### ISSUE TITLE
[🕹️] Side Quest : Follow Papermark on X (Twitter) Account

### ISSUE THREAD

**Issue by abheeshtsingh2803** [mfts/papermark#1003]
### What side quest or challenge are you solving?

Follow [Papermark X (Twitter)](https://x.com/papermarkio) Account (50 Points)

### Points

50

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/d0c0d809-9826-412f-a34f-284ce3fef0fa)

**Comment by mfts** [comment]
/award 50

thanks for the follow
