### ISSUE TITLE
[🕹️]Side Quest : Follow Papermark on X (Twitter) Account and Linkedln Account

### ISSUE THREAD

**Issue by naaa760** [mfts/papermark#1004]
### What side quest or challenge are you solving?

 Follow Papermark on X (Twitter) Account and Linkedln Account

### Points

100

### Provide proof that you've completed the task

![Screenshot from 2024-10-15 11-24-33](https://github.com/user-attachments/assets/be4898c9-9c60-432e-b6fb-d95c0111e14e)
![Screenshot from 2024-10-15 11-23-36](https://github.com/user-attachments/assets/a25c8073-02bd-4038-82e6-fee1f2eac24f)

**Comment by mfts** [comment]
/award 100

thanks for the follow
