### ISSUE TITLE
[🕹️]Follow Papermark X (Twitter) Account

### ISSUE THREAD

**Issue by rajeevDewangan** [mfts/papermark#1007]
### What side quest or challenge are you solving?

Follow [Papermark X (Twitter)] Account

### Points

50

### Description

following Papermark account on X
liked and retweeted the launch post

### Provide proof that you've completed the task

![Screenshot 2024-10-15 122654](https://github.com/user-attachments/assets/204198ac-ffaa-4f70-83b1-190562ec058f)
![Screenshot (1235)](https://github.com/user-attachments/assets/335f5b61-3884-4faa-b0e8-ad495a3a5003)

**Comment by mfts** [comment]
/award 50

thanks for the follow
