### ISSUE TITLE
[🕹️]Follow Papermark LinkedIn Page

### ISSUE THREAD

**Issue by rajeevDewangan** [mfts/papermark#1008]
### What side quest or challenge are you solving?

Follow [Papermark LinkedIn](https://linkedin.com/company/papermarkio) Page

### Points

50

### Description

following Papermark on LinkedIn
liked and commented on the launch post

### Provide proof that you've completed the task

![Screenshot 2024-10-15 123652](https://github.com/user-attachments/assets/55c76441-55d0-4340-b6f3-e3df4f1028cf)
![Screenshot 2024-10-15 123632](https://github.com/user-attachments/assets/fa8e79d5-4b5b-4374-b4e6-92a95f91353d)

**Comment by shuvishma** [comment]
![Screenshot 2024-10-14 233749](https://github.com/user-attachments/assets/26271923-df02-4426-97c6-a83be4af954c)

**Comment by mfts** [comment]
/award 50

thanks for the follow
