### ISSUE TITLE
[🕹️]Follow Papermark Youtube Page

### ISSUE THREAD

**Issue by rajeevDewangan** [mfts/papermark#1009]
### What side quest or challenge are you solving?

Follow [Papermark Youtube] Page

### Points

50

### Description

following Papermark on youtube

### Provide proof that you've completed the task

![Screenshot 2024-10-15 124621](https://github.com/user-attachments/assets/0a9a6b59-6362-4b7e-8ad3-473dff56b764)

**Comment by mfts** [comment]
/award 50

thanks for the follow
