### ISSUE TITLE
Starry-eyed Supporter (150 Points)

### ISSUE THREAD

**Issue by antilpiyush89** [mfts/papermark#1011]
### What side quest or challenge are you solving?

Get 5 people to star our repo

### Points

150 points

### Provide proof that you've completed the task

![IMG-20241015-WA0002](https://github.com/user-attachments/assets/fdd5d454-b0ce-46c7-bdcb-7e6bc93afabf)
![IMG-20241015-WA0003](https://github.com/user-attachments/assets/1d3861a3-841a-4da4-bf07-6fc1fc9d0ce1)
![IMG-20241014-WA0024](https://github.com/user-attachments/assets/33cb4e15-6299-43f3-ae85-251b1f40a1c3)
![IMG-20241015-WA0009](https://github.com/user-attachments/assets/de7be884-fa7d-4bca-992d-bb56e4df32eb)
![IMG-20241015-WA0010(1)](https://github.com/user-attachments/assets/71a4ec69-cbb2-4818-9980-928d3a05f09f)

**Comment by mfts** [comment]
/award 150

thanks for sharing! helps us a lot
