### ISSUE TITLE
[🕹️]Gif Magic

### ISSUE THREAD

**Issue by rajeevDewangan** [mfts/papermark#1012]
### What side quest or challenge are you solving?

Gif Magic

### Points

150

### Description

link : https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExOHFjOHJ6Mm44M283Z3NzNXlyZWFzMHlzNWxrcDlqamE1YTJoMXllaSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/UORA6GN8hiG6X266sQ/giphy.gif

### Provide proof that you've completed the task

![Screenshot 2024-10-15 132102](https://github.com/user-attachments/assets/013c5446-052c-4b8a-9fe7-75c9e2911481)
link: https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExOHFjOHJ6Mm44M283Z3NzNXlyZWFzMHlzNWxrcDlqamE1YTJoMXllaSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/UORA6GN8hiG6X266sQ/giphy.gif

**Comment by mfts** [comment]
/award 150 

that's a really cool effect
