### ISSUE TITLE
[🕹️]Design our new Papermark logo

### ISSUE THREAD

**Issue by rajeevDewangan** [mfts/papermark#1013]
### What side quest or challenge are you solving?

Design our new Papermark logo

### Points

150 Points per logo, 750 for the winner

### Description

two logos

### Provide proof that you've completed the task

1st one : ![Screenshot 2024-10-15 135102](https://github.com/user-attachments/assets/21f9b2b0-be61-4086-a4c4-cf0b2ee9e9fc)
2nd one : ![Screenshot 2024-10-15 135408](https://github.com/user-attachments/assets/41370905-67c8-49e1-ba4d-c937cf5cb66b)

**Comment by mfts** [comment]
/award 150

thanks
