### ISSUE TITLE
[🕹️][Bug]:Unwanted blue border appears heavily on Md screens

### ISSUE THREAD

**Issue by rishipatel9** [mfts/papermark#1015]
### What side quest or challenge are you solving?

![IMG_1338](https://github.com/user-attachments/assets/45f7321a-6442-486f-a81d-0da59d6a6a3e)

### Points

200

### Provide proof that you've completed the task

/aasign

**Comment by spawade99** [comment]
This bug is no more reproducible. 
I hope, I can get some points for investing.
https://github.com/user-attachments/assets/6950ca4c-d8d0-4f84-81d0-965d77cdac09

**Comment by rishipatel9** [comment]
> This bug is no more reproducible. I hope, I can get some points for investing. https://github.com/user-attachments/assets/6950ca4c-d8d0-4f84-81d0-965d77cdac09

Create a pr for it

**Comment by ummm288** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
