### ISSUE TITLE
[🕹️]Follow Papermark LinkedIn Page

### ISSUE THREAD

**Issue by GAURAV8520** [mfts/papermark#1016]
### What side quest or challenge are you solving?

What side quest or challenge are you solving?
Follow [Papermark LinkedIn](https://linkedin.com/company/papermarkio) Page

Points
50

Description
following Papermark on LinkedIn

Provide proof that you've completed the task

### Points

50

### Provide proof that you've completed the task

![Screenshot 2024-10-15 154359](https://github.com/user-attachments/assets/aeb5cee8-a07e-446a-846c-5270e69d8c10)

**Comment by mfts** [comment]
/award 50 

thanks :)
