### ISSUE TITLE
[🕹️]Follow Papermark on X (Twitter) Account

### ISSUE THREAD

**Issue by GAURAV8520** [mfts/papermark#1017]
### What side quest or challenge are you solving?

Follow [Papermark X (Twitter)](https://x.com/papermarkio) Account (50 Points)

### Points

50

### Description

I followed Papermark on X (Twitter) and I have attached the proof of the same.

### Provide proof that you've completed the task

![Screenshot 2024-10-15 154928](https://github.com/user-attachments/assets/7d6aed54-3fca-4a68-921a-64302281112d)
![Screenshot 2024-10-15 155017](https://github.com/user-attachments/assets/3be7e5a9-a2b4-4a9f-93c0-785cada067a3)

**Comment by harjasae2001** [comment]
![{AB406B1C-BD42-4359-914D-5BBED1301E82}](https://github.com/user-attachments/assets/a1352b77-70c7-4195-bb99-0affc6301f8b)

Completed

**Comment by mfts** [comment]
/award 50

thanks for the follow 

---

@harjasae2001 please open your own issue
