### ISSUE TITLE
[🕹️]Youtube Subscribed

### ISSUE THREAD

**Issue by GAURAV8520** [mfts/papermark#1019]
### What side quest or challenge are you solving?

Subscribe to youtube channel.

### Points

50

### Description

Subscribed the youtube channel.

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/22f6ec28-c11e-4b9d-b599-665458bad11b)

**Comment by mfts** [comment]
/award 50

thanks for the support
