### ISSUE TITLE
[🕹️]Follow Papermark Page on Linkedin

### ISSUE THREAD

**Issue by tejaslakade99** [mfts/papermark#1020]
### What side quest or challenge are you solving?

Follow [Papermark LinkedIn](https://linkedin.com/company/papermarkio) Page

### Points

50

### Description

Followed Papermark Page on Linkedin

### Provide proof that you've completed the task

![Screenshot 2024-10-15 at 5 03 05 PM](https://github.com/user-attachments/assets/b1098882-372f-4955-aa34-a010f026a2c6)

**Comment by mfts** [comment]
/award 50

thanks for the follow
