### ISSUE TITLE
[🕹️]Subscribe/Follow Papermark on Youtube

### ISSUE THREAD

**Issue by tejaslakade99** [mfts/papermark#1022]
### What side quest or challenge are you solving?

The side quest to follow Papermark on YouTube

### Points

50

### Description

Followed/Subscribed to Papermark on YouTube

### Provide proof that you've completed the task

![Screenshot 2024-10-15 at 5 07 40 PM](https://github.com/user-attachments/assets/c8fd48b0-3a6a-4c87-a341-86096b69b564)

**Comment by mfts** [comment]
/award 50

thanks for the follow
