### ISSUE TITLE
[🕹️] Follow PaperMark Twitter Page Side Quest

### ISSUE THREAD

**Issue by radheshpai87** [mfts/papermark#1023]
### What side quest or challenge are you solving?

Follow [Papermark X (Twitter)](https://x.com/papermarkio) Account

### Points

50

### Description

Followed [Papermark X (Twitter)](https://x.com/papermarkio) Account

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/b5af9f8b-1c21-42f3-a78a-e31089cf5563)

**Comment by mfts** [comment]
/award 50

thanks for the follow
