### ISSUE TITLE
[🕹️] Follow Papermark LinkedIn Page

### ISSUE THREAD

**Issue by radheshpai87** [mfts/papermark#1024]
### What side quest or challenge are you solving?

Follow [Papermark LinkedIn](https://linkedin.com/company/papermarkio) Page

### Points

50

### Description

I have followed the PaperMark Linkedin Page

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/5e859c76-ce8d-42ba-a526-75f0912ad64e)

**Comment by mfts** [comment]
/award 50

thanks for the follow
