### ISSUE TITLE
[🕹️] Adding Startup Pitch Deck to Gallery

### ISSUE THREAD

**Issue by shreykx** [mfts/papermark#1035]
### What side quest or challenge are you solving?

**Add Startup Pitch Deck to Gallery**

### Points

150

### Description

I uploaded the **[Tesla](https://www.tesla.com)** startup pitch deck to **Papermark** and created a public link for anyone to view.

### Provide proof that you've completed the task

**Link to Papermark- https://www.papermark.io/view/cm2apo25e000112rag5ktxqf8**
**Source - [Tesla](tesla.com)**

**Comment by mfts** [comment]
@shreykx please add yourself in the list that you can be awarded https://drive.google.com/drive/u/1/folders/1M3Wt4px5yKCYRrTnndadO7mdNYYDBNKu
