### ISSUE TITLE
[🕹️] Design our new Papermark logo

### ISSUE THREAD

**Issue by Emmarie-Ahtunan** [mfts/papermark#1041]
### What side quest or challenge are you solving?

Design our new Papermark logo.

### Points

150 Points per logo, 750 for the winner.

### Description

Designed your new Papermark logo.

### Provide proof that you've completed the task

![PapermarkLogo](https://github.com/user-attachments/assets/a0491d8b-768e-4892-8324-dc8f4e0f7f06)

**Comment by SaquibShahid** [comment]
![Screenshot (25)](https://github.com/user-attachments/assets/17c6cfa5-34ff-44d1-9027-587971005b0d)
New PaperMark Logo

**Comment by Emmarie-Ahtunan** [comment]
@SaquibShahid you need to open your own issue for this sidequest. Here is a screenshot of the how-to. 

[Papermark - Hacktoberfest Side Quests & Challenges](https://mfts.notion.site/Papermark-Hacktoberfest-Side-Quests-Challenges-111d3f870f008033935efe9f7702a3dc)

![Screenshot 2024-10-16 at 7 10 31 AM](https://github.com/user-attachments/assets/362133a7-1f4d-4ee7-8899-bd8ccd12ab08)

**Comment by Emmarie-Ahtunan** [comment]
resubmitted due to another person assigning themself to my task. Closing this issue.
