### ISSUE TITLE
[🕹️] [BUG] Link Sheet toggles hidden on mobile devices when "custom social media card toggle" active

### ISSUE THREAD

**Issue by mfts** [mfts/papermark#1046]
### What side quest or challenge are you solving?

On mobile devices the link sheet is not fully shown if the custom social media card is toggled on as it overlapps and hides the overflow fully. 

fix: make sure everything fits in the link sheet even if the social media card is toggled, do not add a horizontal scroll (!!)

![CleanShot 2024-10-16 at 13 22 50@2x](https://github.com/user-attachments/assets/c1cecf18-af50-410c-a393-f35d8c1a9e5e)

### Points

300 Points

### Provide proof that you've completed the task

Open a PR with the working code, detailed explanation of what you did and ideally a video showing the solution

**Comment by hacanand** [comment]
can you please guide us how to setup this project locally

**Comment by ummm288** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by DeepaPrasanna** [comment]
Hey @AshishViradiya153 , how can u work on this without asking me first. Is this against rule. I am working on that

**Comment by DeepaPrasanna** [comment]
Hello @mfts,  may I know your views?
