### ISSUE TITLE
[🕹️] Starry-eyed supporter

### ISSUE THREAD

**Issue by Khaan25** [mfts/papermark#1047]
### What side quest or challenge are you solving?

Starry-eyed supporter

### Points

150

### Provide proof that you've completed the task

![WhatsApp Image 2024-10-15 at 11 40 27_64fa213f](https://github.com/user-attachments/assets/49ff06e2-bf0a-42ca-ab46-57098e2fb0b4)
![WhatsApp Image 2024-10-15 at 11 43 45_ad7fa0da](https://github.com/user-attachments/assets/8f8347ca-733c-4c03-b6bf-3c38b06891cb)
![WhatsApp Image 2024-10-15 at 11 45 44_52509b1f](https://github.com/user-attachments/assets/44fc78e3-3ade-4b87-b700-2e86cdcf6604)
![WhatsApp Image 2024-10-15 at 11 49 22_05a38b9a](https://github.com/user-attachments/assets/4f644803-3332-454a-aff7-1595d7d9f9de)
![WhatsApp Image 2024-10-15 at 16 44 14_912efd4b](https://github.com/user-attachments/assets/27a6b7d1-dd14-414d-b1a8-d001e210f22e)

**Comment by SaquibShahid** [comment]
Done 
![Screenshot (24)](https://github.com/user-attachments/assets/fd11f1cd-6e5a-4b09-ba1d-8ed4faf21942)

**Comment by Shivam1-123** [comment]
![Screenshot 2024-10-16 141611](https://github.com/user-attachments/assets/9d0a0bfd-a0ad-4ea0-947e-7058e107befb)

Done
