### ISSUE TITLE
[🕹️]oss.gg side quest #1045

### ISSUE THREAD

**Issue by vaibhav03ambhore** [mfts/papermark#1048]
### What side quest or challenge are you solving?

Follow [Papermark Youtube](https://www.youtube.com/@papermarkio) Page

### Points

50

### Description

subcribed

### Provide proof that you've completed the task

![Screenshot 2024-10-16 101306](https://github.com/user-attachments/assets/b1e56237-c10a-4836-a77f-31291f2f3f37)

**Comment by haidarabbasbalospura** [comment]
![image](https://github.com/user-attachments/assets/03dfc56d-0834-44f6-8444-1aeba9e851ff)
subscription done

**Comment by SaquibShahid** [comment]
subscription done
![Screenshot (23)](https://github.com/user-attachments/assets/428c1ef0-22b9-4827-b5b4-351c06bc8673)

**Comment by Shivam1-123** [comment]
![Screenshot 2024-10-16 141124](https://github.com/user-attachments/assets/f7f272f7-1f3f-4d40-bff4-24eb71e746c8)

subscription Done.
