### ISSUE TITLE
[🕹️]Unwanted blue border appears heavily on Md screens

### ISSUE THREAD

**Issue by spawade99** [mfts/papermark#1050]
### What side quest or challenge are you solving?

Unwanted blue border appears heavily on Md screens

### Points

200

### Description

Tried to reproduce on prod and locally but not able to reproduce issue.

### Provide proof that you've completed the task

https://github.com/user-attachments/assets/6950ca4c-d8d0-4f84-81d0-965d77cdac09

**Comment by haidarabbasbalospura** [comment]
Since I don't see a border, could you please briefly explain the problem?

**Comment by haidarabbasbalospura** [comment]
> ### What side quest or challenge are you solving?
> Unwanted blue border appears heavily on Md screens
> 
> ### Points
> 200
> 
> ### Description
> Tried to reproduce on prod and locally but not able to reproduce issue.
> 
> ### Provide proof that you've completed the task
>  Blue-Brdr-Bug.mp4.mp4

**Comment by spawade99** [comment]
it’s a submission for #1015

**Comment by ummm288** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
