### ISSUE TITLE
[🕹️]Follow Paper Mark Linkedin Page

### ISSUE THREAD

**Issue by ayyash1** [mfts/papermark#1061]
### What side quest or challenge are you solving?

Follow Paper Mark Linkedin Page

### Points

50

### Description

I followed papermark page on linkedin

### Provide proof that you've completed the task

![376552773-f754f07a-3b7c-4452-9cc1-c2a44ab4ce7b](https://github.com/user-attachments/assets/81284668-1f23-4ee6-a496-b68c77bd0d00)

username : Ayyash Fous

**Comment by Parth002933v** [comment]
I followed papermark page on linkedin

![Screenshot (4)](https://github.com/user-attachments/assets/abb10c2d-1dda-4388-b786-37fbe5e50fed)
