### ISSUE TITLE
[🕹️] Follow Papermark LinkedIn Page

### ISSUE THREAD

**Issue by phanindraadhikari** [mfts/papermark#1063]
### What side quest or challenge are you solving?

[🕹️] Follow Papermark LinkedIn Page

### Points

50

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/af9c9579-68e1-48b7-88fc-7b980bba2743)

**Comment by sanyamhbtu** [comment]
![Screenshot 2024-10-18 195020](https://github.com/user-attachments/assets/55789992-1576-4070-9650-90af2bd2ee3d)
Here’s the screenshot of following your LinkedIn page as requested.
