### ISSUE TITLE
[🕹️] Follow Papermark Youtube Page

### ISSUE THREAD

**Issue by phanindraadhikari** [mfts/papermark#1064]
### What side quest or challenge are you solving?

[🕹️] Follow Papermark Youtube Page

### Points

50

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/c3cf2f09-47cb-41d6-b1b0-d124a0156d30)

**Comment by mfts** [comment]
/award 50 thanks for participation!

@Meetpidev pls open your own issue with proof of completing the quest :
I can only award the author of an issue with points!
