### ISSUE TITLE
Need of sentry integration : Lack of visibility for critical application errors

### ISSUE THREAD

**Issue by Raju-kadel-27** [mfts/papermark#107]
I think it's a must to do integration for monitoring the papermark in future. 😀

**Comment by Raju-kadel-27** [comment]
@mfts If it's a goto signal, I would love to integrate this.

**Comment by mfts** [comment]
not urgent right now. vercel logs are pretty good for now, want to add axiom.co and then eventually add sentry or something similar

**Comment by mfts** [comment]
We added axiom via the vercel integration. Sentry is nice but also heavy and slows down the application.
