### ISSUE TITLE
[🕹️]Followed Papermark LinkedIn Page 

### ISSUE THREAD

**Issue by PranavS1604** [mfts/papermark#1073]
### What side quest or challenge are you solving?

Follow [Papermark LinkedIn](https://linkedin.com/company/papermarkio) Page

### Points

50

### Description

Started following Papermark LinkedIn page.

### Provide proof that you've completed the task

![Screenshot_20241017_011200](https://github.com/user-attachments/assets/0fb429c3-75ba-474b-870f-de4616793666)

**Comment by mfts** [comment]
/award 50 thanks for participation!

@Siddharth-prog 
to everyone else commenting: if you not already, pls open your own issue with proof of completing the quest :
I can only award the author of an issue with points!

more Papermark side quests here 👇
https://mfts.notion.site/Papermark-Hacktoberfest-Side-Quests-Challenges-111d3f870f008033935efe9f7702a3dc
