### ISSUE TITLE
[🕹️] Side Quest submission - Follow Papermark Youtube page

### ISSUE THREAD

**Issue by PratikAwaik** [mfts/papermark#1078]
### What side quest or challenge are you solving?

[🕹️] Follow Papermark Youtube Page

### Points

50

### Provide proof that you've completed the task

<img width="1660" alt="image" src="https://github.com/user-attachments/assets/d78df9b5-06ce-40f0-8da4-8b3b12837695">

Youtube username - @pratikawaik4882 (Pratik Awaik)

**Comment by mayurG2299** [comment]
how to actually do the submission of these type of issues

**Comment by PratikAwaik** [comment]
@mayurG2299 open an issue with the submission proof, like how i did it
