### ISSUE TITLE
[🕹️]Follow Papermark Youtube Page (50 Points)

### ISSUE THREAD

**Issue by A10-g** [mfts/papermark#1080]
### What side quest or challenge are you solving?

Follow [Papermark Youtube](https://www.youtube.com/@papermarkio) Page (50 Points)

### Points

50

### Description

Followed [Papermark Youtube](https://www.youtube.com/@papermarkio) Page (50 Points)

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/5aa832fb-9fc4-4cdf-a8b8-643695189c4c)

**Comment by mfts** [comment]
/award 50 thanks for participation!

@meetVaidya 
to everyone else commenting: if you not already, pls open your own issue with proof of completing the quest :
I can only award the author of an issue with points!

more Papermark side quests here 👇
https://mfts.notion.site/Papermark-Hacktoberfest-Side-Quests-Challenges-111d3f870f008033935efe9f7702a3dc
