### ISSUE TITLE
[🕹️] Following Linkedin page of papermark (50 points)

### ISSUE THREAD

**Issue by Kiran-F** [mfts/papermark#1082]
### What side quest or challenge are you solving?

Followed the Linkedin page of papermark.
liked and commented too.

### Points

50 points

### Description

Followed the Linkedin page of papermark for 50 points.

### Provide proof that you've completed the task

![Screenshot (691)](https://github.com/user-attachments/assets/99c88436-eb29-4dea-be84-a9e3557fc863)
![Screenshot (692)](https://github.com/user-attachments/assets/f1bae2d1-4abc-459e-9eef-0d65caee248e)

**Comment by mfts** [comment]
/award 50 thanks for participation!

@Kiran-F 
to everyone else commenting: if you not already, pls open your own issue with proof of completing the quest :
I can only award the author of an issue with points!

more Papermark side quests here 👇
https://mfts.notion.site/Papermark-Hacktoberfest-Side-Quests-Challenges-111d3f870f008033935efe9f7702a3dc
