### ISSUE TITLE
[🕹️] Followed the youtube page of papermark (50 points)

### ISSUE THREAD

**Issue by Kiran-F** [mfts/papermark#1083]
### What side quest or challenge are you solving?

Followed the youtube page of papermark (50 points)

### Points

50 points for this side quest.

### Description

Followed the youtube of papermark.

### Provide proof that you've completed the task

![Screenshot (690)](https://github.com/user-attachments/assets/cc5e5f46-c562-47d0-a726-481c1622d3d6)

**Comment by mfts** [comment]
/award 50 thanks for participation!

@Roshanchenna 
to everyone else commenting: if you not already, pls open your own issue with proof of completing the quest :
I can only award the author of an issue with points!

more Papermark side quests here 👇
https://mfts.notion.site/Papermark-Hacktoberfest-Side-Quests-Challenges-111d3f870f008033935efe9f7702a3dc
