### ISSUE TITLE
[🕹️] Create a "new" logo for Papermark

### ISSUE THREAD

**Issue by MuhammadNoorani** [mfts/papermark#1085]
### What side quest or challenge are you solving?

Design our new Papermark logo.

### Points

150 Points for logo, 750 for winners

### Description

I designed a logo and understand you'll be awarding only once. However, I’ve created several variations to give the team more options to select the best one. 

Also, I see you’ll be running a voting process on Twitter/X—my username is @MuhamadN_twts.   

The story behind the Papermark logo design is rooted in its core function : 
- Transforming documents into shareable links and securely managing data rooms. 
- The concept of lined documents is captured in the logo. 
- The side borders represent the path—the secure framework in which documents are stored and shared. 
- The link icon within the design captures the idea of connecting or linking documents seamlessly, bringing to life the essence of Papermark’s mission.

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/afa35b0e-275e-48be-9815-8a043df490cd)

![Logo 1](https://github.com/user-attachments/assets/a25f2180-36df-4e74-81fd-6f47d060f0d1)
![Logo 2](https://github.com/user-attachments/assets/75ac4ef8-0b6b-4db3-b87b-a1880c381759)
![Logo 3](https://github.com/user-attachments/assets/d8883789-754e-4cb1-8883-b34378b13e24)
![Logo 4](https://github.com/user-attachments/assets/4f01e868-f8ce-490f-9d5a-a2b99fa8530d)
![Logo 5](https://github.com/user-attachments/assets/0c536959-7410-4ab9-a301-818a69f97018)
![Logo 6](https://github.com/user-attachments/assets/5551d4cd-3f27-4f62-96bc-c7c6e15480d9)
![Logo 7](https://github.com/user-attachments/assets/b8c2ccc7-9041-4206-a5d8-300537a6ce31)
![Logo 8](https://github.com/user-attachments/assets/37c1605d-c7a2-4f28-8e4e-30e50ee44acb)
![Logo 9](https://github.com/user-attachments/assets/70320191-012e-4606-987f-e267ed2d2497)
![Logo 10](https://github.com/user-attachments/assets/f1ccbc28-9a22-41ac-8bef-333fd61f8328)
![Logo 11](https://github.com/user-attachments/assets/9027067f-f9d9-4b90-8e90-adc3249bbb3b)
![Logo 12](https://github.com/user-attachments/assets/1fced781-9ef9-429c-ad5c-818be3dbadc1)

**Comment by MuhammadNoorani** [comment]
@mfts what is the process to open a draft PR linking this issue??

**Comment by mfts** [comment]
/ award 150

We will let you know closer to voting time, end of the month. 

Thanks for logos we take one of this!

**Comment by MuhammadNoorani** [comment]
> /award 150
> 
> We will let you know closer to voting time, end of the month.
> 
> Thanks for logos we take one of this!

@mfts 
Thanks for the points! Feel free to pick whichever one you think is best for voting. If I get the chance, I’ll  choose one to add for voting.
