### ISSUE TITLE
[🕹️]Side Quest : Follow Papermark on Youtube

### ISSUE THREAD

**Issue by PritBlitz** [mfts/papermark#1089]
### What side quest or challenge are you solving?

Side Quest : Follow Papermark on Youtube

### Points

50

### Provide proof that you've completed the task

![Screenshot 2024-10-17 172210](https://github.com/user-attachments/assets/7d479d82-0b5e-472e-beb4-d95a0b365c2a)

**Comment by VaibhavK03** [comment]
should I have to create a PR for this also?? @PritBlitz
