### ISSUE TITLE
[🕹️]Side Quest: Follow Papermark in LinkedIn

### ISSUE THREAD

**Issue by arkokundu500** [mfts/papermark#1095]
### What side quest or challenge are you solving?

Side Quest: Follow Papermark in LinkedIn

### Points

50

### Description

Following Papermark in LinkedIn

### Provide proof that you've completed the task

![papermark](https://github.com/user-attachments/assets/c15423c2-b308-4f45-af2a-be3e63b7868c)

**Comment by Aryankanojia9654** [comment]
Proof of Completion
Hi team,

I've completed the task to follow Papermark on LinkedIn as requested. Please find the screenshot attached below as proof.

![image](https://github.com/user-attachments/assets/fa00b449-45bf-4eb0-8b71-fb76cb8d4ab3)



Thank you, and let me know if any further action is required!
