### ISSUE TITLE
[🕹️]Subscribe papermark on YouTube

### ISSUE THREAD

**Issue by rohit0796** [mfts/papermark#1099]
### What side quest or challenge are you solving?

Subscribe papermark on YouTube

![Screenshot 2024-10-17 192844](https://github.com/user-attachments/assets/f8c0de77-ec1f-45cf-b63d-a834582e2471)

### Points

50

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/045cd027-cf98-43ed-944c-ab4705bdb6ed)

**Comment by nikhileshkumar21** [comment]
![image](https://github.com/user-attachments/assets/5a02b9ff-ef9a-42cf-a34f-c6ac8c65a974)
