### ISSUE TITLE
[🕹️]Followed  Papermark Youtube Page (50 Points):

### ISSUE THREAD

**Issue by soummyaanon** [mfts/papermark#1104]
### What side quest or challenge are you solving?

 i have follwed Follow [Papermark Youtube](https://www.youtube.com/@papermarkio) Page 
with the Youtube Handel [Soumyranjan Panda](https://www.youtube.com/@soumyaranjanpanda6661)

### Points

50

### Description

 i have follwed Follow [Papermark Youtube](https://www.youtube.com/@papermarkio) Page 
with the Youtube Handel [Soumyranjan Panda](https://www.youtube.com/@soumyaranjanpanda6661)

### Provide proof that you've completed the task

Proof 
![Screenshot 2024-10-17 at 10 58 26 PM](https://github.com/user-attachments/assets/6a5da545-ea02-44c8-a6f1-a43b1ed7cc02)

**Comment by Hv271005** [comment]
What side quest or challenge are you solving?
i have follwed Follow [Papermark Youtube](https://www.youtube.com/@papermarkio) Page
with the Youtube Handel [Soumyranjan Panda](https://www.youtube.com/@soumyaranjanpanda6661)

Points
50

Description
i have follwed Follow [Papermark Youtube](https://www.youtube.com/@papermarkio) Page
with the Youtube Handel [Soumyranjan Panda](https://www.youtube.com/@soumyaranjanpanda6661)

Provide proof that you've completed the task
Proof
![Screenshot 2024-10-19 114503](https://github.com/user-attachments/assets/22a90b5a-a2f5-4f2f-aa70-8321d4de62b5)
