### ISSUE TITLE
[🕹️] Follow Papermark on YouTube (50 points)

### ISSUE THREAD

**Issue by abdulrehmanwaseem** [mfts/papermark#1107]
### What side quest or challenge are you solving?

Papermark now has a Youtube channel.

### Points

50

### Provide proof that you've completed the task

![Screenshot 2024-10-13 233928](https://github.com/user-attachments/assets/1c8f177b-5ab6-4b0e-8cc7-8b683364d0e4)

**Comment by prathamesh424** [comment]
/award 50 
![Screenshot 2024-10-18 104745](https://github.com/user-attachments/assets/6ad47bbe-eb04-4fc0-b56e-e50b1b1f242f)
