### ISSUE TITLE
[🕹️] Followed Papermark LinkedIn Page as a Side quest

### ISSUE THREAD

**Issue by DanishAliUmar** [mfts/papermark#1110]
### What side quest or challenge are you solving?

Followed [Papermark LinkedIn](https://linkedin.com/company/papermarkio) Page

With the linkein Handel [Danish Ali](https://www.linkedin.com/in/danish-umar)

### Points

50

### Description

Followed [Papermark LinkedIn](https://linkedin.com/company/papermarkio) Page

With the linkein Handel [Danish Ali](https://www.linkedin.com/in/danish-umar)

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/e43710ef-6b8e-4191-8744-ff05da1ed560)

**Comment by mfts** [comment]
already awarded
