### ISSUE TITLE
[🕹️]  Starry-eyed Supporter - [<Abdul_Rehman />] 🌟

### ISSUE THREAD

**Issue by abdulrehmanwaseem** [mfts/papermark#1113]
### What side quest or challenge are you solving?

I am solving the "Starry-eyed Supporter" side quest.

This involves getting 5 friends to star the repositories participating in the oss.gg hackathon and submitting screenshots as proof in each repository's issues.

### Points

1050

### Description

I've completed the "Starry-eyed Supporter" side quest by getting 5 friends to star this repository! 🎉

As requested, here are screenshots from their GitHub profiles showing their usernames and recent starred repositories, including this one:

### Provide proof that you've completed the task

> As requested, here are screenshots from their GitHub profiles showing their usernames and recent starred repositories, including this one:
![Screenshot 2024-10-19 122040](https://github.com/user-attachments/assets/a5e5f21b-d30e-44d8-82e3-f2d5210ce8d8)
![Screenshot 2024-10-19 122131](https://github.com/user-attachments/assets/1f1294c8-c0f4-440f-aa82-c22d6533c5eb)
![Screenshot 2024-10-19 122137](https://github.com/user-attachments/assets/f54cf2fc-3d26-40b4-90b5-189c76e946dd)
![Screenshot 2024-10-19 122142](https://github.com/user-attachments/assets/7918891f-0e41-42ba-a774-08cb4a4c707c)
![Screenshot 2024-10-19 122148](https://github.com/user-attachments/assets/0a0e3ce4-6d0c-41dc-b3b2-098cd9e39cb4)

**Comment by JeevaRamanathan** [comment]
Hi @abdulrehmanwaseem, the images are not loaded properly. Would you mind checking that and re-updating them.
![image](https://github.com/user-attachments/assets/d2d46cd5-6425-4969-b0ca-78cef1378d1f)

**Comment by abdulrehmanwaseem** [comment]
> Hi @abdulrehmanwaseem, the images are not loaded properly. Would you mind checking that and re-updating them. ![image](https://private-user-images.githubusercontent.com/64531160/378003857-d2d46cd5-6425-4969-b0ca-78cef1378d1f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzMjI2MDYsIm5iZiI6MTcyOTMyMjMwNiwicGF0aCI6Ii82NDUzMTE2MC8zNzgwMDM4NTctZDJkNDZjZDUtNjQyNS00OTY5LWIwY2EtNzhjZWYxMzc4ZDFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE5VDA3MTgyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxNzhmOTc3M2EwZDE1MjZlNTk0ZDgzMTljMTM4NGE1OWUwMWY0MjU3NWQzODQxYTIyOTNjYmUxYTFjM2NjYmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-VSMLb0NTSQiZ1JCtVK5DmuNPisN64WiEZQq6lBZ_5c)

:: check now

**Comment by abdulrehmanwaseem** [comment]
@mfts please award me 1050 it been a day i think so

**Comment by mfts** [comment]
See the answer to your duplicate issue #1140 

> These accounts either don't exist or have been opened only to star a repo.
> 
> Do not do this otherwise we ban you from the competition.
> 
> All accounts need to be older than 1 year to comply with the challenge

---
Do not open an issue twice! This can also get you banned from the competition. Play fair!
