### ISSUE TITLE
[🕹️] /reward 50 for  subscribe on youtube 

### ISSUE THREAD

**Issue by prathamesh424** [mfts/papermark#1116]
### What side quest or challenge are you solving?

What side quest or challenge are you solving?
i have follwed Follow [Papermark Youtube](https://www.youtube.com/@papermarkio) Page
 

Points
50

Description
i have follwed Follow [Papermark Youtube](https://www.youtube.com/@papermarkio) Page
 

Provide proof that you've completed the task

### Points

points 50 

### Provide proof that you've completed the task

Proof
 
![Screenshot 2024-10-18 104745](https://github.com/user-attachments/assets/709610a4-9014-47e7-9db7-aca3877d940e)

**Comment by KUNDAN1334** [comment]
![image](https://github.com/user-attachments/assets/03684ae4-44dd-479a-96a9-14871d2a39ef)
