### ISSUE TITLE
[🕹️] Gif Magic (150 Points)

### ISSUE THREAD

**Issue by tejaslakade99** [mfts/papermark#1120]
### What side quest or challenge are you solving?

Gif Magic

### Points

150

### Description

Created a GIF

### Provide proof that you've completed the task

![supermeme_17h29_33](https://github.com/user-attachments/assets/ac922fde-6e32-435a-b23d-a0cd424d4a81)

**Comment by Anonymous-RD** [comment]
intresting one  but where to update the gif
