### ISSUE TITLE
[🕹️]Design our new Papermark logo (150 Points per logo, 750 for the winner)

### ISSUE THREAD

**Issue by sahiladit** [mfts/papermark#1129]
### What side quest or challenge are you solving?

Design our new Papermark logo (150 Points per logo, 750 for the winner)

### Points

150 Points per logo, 750 for the winner

### Description

Created A Logo!

### Provide proof that you've completed the task

![WhatsApp_Image_2024-10-19_at_12 07 30_AM-transformed](https://github.com/user-attachments/assets/44014483-a291-433f-83ff-b6f8305cd93e)

**Comment by sureshjangid** [comment]
What side quest or challenge are you solving?
Design our new Papermark logo (150 Points per logo, 750 for the winner)

Points
150 Points per logo, 750 for the winner

Description
Created A Logo!

Provide proof that you've completed the task
![logo-2](https://github.com/user-attachments/assets/841ba3dc-bf08-4dd6-8c29-5bc69c6902c6)
![logo-1](https://github.com/user-attachments/assets/63e92d1d-28d5-41a5-be56-a5bbd0d36405)

**Comment by mfts** [comment]
/award 150

---

@sureshjangid please open your own issue
