### ISSUE TITLE
Modification in README file.

### ISSUE THREAD

**Issue by dipakja** [mfts/papermark#113]
I just went through your README file.
And I found irrelevant words in the inspiration section.
If it has meaning, then it's ok to have.

![Readme-bug](https://github.com/mfts/papermark/assets/104189165/c4b8fa2f-a6df-46f8-85d1-a490f1f42822)

**Comment by dipakja** [comment]
![Readme](https://github.com/mfts/papermark/assets/104189165/fd75b8db-af8b-4eaf-b570-cc72d6a73b26)

**Comment by mfts** [comment]
Oh that's meant to be there hehe. I consider "dub" and @steven-tey my internet friend :)
