### ISSUE TITLE
[🕹️]Followed Papermark LinkedIn Page as a Side quest

### ISSUE THREAD

**Issue by DanishAliUmar** [mfts/papermark#1130]
### What side quest or challenge are you solving?

Followed [Papermark LinkedIn](https://linkedin.com/company/papermarkio) Page

With the linkein Handel [Danish Ali](https://www.linkedin.com/in/danish-umar)

### Points

50

### Description

Followed [Papermark LinkedIn](https://linkedin.com/company/papermarkio) Page

With the linkein Handel [Danish Ali](https://www.linkedin.com/in/danish-umar)

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/585be58f-f9ce-468c-b786-1486b1652ee7)

**Comment by ajeetkumarrauniyar** [comment]
> Assigned to @ajeetkumarrauniyar! Please open a draft PR linking this issue within 48h ⚠️ If we can't detect a PR from you linking this issue in 48h, you'll be unassigned automatically 🕹️ Excited to have you ship this 🚀

Completed the Side Quest as per the instructions provided, 

https://github.com/mfts/papermark/issues/1134

**Comment by ajeetkumarrauniyar** [comment]
Completed the Side Quest
