### ISSUE TITLE
[🕹️] Starry-eyed Supporter - [<Abdul_Rehman />] 🌟

### ISSUE THREAD

**Issue by abdulrehmanwaseem** [mfts/papermark#1140]
### What side quest or challenge are you solving?

I am solving the "Starry-eyed Supporter" side quest.

This involves getting 5 friends to star the repositories participating in the oss.gg hackathon and submitting screenshots as proof in each repository's issues.

### Points

1050

### Description

I've completed the "Starry-eyed Supporter" side quest by getting 5 friends to star this repository! 🎉

As requested, here are screenshots from their GitHub profiles showing their usernames and recent starred repositories, including this one:

### Provide proof that you've completed the task

As requested, here are screenshots from their GitHub profiles showing their usernames and recent starred repositories, including this one:
![Screenshot 2024-10-19 122040](https://github.com/user-attachments/assets/ca52ab37-3c6f-4797-a8bd-1018daf09cc9)
![Screenshot 2024-10-19 122131](https://github.com/user-attachments/assets/36022e54-094d-4b18-a812-67f29405746c)
![Screenshot 2024-10-19 122137](https://github.com/user-attachments/assets/437da57a-2233-4f2f-be12-d8020163f0de)
![Screenshot 2024-10-19 122142](https://github.com/user-attachments/assets/6971ae90-5618-4fd4-9011-17b9f8e64e61)
![Screenshot 2024-10-19 122148](https://github.com/user-attachments/assets/55bbc523-7fe3-463b-89f2-a7336c584eb3)

**Comment by mfts** [comment]
These accounts either don't exist or have been opened only to star a repo. 

Do not do this otherwise we ban you from the competition. 

All accounts need to be older than 1 year to comply with the challenge
