### ISSUE TITLE
[🕹️]Add Startup Pitch Deck to Gallery (150 Points)

### ISSUE THREAD

**Issue by tejaslakade99** [mfts/papermark#1146]
### What side quest or challenge are you solving?

Add Startup Pitch Deck to Gallery (150 Points)

### Points

150

### Description

https://www.papermark.io/view/cm2g2nygn0003uco13h8vgsj0

### Provide proof that you've completed the task

# Pitch Deck Starting Page
![Screenshot 2024-10-19 at 4 57 05 PM](https://github.com/user-attachments/assets/3b1341ca-5e4b-40ba-a32c-1c018ada87a4)

**Comment by mfts** [comment]
@tejaslakade99  

Can you add you deck here and add yourself in the list 
https://drive.google.com/drive/u/1/folders/1M3Wt4px5yKCYRrTnndadO7mdNYYDBNKu

**Comment by mfts** [comment]
@Aryankanojia9654  please open separate issue, if you completed it.
