### ISSUE TITLE
[🕹️]side quest Like & Re-Tweet oss.gg Launch Tweet and following papermark on X 

### ISSUE THREAD

**Issue by adilkadivala** [mfts/papermark#1149]
### What side quest or challenge are you solving?

side quest 

Like & Re-Tweet oss.gg Launch Tweet (50 Points)
following papermark on x (50 Points)

Like and retweet the side quest post of Papermark.

### Points

100

### Description

Like and retweet the side quest post of Papermark.

### Provide proof that you've completed the task

![post](https://github.com/user-attachments/assets/8284d82b-a887-46b0-be2c-038d35567b6a)

https://x.com/adil_kadival/status/1847639393395482797

![followed](https://github.com/user-attachments/assets/52debb79-01e0-4a90-93b3-f3aa915743fb)

**Comment by mfts** [comment]
/award 50 

the retweet launch tweet is only award once by formbricks who manages the ossgg account
