### ISSUE TITLE
[🕹️]Logo OF papermark

### ISSUE THREAD

**Issue by Meetpidev** [mfts/papermark#1153]
### What side quest or challenge are you solving?

Logo of papermark

### Points

450

### Description

Logo of papermark

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/4480245b-a725-4a08-8695-2626dc02cc84)
![Screenshot 2024-10-19 201735](https://github.com/user-attachments/assets/678df0f9-2ff1-45d7-934f-6e69219737f1)
![image](https://github.com/user-attachments/assets/8c7fc9e3-fe55-4cab-9dd7-c9941534744d)

**Comment by Meetpidev** [comment]
@mfts Please Review It

**Comment by Meetpidev** [comment]
@mfts Please Review It

**Comment by abdulrehmanwaseem** [comment]
assign

**Comment by Meetpidev** [comment]
> /assign

Open Your new isuue..

**Comment by Meetpidev** [comment]
@mfts Please Review it

**Comment by Meetpidev** [comment]
@mfts Please Review It
