### ISSUE TITLE
[🕹️]Gif Magic (150 Points) + Meme Magic (150 Points)

### ISSUE THREAD

**Issue by Sam-at-code** [mfts/papermark#1158]
### What side quest or challenge are you solving?

]Gif Magic (150 Points) + Meme Magic (150 Points)

### Points

300 (150+150)

### Description

Solved both the side quests at once

### Provide proof that you've completed the task

![Screenshot 2024-10-19 234205](https://github.com/user-attachments/assets/6637770a-cfaa-4e86-a3b9-bccbe0cc610b)
![Screenshot 2024-10-19 234453](https://github.com/user-attachments/assets/0da62574-5b46-4bd4-8646-b22a4f8b4b54)

**Comment by mfts** [comment]
@Sam-at-code please share the link to the gif
