### ISSUE TITLE
[🕹️] Mismatch in Text for Delete Group and Delete Team Popups Despite Same Name

### ISSUE THREAD

**Issue by AshishViradiya153** [mfts/papermark#1163]
### What side quest or challenge are you solving?

![new issue](https://github.com/user-attachments/assets/2409d6f2-b9c9-485d-960c-6337a8aa52e7)
![image](https://github.com/user-attachments/assets/23cd9230-85e4-45e5-9aae-4d42d0c258e7)

### Points

@mfts ?

### Provide proof that you've completed the task

PR

**Comment by AshishViradiya153** [comment]
@uluckydev do not start work on it, PR in review

**Comment by uluckydev** [comment]
@AshishViradiya153 Okay. But is it fine to use a form validation library instead?

**Comment by AshishViradiya153** [comment]
@uluckydev, yes, using a form validation library(zod) can be a great idea! However, for that, maybe we should create a separate issue and PR in the future.

**Comment by uluckydev** [comment]
It looks good to me. No format errors if the string match. This error is coming only if added an extra space at the the end. Which can be fixed easily. 
@AshishViradiya153  is that what you are recommending?

**Comment by AshishViradiya153** [comment]
Yes

**Comment by uluckydev** [comment]
fixed on #1180
