### ISSUE TITLE
 Side quest: Follow Papermark on YouTube

### ISSUE THREAD

**Issue by nepalankit** [mfts/papermark#1165]
### What side quest or challenge are you solving?

The side quest of Following Papermark on YouTube.

### Points

50

### Description

Followed Papermark on YouTube.

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/84f1c75b-1b3e-435a-af47-3c202b2adae6)

**Comment by Anurag-singh-thakur** [comment]
@nepalankit can i work on that issue
