### ISSUE TITLE
[🕹️][🕹️] Design our new Papermark logo 

### ISSUE THREAD

**Issue by nepalankit** [mfts/papermark#1181]
### What side quest or challenge are you solving?

Design our new Papermark logo 

### Points

15o to 750

### Description

Designed a new Papermark logo 

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/0e917616-5818-4128-b6a0-a18bed51dd28)

**Comment by Anirudhchauhan04** [comment]
What side quest or challenge are you solving?
Design our new Papermark logo

Points
15o to 750

Description
Designed a new Papermark logo

Provide proof that you've completed the task
![Anirudh_chauhan_design_a_logo_for_papermark_make_minimilistic_and_83104caf-808d-4cc1-8f5e-dc60f10c1119](https://github.com/user-attachments/assets/22bee7ba-29a6-472c-9cc1-ad46f9ecad22)

**Comment by mfts** [comment]
/award 150 

---
@Anirudhchauhan04 please open your own issue
