### ISSUE TITLE
Assigned to @techwizard31! 🕹️ Excited to have you ship this 🚀 -- issue1178

### ISSUE THREAD

**Issue by techwizard31** [mfts/papermark#1182]
Assigned to @techwizard31! Please open a draft PR linking this issue within 48h ⚠️ If we can't detect a PR from you linking this issue in 48h, you'll be unassigned automatically 🕹️ Excited to have you ship this 🚀

_Originally posted by @oss-gg[bot] in https://github.com/mfts/papermark/issues/1178#issuecomment-2424857918_

I have added pitch decks of 10 popular companies into the excel sheet with author name as 'techwizard' and also added the pdfs of the decks to the google drive.

I have also added the proof of it 
![Screenshot (63)](https://github.com/user-attachments/assets/5526e9f4-cd39-437b-94dc-b831500291c0)

**Comment by mfts** [comment]
/award 1500 Thanks for adding so many decks!
