### ISSUE TITLE
[🕹️] Pitch deck

### ISSUE THREAD

**Issue by AshishViradiya153** [mfts/papermark#1183]
### What side quest or challenge are you solving?

23 Pitch deck

![image](https://github.com/user-attachments/assets/cc613846-96a5-4ca0-a24f-75dde6d99f40)
![image](https://github.com/user-attachments/assets/38c78ffe-64fd-44c1-9f55-43853a1bc3c7)

### Points

@mfts ?

### Provide proof that you've completed the task

IMAGE

**Comment by mfts** [comment]
/award 1500

Thanks so much for adding decks!
