### ISSUE TITLE
[🕹️] Follow Papermark LinkedIn Page

### ISSUE THREAD

**Issue by soamn** [mfts/papermark#1189]
### What side quest or challenge are you solving?

Follow [Papermark LinkedIn](https://linkedin.com/company/papermarkio) Page

### Points

50

### Description

Linkedin Profile Link- https://www.linkedin.com/in/soamn/

### Provide proof that you've completed the task

![Screenshot 2024-10-20 225014](https://github.com/user-attachments/assets/1292f4b2-9206-439c-96dc-d5e98d5b954a)

**Comment by Afza-Khursheed123** [comment]
What side quest or challenge are you solving?
Follow [Papermark LinkedIn](https://linkedin.com/company/papermarkio) Page

Points
50

Description
Linkedin Profile Link- https://www.linkedin.com/in/afza-khursheed-3470432a7/

Provide proof that you've completed the task
![image](https://github.com/user-attachments/assets/347c17f9-ada5-4931-bae2-d6bdd711d508)
