### ISSUE TITLE
[🕹️]I subscribed to paperMark channel on YouTube

### ISSUE THREAD

**Issue by prabalai** [mfts/papermark#1197]
### What side quest or challenge are you solving?

I subscribed to paperMark channel on YouTube

### Points

50

### Provide proof that you've completed the task

![Screenshot 2024-10-21 093836](https://github.com/user-attachments/assets/babe47d5-e587-4ca3-8ef8-4ae7cf983aec)

**Comment by ashanviii** [comment]
![Screenshot 2024-10-21 171116](https://github.com/user-attachments/assets/aeebe570-4ad2-4baf-8985-f3adaae9383d)
