### ISSUE TITLE
Verify email address in order to view the document

### ISSUE THREAD

**Issue by mfts** [mfts/papermark#120]

**Comment by digant2482** [comment]
Hi, @mfts. Can I work on this issue ?

**Comment by mfts** [comment]
Yes absolutely. Please use resend and the helper `sendEmail` function in `lib/resend.ts` to make it happen. 

It's probably good to generate a token when a user enters the email to view the document. 

Let me know if you have any questions

**Comment by digant2482** [comment]
Hi @mfts, just to be clear, here's the process: 
1) generate a random n digit throwaway code,
2) send to email via resend (sendEmail function)
3) User enters the code, views the documents.

If above steps are clear. Do we have any specific code generator library in mind or I can use any code generator ?

**Comment by mfts** [comment]
@digant2482 I think we can skip the entering of the code. Just attach it as a url parameter and then verify the code server-side. 

Otherwise sounds good

**Comment by digant2482** [comment]
Ok, got it. Thank you for clarification

**Comment by digant2482** [comment]
Hi, @mfts. I am almost done. Will release PR tomorrow. Just wanted to take feedback on current progress. I have attached the video. The email html is ready, backend is done. Some tests are remaining. Please suggest if any changes are there. Thank you.

https://github.com/mfts/papermark/assets/73285842/5a12de47-30e3-4bbc-b0c7-4fb278ec86cc

**Comment by digant2482** [comment]
Hi, here's complete version. Few caveats: 
a) Verification codes are stored in-memory (as they are throwaway), I can modify if they are needed to be stored in database.
b) I was trying to configure resend. But there was a bug I guess, I kept getting error (missing 'from' field), but I have made React file similar to view-document.tsx. I guess it should work in production as it is identical to every other email sending function. If needed, happy to test locally, though might need some advice.


https://github.com/mfts/papermark/assets/73285842/55b9c0b7-ae2b-4be0-8b38-5efcfaf0f9b5

**Comment by digant2482** [comment]
#131

**Comment by digant2482** [comment]
closes #131

**Comment by digant2482** [comment]
"Hi @mfts, I created PR #131. Please review and revert if any changes/modifications are required."

**Comment by mfts** [comment]
Thanks @digant2482 looks really good! I will check the PR today!

**Comment by ashrafchowdury** [comment]
This feature has been added to the application and I think we can now close this issue here @mfts
