### ISSUE TITLE
[🕹️] Papermark's New Logo Design (Icon + Wordmark)

### ISSUE THREAD

**Issue by AdityaSharmaHub** [mfts/papermark#1200]
### What side quest or challenge are you solving?

Create a "new" logo for Papermark

### Points

150 Points per logo, 750 for the winner

### Description

Designed a logo with an (icon + wordmark) format 

### Light Mode:
![Papermark](https://github.com/user-attachments/assets/75e30440-293f-4c94-b6f1-5bcdf978ea24)

### Dark Mode:
![Papermark Invert](https://github.com/user-attachments/assets/23ea91df-c402-44b8-aeb4-7d142b14fb38)

**Comment by AdityaSharmaHub** [comment]
Twitter - sharmaadityax

**Comment by mfts** [comment]
awarded in #1187
