### ISSUE TITLE
[🕹️] Add pitch deck (150 points)

### ISSUE THREAD

**Issue by aritradevelops** [mfts/papermark#1209]
### What side quest or challenge are you solving?

Add pitch deck (150 points) #1178

### Points

10 x 150 = 1500

### Description

I have added 10 popular public pitch decks and updated my entry in the sheet given

### Provide proof that you've completed the task

<img width="1440" alt="image" src="https://github.com/user-attachments/assets/b7985114-8abc-494a-8cf7-71a7d04082ca">

<img width="1396" alt="image" src="https://github.com/user-attachments/assets/0b7c1b22-013a-483a-b0a8-82b94ff762d3">

**Comment by ummm288** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
