### ISSUE TITLE
[🕹️] Build testimonials database structure

### ISSUE THREAD

**Issue by sytnikov** [mfts/papermark#1210]
### What side quest or challenge are you solving?

Build testimonials database structure

### Points

1500

### Description

I'm creating a page for the Papermark website to collect Customer Testimonials. It will have filters for the types of the companies. Also, for some companies there will be cards leading to customer stories on other pages.

### Provide proof that you've completed the task

Here's the repo with the code: https://github.com/sytnikov/paperwork-customer-testimonials

**Comment by sytnikov** [comment]
@mfts the issue is completed

**Comment by mfts** [comment]
@shnai0 and I will review it. 

Thanks :)

**Comment by ummm288** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by mfts** [comment]
Thanks @sytnikov ! 

/award 1500
