### ISSUE TITLE
[🕹️]follow on X

### ISSUE THREAD

**Issue by AshishViradiya153** [mfts/papermark#1212]
### What side quest or challenge are you solving?

Ashish Viradiya

<img width="680" alt="Screenshot 2024-10-22 at 9 15 30 AM" src="https://github.com/user-attachments/assets/da62bcd8-55e0-4e4f-af58-68f7a93e1403">

### Points

@mfts ?

### Provide proof that you've completed the task

ScreenShort

**Comment by mfts** [comment]
@AshishViradiya153 what's your handle?

**Comment by AshishViradiya153** [comment]
@mfts  https://x.com/Ashish129570796
