### ISSUE TITLE
[🕹️]follow papermark on LinkedIn

### ISSUE THREAD

**Issue by vamus092** [mfts/papermark#1215]
### What side quest or challenge are you solving?

Follow PaperMark on LinkedIn

### Points

50

### Provide proof that you've completed the task

![Uploading image.png…]()

**Comment by mfts** [comment]
@vamus092 please add a working screenshot

**Comment by vamus092** [comment]
![image](https://github.com/user-attachments/assets/53796c7e-8c05-473e-a875-7f93f11b2b01)

**Comment by vamus092** [comment]
here is the working screenshot,
