### ISSUE TITLE
[🕹️] Add help / info tips to link settings

### ISSUE THREAD

**Issue by mfts** [mfts/papermark#1229]
### What side quest or challenge are you solving?

Currently the link settings may not be 100% clear from just the name of the link option. Therefore we want to add a small tooltip with a brief one-liner explaining the option (if you don't feel comfortable writing it in english, use an LLM to feed the option and help article to summarize it in one short sentence) and linking out to a help article for more information. 

Please use shadcn components, there's already a tooltip component in place. utilize it 

here are the link help articles. 

![CleanShot 2024-10-22 at 22 26 16@2x](https://github.com/user-attachments/assets/63313390-4057-4e32-baf2-15569757d1aa)

## Inspiration

Dub.co's info tooltip is definitely an inspiration
![CleanShot 2024-10-22 at 22 24 37@2x](https://github.com/user-attachments/assets/8d8a564b-7f79-42c6-8075-8bb4dba888fd)

---

## Bonus:
+150 Points
Checkout other help articles (https://www.papermark.io/help) and add info tooltips to relevant sections of the app where it makes sense

### Points

300 points (+150 bonus points)

### Provide proof that you've completed the task

Open a PR with the working clean code and a quick video showing off the tooltip

**Comment by ummm288** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
