### ISSUE TITLE
[🕹️] Starry-eyed Supporter

### ISSUE THREAD

**Issue by rajeevDewangan** [mfts/papermark#1246]
### What side quest or challenge are you solving?

Starry-eyed Supporter

### Points

150

### Description

github accounts:
https://github.com/umairullah0905
https://github.com/akaswang
https://github.com/umeshs25
https://github.com/giteshsarvaiya
https://github.com/Hamsegg

### Provide proof that you've completed the task

![Screenshot 2024-10-23 124939](https://github.com/user-attachments/assets/0d6af49a-c5be-4ae1-b5d0-43dc32bb6604)
![Screenshot 2024-10-23 125032](https://github.com/user-attachments/assets/060bd08b-26f8-46c9-966b-3589ec616e83)
![Screenshot 2024-10-23 125102](https://github.com/user-attachments/assets/f68ed9e7-a471-4bbf-9023-b2682f38dc4a)
![Screenshot 2024-10-23 125133](https://github.com/user-attachments/assets/8440f950-4158-4a6d-9cdc-41be30932791)
![Screenshot 2024-10-23 125158](https://github.com/user-attachments/assets/b040ec4b-cfbb-4bfc-98a3-9b2362a02063)
![yash1](https://github.com/user-attachments/assets/8eea9ba8-8228-428a-8793-280907cb9398)
![gitesh1](https://github.com/user-attachments/assets/ccffa23b-0940-4c27-a9a5-6e48605329eb)
![umesh1](https://github.com/user-attachments/assets/8a0b0ae9-f6c6-4e97-8ccc-4085570d5864)
![akash1](https://github.com/user-attachments/assets/97af4814-faf2-4215-8aa1-4cf6e0450299)
![umair1](https://github.com/user-attachments/assets/c2703f83-9fb0-428e-b310-20cac5c4e4d9)

**Comment by ummm288** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
