### ISSUE TITLE
[🕹️] Solved 3 side quests

### ISSUE THREAD

**Issue by RajuGangitla** [mfts/papermark#1248]
### What side quest or challenge are you solving?

Solved 3 side quests

### Points

150

### Provide proof that you've completed the task

1. Follow on X (50 points)
![image](https://github.com/user-attachments/assets/7edc5c56-9f7f-4aed-bdd3-46c7ee493fb6)

2. Follow on Linkedin (50 points)
![image](https://github.com/user-attachments/assets/ce5ab0a5-e379-4540-8452-ea46c9604a6d)

3.  Follow on Youtube (50 points)
![image](https://github.com/user-attachments/assets/c8bd015d-6df8-4b87-b31d-fe1ed5d5e5de)

**Comment by Dehelaan** [comment]
![image](https://github.com/user-attachments/assets/4ec58f1f-e3a8-4148-8982-07896dc21036)
![image](https://github.com/user-attachments/assets/422e6f80-1bfc-4d47-aafc-375c05353030)
![image](https://github.com/user-attachments/assets/d683c63e-e9a0-4295-a1ea-4e56d8dc27e2)

**Comment by ummm288** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
