### ISSUE TITLE
[🕹️] Subscribed to youtube

### ISSUE THREAD

**Issue by TRIPLE-ADE** [mfts/papermark#1249]
### What side quest or challenge are you solving?

<img width="883" alt="Screenshot 2024-10-23 095643" src="https://github.com/user-attachments/assets/bc951176-d243-47d3-bbc9-420774069f25">

### Points

50

### Provide proof that you've completed the task

<img width="883" alt="Screenshot 2024-10-23 095643" src="https://github.com/user-attachments/assets/e3599ced-9f3e-41e0-8c34-261b6f024f18">

**Comment by Dehelaan** [comment]
![image](https://github.com/user-attachments/assets/e8177b45-1df1-4af4-b38b-780159cc6a2a)
