### ISSUE TITLE
[🕹️] Follow on Twitter

### ISSUE THREAD

**Issue by TRIPLE-ADE** [mfts/papermark#1250]
### What side quest or challenge are you solving?

![WhatsApp Image 2024-10-23 at 9 59 41 AM (1)](https://github.com/user-attachments/assets/a1f4c4d4-621f-48e5-b62d-e6c730f40918)

### Points

50

### Provide proof that you've completed the task

![WhatsApp Image 2024-10-23 at 9 59 41 AM (1)](https://github.com/user-attachments/assets/6219bac0-7732-4939-a693-99fc8c8abec0)

**Comment by aniruddhaadak80** [comment]
Before following --> 
![image](https://github.com/user-attachments/assets/de8bdf6b-c061-4547-b4e7-cd091400f65e)

After following -->
![image](https://github.com/user-attachments/assets/db9ed4a5-54cf-4644-ab45-5f1c273fec7d)


See followers ( from 1776 -> 1777 ) after following me .

**Comment by ummm288** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
