### ISSUE TITLE
[🕹️] Follow on Linkedin

### ISSUE THREAD

**Issue by TRIPLE-ADE** [mfts/papermark#1251]
### What side quest or challenge are you solving?

<img width="869" alt="Screenshot 2024-10-23 095806" src="https://github.com/user-attachments/assets/7e7b2bbf-fbf9-4e87-aac1-0f53ac8cb798">

### Points

50

### Provide proof that you've completed the task

<img width="869" alt="Screenshot 2024-10-23 095806" src="https://github.com/user-attachments/assets/1e8ae11f-e408-42d2-9bff-e5282b323f22">

**Comment by aniruddhaadak80** [comment]
![image](https://github.com/user-attachments/assets/d9cb5cad-ba1d-48de-867c-c096febc0407)

Done for #1251

**Comment by Dehelaan** [comment]
![Screenshot 2024-10-23 181827](https://github.com/user-attachments/assets/d9b24d04-1d51-4a33-a1b5-04a7d2500cb1)

**Comment by ummm288** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
