### ISSUE TITLE
[🕹️] completed 3 tasks

### ISSUE THREAD

**Issue by Dehelaan** [mfts/papermark#1253]
### What side quest or challenge are you solving?

Solved 3 side quests

### Points

150

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/4ec58f1f-e3a8-4148-8982-07896dc21036)
![image](https://github.com/user-attachments/assets/422e6f80-1bfc-4d47-aafc-375c05353030)
![image](https://github.com/user-attachments/assets/d683c63e-e9a0-4295-a1ea-4e56d8dc27e2)

**Comment by ummm288** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
