### ISSUE TITLE
[🕹️] Starry-eyed supporter 

### ISSUE THREAD

**Issue by PratikAwaik** [mfts/papermark#1255]
### What side quest or challenge are you solving?

Starry-eyed supporter

### Points

150

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/12c61bb8-cba7-4e5b-b484-a67b60de16c8)
![image](https://github.com/user-attachments/assets/d504c6ac-407e-46e5-b4e9-bd030a1829f8)
![image](https://github.com/user-attachments/assets/78417f53-2059-467e-8ecb-d32192ed9af8)
![image](https://github.com/user-attachments/assets/d916a297-7c05-4c91-bc42-c395b287e54b)
![image](https://github.com/user-attachments/assets/8b7b9b1c-7d73-410e-8426-c5d9040dc489)

**Comment by ummm288** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
