### ISSUE TITLE
Users can view the document even after archiving the link

### ISSUE THREAD

**Issue by vndpal** [mfts/papermark#126]
Scenario: After a customer generates a shareable link for a document and shares it with someone for viewing, they decide to "Archive" the link. Surprisingly, even after archiving, users with the link can still access the document.

Steps to Reproduce:

1. Create a document.
2. Generate a shareable link for the document.
3. Copy the link and open it in another browser/tab to view the document.
4. Access the document settings and choose "Archive" the link.
5. Return to the same link and open it again, you'll find that you can still view the document.

Expected Behavior: When attempting to open an archived link, it should display a "404 Page Not Found" error, similar to what you see when trying to access an expired document.

**Comment by mfts** [comment]
Thanks @RockingThor for the PR and thanks @vndpal for reviewing 😍

**Comment by mfts** [comment]
completed with #150
