### ISSUE TITLE
[🕹️]Add datarrom folder to other dataroom

### ISSUE THREAD

**Issue by AshishViradiya153** [mfts/papermark#1266]
### What side quest or challenge are you solving?

Add dataroom folder to other dataroom

 https://github.com/mfts/papermark/pull/1258#issuecomment-2434271760 => https://github.com/mfts/papermark/pull/1258#issuecomment-2434319832

### Points

@mfts

### Provide proof that you've completed the task

PR

**Comment by mfts** [comment]
/award 150

reward for PR
