### ISSUE TITLE
[🕹️] Potential Dataroom Link Creation Issues on Production

### ISSUE THREAD

**Issue by AshishViradiya153** [mfts/papermark#1275]
### What side quest or challenge are you solving?

@mfts @shnai0 I'm not 100% sure, but there's a 99.5% chance we have a dataroom link creation issue in production. I haven't checked thoroughly, so please look into it from your side as well. I'll keep you updated.

This is 2 day's old picture

![Screenshot 2024-10-23 211730](https://github.com/user-attachments/assets/1bfee07c-140a-41bf-9889-16606a5ec463)

![cants scroll](https://github.com/user-attachments/assets/ca7fb444-71fe-4580-a3f1-b0463e582b84)

### Points

@mfts ?

### Provide proof that you've completed the task

PR

**Comment by AshishViradiya153** [comment]
@mfts, I fought, what’s the bug and why is it happening!!!

**Comment by AshishViradiya153** [comment]
its beacuse of teamId!

**Comment by AshishViradiya153** [comment]
@mfts, may I help you in any way?

**Comment by mfts** [comment]
@AshishViradiya153 In prod it's working. Can you share what the issue is that you found. 

Super grateful for you looking deep

**Comment by mfts** [comment]
Ok i think i got it. Do you want to open a PR for it?

**Comment by AshishViradiya153** [comment]
yes i can , its because of link.teamId

**Comment by AshishViradiya153** [comment]
There are several places where errors are showing, such as the teamId not being included in the link or being removed. I will raise a PR for this. Do you have any details about the fix that I should be aware of? and yes I'll raise a PR for this.

**Comment by AshishViradiya153** [comment]
@mfts  Got it! It’s working if we remove teamId and create the link, but we are using link.teamId in many places, which is actually a big problem. I will update everywhere before tonight; it will take a maximum of 3-4 hours. I need some rest and dinner, and then I will start working on it. I will fix it before tonight. If that’s okay, please assign me to this issue. Thank you!

**Comment by AshishViradiya153** [comment]
@mfts okay assign  me i will make hotfix...

**Comment by AshishViradiya153** [comment]
Thank you.
