### ISSUE TITLE
Spam Protection: Ability to pause/resume email notifications

### ISSUE THREAD

**Issue by vndpal** [mfts/papermark#128]
Two contrasting use cases for notifications.

Use Case 1:
As a "Fitness Influencer," I shared a workout plan PDF with 10k followers via Papermark. 2k of them opened the link, resulting in 2k email notifications. This would spam my inbox. I need the ability to pause and resume these notifications.

Use Case 2:
As a "Startup CEO," I shared my pitch deck with 5 key investors. I want to receive notifications when they view it for timely follow-ups and assurance.

The ability to pause/resume the notifications would prevent spamming of inboxes.

**Comment by digant2482** [comment]
@vndpal Can I work on this issue ?

**Comment by vndpal** [comment]
I will work on this if/when it is go ahead by @mfts

**Comment by mfts** [comment]
Very good idea @vndpal. I've noticed that as well. 

Great idea 👍

**Comment by vndpal** [comment]
Thanks, Marc. Working on it and will submit a PR soon.

**Comment by vndpal** [comment]
PR merged and deployed. Hence closing the issue.
