### ISSUE TITLE
[🕹️] Add pitch deck (150 points) [Added]

### ISSUE THREAD

**Issue by Dkghuser** [mfts/papermark#1285]
### What side quest or challenge are you solving?

Add pitch deck (150 points) #1178

### Points

150 points for each deck. 
8 x 150 = 1200 points

### Description

I have added some (8) popular pitch decks to the issue, and updated the same in the drive link with the Excel file as well.

### Provide proof that you've completed the task

![Screenshot 2024-10-26 171847](https://github.com/user-attachments/assets/ca904622-9251-46e3-8601-0585e63ed93f)

![Screenshot 2024-10-26 170004](https://github.com/user-attachments/assets/f7ff4613-11e2-4a39-957c-d1a50ae440c7)

![image](https://github.com/user-attachments/assets/5d261de2-c3ba-419f-8f88-557f9a948d5d)

**Comment by Dkghuser** [comment]
> ### What side quest or challenge are you solving?
> Add pitch deck (150 points) #1178
> 
> ### Points
> 150 points for each deck. 8 x 150 = 1200 points
> 
> ### Description
> I have added some (8) popular pitch decks to the issue, and updated the same in the drive link with the Excel file as well.
> 
> ### Provide proof that you've completed the task
> ![Screenshot 2024-10-26 171847](https://private-user-images.githubusercontent.com/139794590/380420625-ca904622-9251-46e3-8601-0585e63ed93f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5NDQxNDEsIm5iZiI6MTcyOTk0Mzg0MSwicGF0aCI6Ii8xMzk3OTQ1OTAvMzgwNDIwNjI1LWNhOTA0NjIyLTkyNTEtNDZlMy04NjAxLTA1ODVlNjNlZDkzZi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNlQxMTU3MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYzQwOWMxMWQ4NDJlMzMyMmYyYWM0ZDc4NTY2NjQ4ZDBlZDg4MmNiZjRkNzUzZGFjOTAwZWJmZmExOWQ4NzQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.oVbkA0bb7fHsa0BzgErnLkK_gCLDxTl8U84_JSfufBI)
> 
> ![Screenshot 2024-10-26 170004](https://private-user-images.githubusercontent.com/139794590/380420641-f7ff4613-11e2-4a39-957c-d1a50ae440c7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5NDQxNDEsIm5iZiI6MTcyOTk0Mzg0MSwicGF0aCI6Ii8xMzk3OTQ1OTAvMzgwNDIwNjQxLWY3ZmY0NjEzLTExZTItNGEzOS05NTdjLWQxYTUwYWU0NDBjNy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNlQxMTU3MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MzFlZWY0NGQ5YWM1ZWExODYxMjcwNGM2ODM0Y2JkMmVjNGMxZGNiNTZlMTUzZTczOTJkNjY0NTEyMTQ3NTlhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.dDe7VqRZ5fQEA3E-EY2oqwiJdG5JlNj6-gIcuH1CwEM)
> 
> ![image](https://private-user-images.githubusercontent.com/139794590/380420755-5d261de2-c3ba-419f-8f88-557f9a948d5d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5NDQxNDEsIm5iZiI6MTcyOTk0Mzg0MSwicGF0aCI6Ii8xMzk3OTQ1OTAvMzgwNDIwNzU1LTVkMjYxZGUyLWMzYmEtNDE5Zi04Zjg4LTU1N2Y5YTk0OGQ1ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNlQxMTU3MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMzNmZmI4NjAwOTI0YjZmOWM0NmY5Y2U5NzVmOWVmNGQwZmUwYWVlZGQ3Zjc2N2Y4NjA5NjQ0YzY5YzIwN2E0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.G9f-bjGZMOlC-dL1IGsMKeoiJ-ShFXOZJPbVngfiRWw)

Hello @mfts  and  @shnai0  ,
I have completed the side quest/issue and submitted the same at #1285 , with the proof as required.
Thank You.

**Comment by mfts** [comment]
award 450 points already in separate issues. that's the current max. thanks for the participation
