### ISSUE TITLE
[🕹️] Follow Papermark LinkedIn Page (50 Points)  (Followed)

### ISSUE THREAD

**Issue by Dkghuser** [mfts/papermark#1289]
### What side quest or challenge are you solving?

Follow [Papermark LinkedIn](https://linkedin.com/company/papermarkio) Page (50 Points): 

### Points

50 points

### Description

Followed [Papermark LinkedIn](https://linkedin.com/company/papermarkio) Page

### Provide proof that you've completed the task

Deepak K

![image](https://github.com/user-attachments/assets/3bc7bea0-f254-4fe9-b63d-86d89552a779)

**Comment by priyanshuverma-dev** [comment]
I have followed 
![image](https://github.com/user-attachments/assets/c49e5d27-a88e-477a-8b1b-c0c7bb09c5c6)
