### ISSUE TITLE
[🕹️]Design new Papermark logo

### ISSUE THREAD

**Issue by arg387** [mfts/papermark#1297]
### What side quest or challenge are you solving?

I have designed a new logo for papermark.

### Points

150

### Provide proof that you've completed the task

![papermark_logo_1](https://github.com/user-attachments/assets/aaf369ee-6707-488f-bf8d-0fb3727e51a8)

**Comment by Anshsahu0802** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)
