### ISSUE TITLE
[🕹️] 

### ISSUE THREAD

**Issue by prachhii31** [mfts/papermark#1321]
### What side quest or challenge are you solving?

starred

### Points

150

### Description

I have share the information about non contribution to my friends and they have starred this repository...

### Provide proof that you've completed the task

![Screenshot 2024-10-28 125442](https://github.com/user-attachments/assets/44d9a47d-56ae-4639-95ef-d9e6c07b7822)
![Screenshot 2024-10-28 125948](https://github.com/user-attachments/assets/4e2d2b10-e8ad-4e5f-a17a-2401b6948010)
![Screenshot 2024-10-28 130048](https://github.com/user-attachments/assets/acc7054f-4c3a-460d-9e55-aba7bdd40986)

**Comment by mfts** [comment]
sorry, that's only three accounts and two of three are your own
