### ISSUE TITLE
[🕹️] Add a Pitch Deck to the Gallery

### ISSUE THREAD

**Issue by Atharva-3000** [mfts/papermark#1338]
### What side quest or challenge are you solving?

Uploaded a pitch deck to papermark, and made a public link.

### Points

150-450

### Description

Uploaded a publicly available PitchDeck to Papermark with Public Link with a Product called as **zkAuth** which integrates Web3 with Suthentication.zkAuth that

### Here is the Link:
https://www.papermark.io/view/cm2typyzy000113mcpda4qe83

**Comment by mfts** [comment]
@Atharva-3000 please add this this spreadsheet 

https://docs.google.com/spreadsheets/d/1Wogxs1y3gE9MEt8Qu56PXOKBL4pgJX_s8NORyaai9Xg/edit?pli=1&gid=0#gid=0

**Comment by Atharva-3000** [comment]
Done @mfts, thanks

**Comment by mfts** [comment]
Thanks. 

/award 450
