### ISSUE TITLE
[🕹️]Add A Pitch Deck to the Gallery

### ISSUE THREAD

**Issue by Atharva-3000** [mfts/papermark#1341]
### What side quest or challenge are you solving?

Uploading a pitch deck to the papermark.

### Points

150-450

### Description

Added the pitch deck for **BuzzFeed**
### Stats
- Industry:📺 Media
- Amount Raised:$3.5M
- Year:2008
- Stage:Series-A

### Link
https://www.papermark.io/view/cm2u5xtyg000183zlzmdvc9zj
<br>
### Preview
Remember it is from 2008
![image](https://github.com/user-attachments/assets/cd8a75b7-b092-40e8-9658-420e3fc2d969)

**Comment by mfts** [comment]
@Atharva-3000 please add it to this spreadsheet 

https://docs.google.com/spreadsheets/d/1Wogxs1y3gE9MEt8Qu56PXOKBL4pgJX_s8NORyaai9Xg/edit?pli=1&gid=0#gid=0

**Comment by Atharva-3000** [comment]
@mfts Done 🫡

**Comment by Atharva-3000** [comment]
Thanks a ton 🙇🏼‍♂️
