### ISSUE TITLE
[🕹️] Starry-eyed Supporter (150 Points)

### ISSUE THREAD

**Issue by Subash-Lamichhane** [mfts/papermark#1352]
### What side quest or challenge are you solving?

Starry-eyed Supporter

### Points

150 Points

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/d9c5307b-5cd2-4ca6-80bd-7206a27a80cf)
![image](https://github.com/user-attachments/assets/86665836-4996-4686-ba34-6a396bc77a9e)
![image](https://github.com/user-attachments/assets/375da634-7dde-42ec-b7ba-50ca4a2a9b7f)
![image](https://github.com/user-attachments/assets/c334c476-55b6-4cfe-90ca-bf99659d6192)
![image](https://github.com/user-attachments/assets/ffdfdc01-f18e-43b6-8bf4-f54513a43638)

**Comment by Shrinivasdumbali** [comment]
![1](https://github.com/user-attachments/assets/d340501c-cfbf-4cb6-af7e-00f9641a1037)
![2](https://github.com/user-attachments/assets/e2fb6795-1777-4ade-8771-f76ad3e40234)
![3](https://github.com/user-attachments/assets/9ecce4f2-c0a5-42d9-85ea-faee1f9ee358)
![4](https://github.com/user-attachments/assets/f1586279-b634-4067-bd08-e7fc45842cb5)
![5](https://github.com/user-attachments/assets/cc60f4a0-e1a5-47af-b6f2-f6069ae24e97)
