### ISSUE TITLE
[🕹️]Starry-eyed Supporter (150 Points)

### ISSUE THREAD

**Issue by sumit2011** [mfts/papermark#1357]
### What side quest or challenge are you solving?

star

### Points

150 Points

### Description

stared the papermark repo

### Provide proof that you've completed the task

![1](https://github.com/user-attachments/assets/16b3ba6c-505e-424b-a89e-727b1a7ea0f3)
![2](https://github.com/user-attachments/assets/cb8316f9-6892-4f06-ad2e-d02e516738b2)
![3](https://github.com/user-attachments/assets/59f584a3-2bc1-4243-9d63-c115da9eae6a)
![4](https://github.com/user-attachments/assets/04710706-b70c-4a77-858b-962e6108b525)
![5](https://github.com/user-attachments/assets/0cf7e28c-4fa8-4f06-8831-a433d92610b1)

**Comment by Shrinivasdumbali** [comment]
![1](https://github.com/user-attachments/assets/b9405a0d-8152-4ff4-9a9d-a2fb02c29763)
![2](https://github.com/user-attachments/assets/1584109b-7b16-4ce7-8c80-e14c63a5036a)
![3](https://github.com/user-attachments/assets/479bebdb-0ab9-4e39-9d61-b4cc8dcf8340)
![4](https://github.com/user-attachments/assets/2db2975e-3675-4947-a5c8-858bc0e5590c)
![5](https://github.com/user-attachments/assets/71a1032d-6366-4f2e-8821-f00271950a56)

5 friends to star the repos!
