### ISSUE TITLE
[🕹️] Pitch decks

### ISSUE THREAD

**Issue by DeepaPrasanna** [mfts/papermark#1367]
### What side quest or challenge are you solving?

Added 20 pitch decks but awarded only for 3

### Points

2550

### Description

As each pitch deck is 150 to 450 points, considering atleast 150 for 20 pitch decks will be 3000

### Provide proof that you've completed the task

https://github.com/mfts/papermark/issues/1365

**Comment by mfts** [comment]
@DeepaPrasanna 

> Each deck is 150 points, max 450 points

https://github.com/mfts/papermark/issues/1178
