### ISSUE TITLE
GAuth problem stuck on login screen

### ISSUE THREAD

**Issue by serhatcalik** [mfts/papermark#137]
When I start the app everything is fine even logs are okay but when I try to login it's sending me back to login screen after google, 
I'm using docker container to start this app, and using Psql from docker container. I tried to check logs from app aswell but I couldn't see any error. I checked with google chrome developer tool, I'm getting JWT token from server aswell but I can't login. Could you help me about that ?

**Comment by vndpal** [comment]
I tried to replicate the issue locally.

If you are running the application locally without any value to  `NEXTAUTH_SECRET` key in the `.env` file, you will face login errors and when you put some value `NEXTAUTH_SECRET` you will be able to login but after login, the application will redirect you to back to login screen.

If you look at your console where you are running the application you will see some error like this `"ikm" must be at least one byte in length'`.

To fix this you can follow these steps.

1. Stop the application.
2. Add a value to the `NEXTAUTH_SECRET` variable in the `.env` file (if it is not already there).
3. Start the application again by running `npm run dev`

After following these steps, the issue was resolved and the application started functioning properly. I recommend giving it a try and confirming whether it fixes the issue for you as well.

**Comment by serhatcalik** [comment]
NEXTAUTH_SECRET=“SECRET”
NEXTAUTH_URL=“URL”
# These variables are from Vercel Storage Postgres
POSTGRES_PRISMA_URL=“PSQL_URL”
POSTGRES_PRISMA_URL_NON_POOLING="PSQL_URL"
# This variable is from Vercel Storage Blob
BLOB_READ_WRITE_TOKEN=

# Google client id and secret for authentication
GOOGLE_CLIENT_ID=“GOOGLECLIENT”
GOOGLE_CLIENT_SECRET=“GOOGLESECRET”

NEXT_PUBLIC_BASE_URL="URL"

My .env file like this. I put dummy data in it, my .env file has secrets.
Do you see any issue on it ?

**Comment by vndpal** [comment]
Assuming you have all the correct values in your `.env` file, you can stop the application and then run again, it should resolve the issue. This resolved the issue for me when I reproduced locally :)

If you're still facing the same problem, I suggest checking for any error messages in your console/command prompt where your are running the `npm run dev` command. The error message will provide you the information to the troubleshooting the issue.

**Comment by serhatcalik** [comment]
I'm already running with npm run dev but it's not working, it's not creating any errors 
✓ Ready in 2.5s
 ✓ Compiled /middleware in 201ms (159 modules)
 ○ Compiling /not-found ...
 ✓ Compiled /not-found in 4.3s (713 modules)
 ⚠ Fast Refresh had to perform a full reload. Read more: https://nextjs.org/docs/messages/fast-refresh-reload
 ✓ Compiled /login in 510ms (771 modules)
 ⚠ Fast Refresh had to perform a full reload. Read more: https://nextjs.org/docs/messages/fast-refresh-reload
 ✓ Compiled /api/auth/[...nextauth] in 253ms (368 modules)
 
 This is the log which literally says nothing. 
 We are using domain with SSL, did anyone try it with domain ?

**Comment by Aashish-Upadhyay-101** [comment]
@serhatcalik I would like you to try these: 
- Make sure that all environment variables, including NEXTAUTH_URL, match the domain and protocol (http or https) you're using. This should be the full URL of your site, and it's especially important when using third-party login providers.
- could you look at the browser's network tab and look for any requests that might be failing or any redirects that shouldn't be happening?
- Ensure your Prisma configuration is correct, and that your database is reachable and operating normally
- Test in an incognito window or a different browser

**Comment by serhatcalik** [comment]
Google sends a 302 to DOMAIN/login with JWT token but stays on login screen.

**Comment by Aashish-Upadhyay-101** [comment]
cc @mfts

**Comment by deeliciouscode** [comment]
I'm facing the same issue. No error in the console, nothing.

**Comment by digant2482** [comment]
@serhatcalik is your google redirect URL http://localhost:3000/api/auth/callback/google (Replace your port with 3000), wrong redirect URL won't allow you to login sometimes. Also try to regenerate GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET.

**Comment by serhatcalik** [comment]
My google redirect url is HTTPS://domain/api/auth/callback/google, which is right and google clientid and client secret is true aswell, I'm even getting JWT token from server but staying on login :(

**Comment by mfts** [comment]
This was related to a timeout of the serverless function. It's since been resolved. If the issue reappears, please open this issue again.
