### ISSUE TITLE
Custom Logo

### ISSUE THREAD

**Issue by vndpal** [mfts/papermark#145]
Following Papermark's goal of providing a fully customized document viewing experience (#73), we want to give document uploaders the ability to add their own logo. This logo will be visible when users view the document, ensuring a higher level of personalization. It will create a truly unique and engaging user experience.

Just like custom domains, our users will be able to replace the default Papermark logo with their own logo.

**Comment by vndpal** [comment]
Since we are already utilizing Vercel Blob for our document uploads, we can re-use the same Vercel Bloc for logo uploads. We will create a new table to store the logo URL and logo metadata. This new table will also have a relationship with the Link table.

@mfts If this approach sounds good to you then I can start working on it.

**Comment by mfts** [comment]
Fantastic! Thanks @vndpal yes let's use vercel/blob

**Comment by mfts** [comment]
closed with #257
