### ISSUE TITLE
It is not clear for beginners to replicate the production environment locally. Can improve the documentation of it! 

### ISSUE THREAD

**Issue by aryan-139** [mfts/papermark#15]
I am writing to provide feedback and request an improvement in the documentation of the Papermark project regarding the process of replicating the production environment locally.

As a beginner trying to set up and run Papermark on my local machine, I encountered some difficulties in following the existing documentation. The steps provided were not detailed enough, assuming prior knowledge that may not be possessed by all users.

To ensure a smoother onboarding experience for new contributors, I feel that I can chip in and make the documentation more concise and easy to consume. 

Here's how I plan to achieve it:

Provide Clearer Cloning Instructions: The documentation should include explicit instructions on how to clone the Papermark repository from GitHub, including the use of version control tools such as Git.

Elaborate on Dependency Installation: The instructions should provide additional information about Node.js and how to install it if not already present on the user's machine. Additionally, a clear explanation of the dependencies required by Papermark and how to install them using npm should be included.

Enhance Database Configuration Steps: The process of configuring the database should be more explicit, including details on setting up SQLite and specifying the necessary path for the database file.

Provide Step-by-Step Migration Instructions: The documentation should include step-by-step instructions on how to run the required database migrations, ensuring that users understand how to set up the database schema correctly.

Clarify Application Startup Process: Clear and concise instructions on how to start the Papermark application locally should be provided, including the specific command to use and the expected URL for accessing the application.

By making these improvements, the documentation will become more accessible to beginners, enabling them to replicate the production environment of Papermark on their local machines more effectively.

Looking forward to working on this issue!

**Comment by mfts** [comment]
Hey @aryan-139 thanks for bringing this to my attention. The README was definitely rushed and there are some good points in your issue that we should definitely add to the README/doc. 

- install instructions
- migrating schema to local db

The hardest will be recreating the file upload locally (see #6). 

Feel free to open a PR with some suggestions.

**Comment by mfts** [comment]
Updated Readme with #22
