### ISSUE TITLE
Need help with Prisma issue.

### ISSUE THREAD

**Issue by yashsharma999** [mfts/papermark#163]
## Description
Getting the 500 Internal server error when accessing `/documents` endpoint.

Getting the following error message
```js
{
    "message": "Internal Server Error",
    "error": "\nInvalid `prisma.team.findUnique()` invocation:\n\n\nThe table `public.Team` does not exist in the current database."
}
```

## 
Not sure what I should do, although I can see the Prisma schema has updated and tried `npx prisma generate`, but this doesn't resolve the issue.

**Comment by digant2482** [comment]
Pull the latest prisma schema from github.
Reset your postgres database
Sign up again
It should work

**Comment by yashsharma999** [comment]
Somehow, my migration files were not in sync even after doing `git pull` 🤔

- ensured that they are same as in the origin.
- ran `npx prisma migrate dev` 
- this solved the issue
