### ISSUE TITLE
Not able to re-upload document if the document upload fails in case of any error.

### ISSUE THREAD

**Issue by crediblebilal** [mfts/papermark#186]
### Descpription

When a user selects a new document and clicks **Upload Document**. If this upload fails, the button still keeps in the **Uploading...** state without showing any message to the user. If the user closes the upload dialog and re-tries to upload a new document, the upload dialog and the button are still in the earlier **Uploading...** state, preventing user from re-trying in case of any error.

#### Screenshot:

![image](https://github.com/mfts/papermark/assets/55330484/b7f82801-3f3c-4063-be4e-ce0b5f3922ee)

### Proposed solution:

- In case of any errors in uploading the document, show some relevant error message to the user.
- Allow user to retry / re-upload the document.

**Comment by crediblebilal** [comment]
Team! if this is approved, I am willing to work on this issue.

**Comment by mfts** [comment]
@crediblebilal Thanks for the report, Bilal. I've heard about this issue before. Thank you for volunteering to work on this issue. 🚀

Let us know if you need any support 💪
