### ISSUE TITLE
disable links while document is being processed

### ISSUE THREAD

**Issue by ashiqYousuf** [mfts/papermark#193]
Hi there, I uploaded few documents (pdf format) and reproduced an application Error issue a lot of times.

After uploading the document, I'm getting the shareable pdf link , fine. Now when i paste the link and enter email then we land into the next page with forward and backward icons (for visiting next or prev pages). 

But i have seen something very unusual, after giving my email id, then if i quickly hit the next next next..... icon , the following error gets generated.

Initial Page after entering email
![Screenshot from 2023-12-06 15-01-48](https://github.com/mfts/papermark/assets/91784076/afc37c81-636a-45b7-84fe-b2e97a8c9a70)

Actual Error
![Screenshot from 2023-12-06 15-01-26](https://github.com/mfts/papermark/assets/91784076/5348b974-239e-4ccd-ba19-4adf939b4161)

in the network tab you can see , pages key as NULL, in that case only im able to get this Error.

in following case, 
![image](https://github.com/mfts/papermark/assets/91784076/43b3ef0a-ddff-477a-9a5e-0fb6eecf1156)
I do not get any errors.

If this is really some issue that needs consideration from your side, then i'll be available to work on this.

**Comment by RockingThor** [comment]
I would love to work on this issue. Can I get this issue assigned to me?

**Comment by mfts** [comment]
@ashiqYousuf thabks for reporting. When you upload a pdf, a background task gets triggered that generates images for each page. 

I think you may have accessed the link before the pages were processed. 

In any case the UX should be improved and any errors properly handled. 

Can you confirm that you accessed the link before the doc finished processing the pages? That would help debug the issue somewhat :)
