### ISSUE TITLE
Bland 404 error page

### ISSUE THREAD

**Issue by tsikatawill** [mfts/papermark#2]
The error page is quite bland and doesn't have a link to redirect users to the homepage.

![image](https://github.com/mfts/papermark/assets/48873308/035325b6-6383-4e30-882a-c33d1ebe78c6)

Would be great to have a dedicated 404 error page.

Thanks.

**Comment by dephraiim** [comment]
@tsikatawill Are you working on this?

**Comment by mfts** [comment]
@tsikatawill @dephraiim I don't have any specific design in mind for this. Feel free to suggest something :)

**Comment by tsikatawill** [comment]
> @tsikatawill Are you working on this?

I am now

**Comment by tsikatawill** [comment]
> @tsikatawill @dephraiim I don't have any specific design in mind for this. Feel free to suggest something :)

Sure. Let me get to it then.
