### ISSUE TITLE
[🪲 Bug]: Add a validation on Notion page link implementation

### ISSUE THREAD

**Issue by ashrafchowdury** [mfts/papermark#201]
## Description
Currently, **to add a new document through the Notion page, we can add any text on the input field to create a page link,** it's not a good practice we have to add a validation to check if it's a valid URL or not.

## Steps to Reproduce

1. We have to implement a condition to check if it's a valid URL or not.
2. If the URL is invalid, we have to throw an error message; otherwise, they can create a page link.

## Bug Preview

https://github.com/mfts/papermark/assets/87828904/507cfb8c-1278-40fd-bd7e-b45c2adf05a4

## Would you like to work on this issue?

 **Yes, I would like to work on this issue, if all sounds good.**

**Comment by ManishBisht777** [comment]
i would like to work on this issue :)

**Comment by mfts** [comment]
@ashrafchowdury thanks for bringing that ip. There is a validation method as part of the react-notion-utils package. Perhaps you can make use of that. 

Thanks for offering to work on it. I've assigned the task to you
