### ISSUE TITLE
Auth UI: Show a loading state when logging in / signing up via email address

### ISSUE THREAD

**Issue by andrewheekin** [mfts/papermark#206]
It would be a nice UI improvement to show a loading spinner when a user enters an email address and clicks "Continue with email". As a note, there's currently a ~5s delay before the "Email sent - check your inbox!" toast notification displays
<img width="1312" alt="Screenshot 2023-12-12 at 2 46 52 PM" src="https://github.com/mfts/papermark/assets/4684591/001c8a3c-77e8-4996-a3ed-be7c99f27e85">

**Comment by Aashish-Upadhyay-101** [comment]
I will work on this
