### ISSUE TITLE
Auth UI: Show a loading state for Google OAuth and LinkedIn OAuth

### ISSUE THREAD

**Issue by andrewheekin** [mfts/papermark#207]
Similar to #206 , it would be a nice small UI improvement to show a loading spinner when a user clicks "Continue with Google" or "Continue with LinkedIn"
<img width="1312" alt="Screenshot 2023-12-12 at 2 46 52 PM" src="https://github.com/mfts/papermark/assets/4684591/76e45c89-647b-4053-88ba-9fb126684425">

**Comment by Aashish-Upadhyay-101** [comment]
and this one too, I will fix this !
