### ISSUE TITLE
Dashboard UI: Add a loading skeleton as Sidebar.tsx renders

### ISSUE THREAD

**Issue by andrewheekin** [mfts/papermark#208]
It would be a nice UI improvement to replace the loading spinner with a loading skeleton as Sidebar.tsx renders on the page
<img width="1724" alt="Screenshot 2023-12-12 at 2 53 13 PM" src="https://github.com/mfts/papermark/assets/4684591/b9901e20-36ad-496e-afc1-143aa6c2b06b">

**Comment by Aashish-Upadhyay-101** [comment]
I would like to take this @mfts  :)
