### ISSUE TITLE
[✨ Feature]:  Custom Name for Notion page link

### ISSUE THREAD

**Issue by ashrafchowdury** [mfts/papermark#212]
## Description
Currently, when adding a Notion page link, the default name displayed is "Notion Link". This lack of customization makes it difficult to quickly identify and navigate between linked pages, especially in documents with numerous links.

## Proposed Solution:
1. Allow users to specify their own name for each Notion link. This could be done through an input field which we have to insert before the Notion page link input field.
2. In the detailed document page we have to add an edit Icon next to the Notion page name for better user experience.

## Example 
![image](https://github.com/mfts/papermark/assets/87828904/dcd347bb-5ea2-4490-9fb0-9106e621c2d8)

We have to add an edit Icon next to the Notion page name for better user experience.

![image](https://github.com/mfts/papermark/assets/87828904/d913c69d-c5cd-4c6e-b4c7-eb3b685b10c6)

**It is also included in your to-do list.**

![image](https://github.com/mfts/papermark/assets/87828904/a568df81-ad88-42fc-8b8f-e0746bc81537)

## Would you like to work on this issue?

**Yes**

**Comment by ashrafchowdury** [comment]
**I would like to work on this issue if all sounds good.**  🙌💖

**Comment by mfts** [comment]
I thought it would be cool to take the existing name of the notion link instead of adding another input field. What do you think?

**Comment by ashrafchowdury** [comment]
> I thought it would be cool to take the existing name of the notion link instead of adding another input field. What do you think?

Well, it sounds excellent. I never thought like that before. We can do that easily. 🙌
