### ISSUE TITLE
[🐛 Bug]: Document upload model state is not cleared when the model is closed.

### ISSUE THREAD

**Issue by ashrafchowdury** [mfts/papermark#217]
## Description

When a user closes the document upload model, **the selected document is not get cleared**. Users have to refresh the page manually to add a new document. 

## Steps to Reproduce

1. When the user closes the model the state that contains the document has to be get cleared.
2. The first method also applies to the Notion page add model.

## Bug Preview

https://github.com/mfts/papermark/assets/87828904/bf7e8978-bd14-4cbf-8159-173e9b60bcb6

## Would you like to work on this issue?

**Yes**

**Comment by Aashish-Upadhyay-101** [comment]
hey @ashrafchowdury you can work on this issue if you want to : ) 
otherwise I am happy to take on this 😀

**Comment by ashrafchowdury** [comment]
I would like to work on this issue @Aashish-Upadhyay-101, I appreciate your engagement. :)
