### ISSUE TITLE
🐛 Bug: The preview site crashes when a private Notion page link gets added

### ISSUE THREAD

**Issue by ashrafchowdury** [mfts/papermark#221]
## Description
**When a user adds a private Notion page link, the preview site crashes**. This issue is specific to private Notion links and does not occur with public links.

## Steps to Reproduce
1. While adding the link, we need to check if the Notion page link is private or public. If it's private, we will send an error message, otherwise, we will add the page link.

 ## Bug Preview

https://github.com/mfts/papermark/assets/87828904/b1976c2e-e256-4321-bd01-5f4c346b24c9

## Would you like to work on this issue?

**Yes, I would like to work on this issue**

**Comment by mfts** [comment]
Yes that's indeed a known error. It would be great to detect if the notion is private/public when uploading already

**Comment by ashrafchowdury** [comment]
Hay @mfts, assign me to this issue to start working on it :)
