### ISSUE TITLE
♻️ Refactor Sidebar Component for Improved User Experience

### ISSUE THREAD

**Issue by ashrafchowdury** [mfts/papermark#222]
## Description

For a better user experience and interaction on smaller screens, replace the headlessui sidebar with the shadcn sidebar. For bigger screens, a dedicated sidebar should be created.

The sidebar code is now difficult to read and update. To make it more understandable, we need to create various components to store different sections of the sidebar.

Note: These changes will not affect user experience.

## Request Changes

1. Replace the headlessui sidebar with the shadcn sidebar to improve the user experience on a smaller screen.
2. For bigger screens we will add a fixed sidebar.
3. Create a component to keep the sidebar code to use different areas.
4. Break down the sidebar into distinct, reusable components for better organization and maintainability.

## Screenshots

https://github.com/mfts/papermark/assets/87828904/a9b59ebc-4c8c-4880-82f3-f49a10f09edf

## Would you like to work on this issue?

**Yes, I would like to work on this issue.**

**Comment by Gourav-21** [comment]
hey, I would like to work on this issue but as new to open source i need a little bit of guidance

should i divide the the into 3 components like sidebar which will have desktop sidebar and mobile sidebar or should i divide it into more smaller components like header of mobile and navigation buttons of sidebar?

**Comment by ashrafchowdury** [comment]
Hay @Gourav-21, we appreciate your contribution but this issue has been resolved the by latest UI update. That's why I'm closing this issue here.
