### ISSUE TITLE
Feature: Expand File Format Support to PPT/PPTX, DOC/DOCX

### ISSUE THREAD

**Issue by ashrafchowdury** [mfts/papermark#231]
## Description
Currently, the document only accommodates PDF and Notion page formats. To enhance its functionality and versatility, you proposed integrating support for additional file formats:

1. PPT/PPTX
2. DOC/DOCX

It's the best time to work on this feature as it's part of the roadmap. https://github.com/mfts/papermark/issues/71

### Benefits:

* Enhanced User Experience: By accommodating a broader range of file types, users will enjoy greater flexibility and convenience in their interactions with the application.
* Expanded Use Cases: The application will become suitable for a wider range of tasks and projects, attracting a broader audience and fostering increased adoption.

**Comment by ashrafchowdury** [comment]
**I would like to work on this feature if all sounds good. :)**

Additionally, you can share your opinion and requirements if you have to. ;)

**Comment by mfts** [comment]
Yes that's definitely a good point. A few things to consider: we need to keep the page-by-page analytics even for new file types. 

Have you thought about any ways to convert docx/pptx to images (or individual pages)? 

I was researching this a while ago and there are a couple of ways but curious to see what you / and the community think.

**Comment by ashrafchowdury** [comment]
Converting docx/pptx to an image can be expensive, although we can do that. 

What if we use a library to view these files instead of converting them into images?

**Comment by mfts** [comment]
As long as we can get the individual document pages from the library, so that we cab track the analytics on each page,  sure :)

**Comment by ashrafchowdury** [comment]
I would like to try both options to see which one performs better and will raise a PR according to it. For sure.

**Comment by mfts** [comment]
closed by #598
