### ISSUE TITLE
ui: remove scrollbar

### ISSUE THREAD

**Issue by priyankarpal** [mfts/papermark#232]
There is a scroll bar at the bottom which creates a bad user experience. It would be great if we could remove it.

https://github.com/mfts/papermark/assets/88102392/8a4ac697-3db2-444a-9ba6-f08405a0fefc

**Comment by Aashish-Upadhyay-101** [comment]
same here, I could see this glitch in mine 
cc @mfts

**Comment by Aashish-Upadhyay-101** [comment]
which browser are you using? @priyankarpal

**Comment by mfts** [comment]
Uff that's disgusting UX. Y'all are right. 

We need to truncate the email.

**Comment by Aashish-Upadhyay-101** [comment]
I will do it!

**Comment by Aashish-Upadhyay-101** [comment]
I will do it!

**Comment by priyankarpal** [comment]
> which browser are you using? @priyankarpal

Brave

**Comment by priyankarpal** [comment]
> I will do it!

sure

**Comment by ashrafchowdury** [comment]
@mfts, this issue has been resolved, you can now go ahead and close this issue.
