### ISSUE TITLE
bug: switch theme button creating issue

### ISSUE THREAD

**Issue by priyankarpal** [mfts/papermark#233]
if you notice the switch theme button's position differs from the actual one. I suggest adding a switch button to the top or bottom left. What do you think?

https://github.com/mfts/papermark/assets/88102392/f7a8eb2a-001c-46f3-8079-29478fa8072e

**Comment by Aashish-Upadhyay-101** [comment]
@priyankarpal Strange, but I couldn't see that glitch in mine ! 
cc @mfts

**Comment by sourabpramanik** [comment]
@mfts can you please assign me this issue if @priyankarpal is not working on this?

**Comment by priyankarpal** [comment]
> @mfts can you please assign me this issue if @priyankarpal is not working on this?

yup you can work on this issue

**Comment by ashrafchowdury** [comment]
**Hay @priyankarpal, this issue has been resolved by the latest UI update. You can now go ahead and close this issue.**
