### ISSUE TITLE
chore: remove all `console.log`

### ISSUE THREAD

**Issue by priyankarpal** [mfts/papermark#234]
When you open the developer console by clicking on the green chart, you will see several `console.log` statements. This is not a good practice.

![Screenshot from 2024-01-05 10-39-03](https://github.com/mfts/papermark/assets/88102392/2604f3f2-525a-49e5-87b5-da1e2e419d54)

https://github.com/mfts/papermark/assets/88102392/1c5fa8de-e8cf-4d83-99c5-b8a21c2e307a

## code example

https://github.com/mfts/papermark/blob/d08088b4a55cf5bce96b0a8df920af95ba7b9b1d/components/charts/bar-chart.tsx#L162

**Comment by Aashish-Upadhyay-101** [comment]
@mfts, I will do this ASAP !

**Comment by ShashwatPS** [comment]
Can I work on this and make a new PR ?

**Comment by priyankarpal** [comment]
> Can I work on this and make a new PR ?

someone already raised the PR :)
