### ISSUE TITLE
bug: still showing disable Assistant option after successfully disabling the AI Assistant

### ISSUE THREAD

**Issue by priyankarpal** [mfts/papermark#235]
1. go to your documents page
2. click on AI Assistant & after clicking it will be activated
3. if you click the three dots icon sometimes still it will show the `Activate Assistant` option 
4. after refreshing the page it will show the `Disable Assistant` option
5. when you disable the AI assistant, the same things happen.

https://github.com/mfts/papermark/assets/88102392/bc8145b7-b898-4e6a-ae18-fd75fe356895

**Comment by Aashish-Upadhyay-101** [comment]
Fix for this is ready !
cc @mfts
