### ISSUE TITLE
Not able to view the PNG files of around 170 Kb . 

### ISSUE THREAD

**Issue by guptalife** [mfts/papermark#24]
I am facing this issue. is this a bug or something temporary.

**Comment by mfts** [comment]
Would you mind sharing a view link to png in papermark, then I can look into your issue.

**Comment by guptalife** [comment]
https://www.papermark.io/view/cljmtk7tn0002mj08c39r2pof. 

check this

**Comment by HunnySajid** [comment]
This happened to me too. 
The react-pdf package does not work with images. I did not try with a .docx file but images (png, jpeg) are not rendered in dom with this package.
I think we need to save the file type as well in our document entity while uploading the file.
Right now we can split the `name` attribute to get file type and conditionally render the image file within <img /> tag to fix this bug.
I am not sure how the analytics part would work there though OR we can restrict to accept only `.docs/pdf` for now while uploading.

**Comment by mfts** [comment]
@HunnySajid yes, react-pdf can only render pdf. It's an not ideal long-term solution. 

The `view/[id]` page has logic that renders the respective component for a given file extension. image extension will not use the react-pdf, instead like you realized it will just be an `img` on the DOM. 

Ideally, I'd love to convert all documents to images per page and then serve the pages. It's much more versatile than dealing with all the file extensions.

**Comment by mfts** [comment]
Limited the file type to `.pdf` among other features and fixes in #36
