### ISSUE TITLE
feat: add navigation from login to register page and from register to login page

### ISSUE THREAD

**Issue by sourabpramanik** [mfts/papermark#240]
At this moment we don't have any button or link on the login or register page to route from one to another. 

 I think we should add a new button or link at the bottom of the auth block to make the both the routes accessible.
 
@mfts  Need your input for this.

**Comment by ashrafchowdury** [comment]
Hay @sourabpramanik, 

I don't believe we need to include a registration link on the login page. **The login page can both register new users and login to existing accounts.**

**Comment by sourabpramanik** [comment]
Yes I found that it work both ways after spending bit more time on it. Forgot to close this
