### ISSUE TITLE
🪄 Enhance: improve the Dialog model UI

### ISSUE THREAD

**Issue by ashrafchowdury** [mfts/papermark#242]
## Description

The current UI of the `add-domain` & `add-team` models does not look good enough, we can improve the UI just by adding a few lines of styles.

## Example

**Before**

![Group 119](https://github.com/mfts/papermark/assets/87828904/c9af2ec7-d9ad-488e-b863-eacb53cdf809)

**After**

![Group 120](https://github.com/mfts/papermark/assets/87828904/d02ce38e-530f-4e04-9cfb-1a598c08c09f)

**Comment by ashrafchowdury** [comment]
### I would like to raise a PR if it sounds good. :)

**Comment by mfts** [comment]
Sounds great!

**Comment by ashrafchowdury** [comment]
> Sounds great!

Perfect, I'm raising a PR 🥰
