### ISSUE TITLE
Make links inside PDFs and documents clickable when viewing with Papermark

### ISSUE THREAD

**Issue by mfts** [mfts/papermark#253]

**Comment by Aashish-Upadhyay-101** [comment]
I would like to do this! @mfts

**Comment by mfts** [comment]
That would be awesome. There's a function in `mupdf` that parses the content and makes it available 

https://mupdf.readthedocs.io/en/latest/mupdf-js.html#getLinks

**Comment by Aashish-Upadhyay-101** [comment]
@mfts, After I extracted all the links, how should I put it on top of the PageViewer?

**Comment by mfts** [comment]
I'll leave the visual up to you. Just make it usable for yourself :)

**Comment by Aashish-Upadhyay-101** [comment]
okay, I will raise PR very soon.
