### ISSUE TITLE
Replace @headlessui/react with all shadcn/ui library components for better efficiency

### ISSUE THREAD

**Issue by ashrafchowdury** [mfts/papermark#259]
## Description

Currently, papermark project utilizes the `@headlessui/react` library for Dropdown and Disclosure components across various UI elements. However, we have an alternative library, `shadcn/ui`, already integrated into the project, providing similar functionality with no additional installation requirements. This enhancement proposes replacing `@headlessui/react` components with their counterparts from `shadcn/ui` to **streamline the codebase, reduce application size, and declutter dependencies**.

## Benefits

- **Reduced Application Size:** By eliminating the dependency on `@headlessui/react`, we can reduce the overall size of the application bundle.
- **Project Simplification:** Utilizing components from a single UI library simplifies maintenance and reduces the cognitive load for developers.
- **Consistency:** Ensuring consistency across UI components enhances user experience and improves code maintainability.
- **Optimized Performance:** With reduced dependencies, the application's performance may see marginal improvements, especially in load times and rendering efficiency.

**Comment by FurquanAnwer** [comment]
Please assign this issue to me!

**Comment by mfts** [comment]
@FurquanAnwer happy for you to take this one :)

**Comment by Kartikhub** [comment]
I have also worked on the issue, not knowing that others are also working on it. I have some changes that might complement the solution. Feel free to use if you find them helpful
