### ISSUE TITLE
[feat] add watermarking to documents

### ISSUE THREAD

**Issue by mfts** [mfts/papermark#267]
- Add watermarks to links that includes the email and the datetime of the visitor. 
- Placement of the watermark should bottom right (in the future we can make it movable)

**Comment by ashrafchowdury** [comment]
> Add watermarks to links that includes the email and the datetime of the visitor.

Could you explain this a little bit more?

**Comment by mdmm13** [comment]
By far the biggest issue holding back adoption in the venture context. Would be amazing to have!

**Comment by mdmm13** [comment]
> > Add watermarks to links that includes the email and the datetime of the visitor.
> 
> Could you explain this a little bit more?

I assume he's referring to this:

https://www.docsend.com/features/dynamic-watermarking/
https://help.docsend.com/hc/en-us/articles/360003884353-Watermarks

**Comment by ashrafchowdury** [comment]
Ohh I see, I would like to work on this feature, @mfts  🙌

**Comment by mfts** [comment]
@ashrafchowdury That would be awesome 😎

**Comment by mdmm13** [comment]
Any chance this will make 0.15? :-)

**Comment by mfts** [comment]
@mdmm13 fyi, we just shipped watermarking
