### ISSUE TITLE
PDF file icon is not visible on the light theme.

### ISSUE THREAD

**Issue by ashrafchowdury** [mfts/papermark#278]
## Description
**The file icons in the PDF are not visible on the light theme,** but they are visible on the dark theme. The icons' borders are not visible on the light theme.

## Steps To Reproduce
1. Login to the app
2. Upload a PDF document
3. Switch the theme into the light mood.
4. Check the PDF file icon.

## Screenshot

![image](https://github.com/mfts/papermark/assets/87828904/12ab40a9-e28f-4a81-b44d-49b6da9704e8)

**Comment by mfts** [comment]
Yes ideally we need a dark icon for it.
