### ISSUE TITLE
Ability to add custom name for documents uploaded and to delete docs

### ISSUE THREAD

**Issue by HunnySajid** [mfts/papermark#28]
I would like to add functionality to customize the document name while uploading. 
Right now the default name is picked. 
I was trying with some gibberish image files and could not identify them after uploading 3,4 files as all had random strings as names. 

Also, the ability to delete a file feels mandatory to me.

**Comment by mfts** [comment]
> I would like to add functionality to customize the document name while uploading.
Yes, this is 100% needed. Feel free to open a PR. Otherwise, I'm happy to get to it.

> the ability to delete a file feels mandatory to me.
Yes, I'm with you. You're more than welcome to take a swing at it :)

**Comment by HunnySajid** [comment]
Hey @mfts 
Thanks for the acknowledgment. I just spun up the project to see how it is working. The only blocker I have is Vercel blob storage. (I am still on the waiting list)
I think we might need to resolve https://github.com/mfts/papermark/issues/6 first, this could unblock other contributors too who can add value to this project. A quick (and dirty :| ) solution could work for us. We might not need it at all when vercel blob officially releases.

**Comment by mfts** [comment]
Let me see what I can do about your pending waiting list status :) and yes, I agree with #6 getting that off the ground would help unblock contributors

**Comment by HunnySajid** [comment]
@mfts Well that would really help if I get access to vercel blob. 
Meanwhile, I was trying to work with `multer`(for multipart form data serialisation) + `minio` combination as an alternate to vercel blob but I could not complete it.

So far I was able to run minio server in docker container and connect with that via minio client. 
I was trying to implement minio service with in the API as a separate route e.g **upload-minio**. 
The idea is to call separate endpoint from frontend based on the environment. I am using default nodejs runtime instead of edge in this route.

But I am stuck right now and still trying to comprehend it. 

Another approach could be to use minio client on client side only instead of api. Based on environment, we can either call the upload endpoint or run minio upload function on frontend to deal with storage.

**Comment by ashrafchowdury** [comment]
Thanks for your contribution, this feature has been added to the application, and you can now close this issue @HunnySajid

**Comment by HunnySajid** [comment]
@ashrafchowdury thanks for the update.
