### ISSUE TITLE
How to use alternative storage solutions

### ISSUE THREAD

**Issue by praveenraghav01** [mfts/papermark#29]
Hi, I want to know if there is a way to use RDS and S3 instead of vercel?

**Comment by mfts** [comment]
I feel you @praveenraghav01. I have a test running with S3, will open a PR later this week. I'm still hoping vercel/blob gets GA soon. 

As for RDS, you can just replace the DATABASE_URL in schema.prisma and .env with any postgres database.

**Comment by praveenraghav01** [comment]
Thank you so much. @mfts having S3 support would be super helpful

**Comment by mfts** [comment]
@praveenraghav01 please. Heck if you are on the vercel blob waitlist, they are opening it up this week: #42

**Comment by ashrafchowdury** [comment]
Hay @mfts, this issue is no longer relevant, we can close it here.

**Comment by mfts** [comment]
We added AWS S3 support in #301, therefore closing this issue.
