### ISSUE TITLE
Installation failure - npx prisma db deploy gives "Unknown command"

### ISSUE THREAD

**Issue by itacasoft** [mfts/papermark#310]
Trying to install it on Windows 10, when I try to run the npx command:

    _npx db prisma deploy_

it returns:

 _! Unknown command "deploy"

Manage your database schema and lifecycle during development.

Usage

  $ prisma db [command] [options]

Options

  -h, --help   Display this help message
    --schema   Custom path to your Prisma schema

Commands
     pull   Pull the state from the database to the Prisma schema using introspection
     push   Push the state from Prisma schema to the database during prototyping
     seed   Seed your database
  execute   Execute native commands to your database_

I should add the version of npm and npx program is 10.2.4:

_C:\usr\Projects\papermark>npm -v
10.2.4

C:\usr\Projects\papermark>npx -v
10.2.4__

Any hint how to proceed?
Thanks

**Comment by itacasoft** [comment]
I should add the the versions of npm and npx are 10.2.4

**Comment by ashrafchowdury** [comment]
Hay @itacasoft, I think you made a mistake. It's not `npx db prisma deploy` it's `npx prisma db deploy`

Try out this:
```
npx prisma db deploy
```       

If that's not working then try this, please let me know if all of them are working or not.
 ```
npx prisma db push
```

**Comment by ashrafchowdury** [comment]
Have you setup this env variable `POSTGRES_PRISMA_URL_NON_POOLING=` 

if not then add this `POSTGRES_PRISMA_URL_NON_POOLING=` environment variable to your `.env` file. The value of this env variable is going to same as this `POSTGRES_URL_NON_POOLING=` env variable.

**Comment by itacasoft** [comment]
Now, when issuing the command 

    _npm run dev_

I encounter the following error message:

C:\usr\Projects\papermark>npm run dev

> papermark@0.1.0 dev
> next dev

   ▲ Next.js 14.1.0
   - Local:        http://localhost:3000
   - Environments: .env
   - Experiments (use at your own risk):
     · missingSuspenseWithCSRBailout

 ⚠ Attempted to load @next/swc-win32-x64-msvc, but an error occurred: \\?\C:\usr\Projects\papermark\node_modules\@next\swc-win32-x64-msvc\next-swc.win32-x64-msvc.node is not a valid Win32 application.
\\?\C:\usr\Projects\papermark\node_modules\@next\swc-win32-x64-msvc\next-swc.win32-x64-msvc.node
 ⨯ Failed to load SWC binary for win32/x64, see more info here: https://nextjs.org/docs/messages/failed-loading-swc

Please help, thx

**Comment by ashrafchowdury** [comment]
Don't know exactly why it's happening, I guess something is wrong with your system.

Reinstalling npm packages can resolve this issue:
```
rm -rf node_modules
npm i
```

Otherwise if it's not working then share your basic operating system info so that I can assist you better.

**Comment by itacasoft** [comment]
Thank you @ashrafchowdury , I reached a page that was suggesting the same and it worked.

Now, web application starts, but when I try to register on page http://localhost:3000/login, apparently it works, but actually no email is sent. 
I registered on Resend with a free plan and set the RESEND_API_KEY value in the .env environment with the API Key copied from Resend web site, but I did not receive any email. 

![image_2024-02-27_153952263](https://github.com/mfts/papermark/assets/2667938/85545e98-505c-44a5-a408-ae2403c9af5a)
 
For information, I installed everything on my laptop connected to internet through my home WiFi, but I tried also hotspot of my mobile phone with no success.

Thanks in advance for any help.

 

Any suggestion?

**Comment by ashrafchowdury** [comment]
You have to run the email server to get to login.

Run the email server by using:
```
npm run email
```

**Comment by itacasoft** [comment]
ok. 
I have run "npm run email" on a CMD prompt, and "npm run dev" on another CMD prompt.
Now, trying to register give me a better understandable error:

<img width="909" alt="Untitled1" src="https://github.com/mfts/papermark/assets/2667938/6ffcc0ff-8c7e-4efe-88d2-d7ecbd8c1d0d">
[log_20240227.txt](https://github.com/mfts/papermark/files/14422461/log_20240227.txt)

What's next? Thx

**Comment by itacasoft** [comment]
Thank you @mfts and @ashrafchowdury , but I still have problem sending emails.
However, since the Prisma part is OK and the web server starts and responds, I would close the issue related to the installation and db deploy and open an issue related to email.
Thanks all for your support.
