### ISSUE TITLE
Is not possible to download

### ISSUE THREAD

**Issue by BernardoSM** [mfts/papermark#314]
Hey guys, even with "Allow downloading" option enabled is not possible to download the document because there's a react-draggable element overflowing the actions on the top. See this screenshot:

![image](https://github.com/mfts/papermark/assets/36281298/fb7fd57b-6981-4b36-8a9b-a1a1ff1cb90f)

**Comment by mfts** [comment]
Oh shoot! Thanks for the catch @BernardoSM. The element should not be above the navbar...  fix incoming
