### ISSUE TITLE
413 ERROR on upload deck

### ISSUE THREAD

**Issue by duelinggalois** [mfts/papermark#35]
Tried testing https://www.papermark.io and when I added a deck to upload it fails with not much notification. Opened inspection tools and see a failed call to upload api. 

![Screen Shot 2023-08-24 at 2 12 57 PM](https://github.com/mfts/papermark/assets/26027325/6606db3f-a307-474b-9994-d5a105e07564)

**Comment by mfts** [comment]
Thanks for the report @duelinggalois -- i will have a look at it right away

**Comment by mfts** [comment]
It seems that your file must have been larger than 4MB. I will have this fixed in the morning with larger uploads and proper error handling. Thanks for your report!

**Comment by duelinggalois** [comment]
My file is 24.2 MB. Product looks cool, would love to give it a test.
