### ISSUE TITLE
ERR_INVALID_URL, while building on vercel

### ISSUE THREAD

**Issue by pravin-compatio** [mfts/papermark#362]
i'm new to next.js and trying to setup papermark on vercel. while building, i'm getting this following error.

TypeError: Failed to parse URL from undefined/api/alternatives
<img width="1431" alt="image" src="https://github.com/mfts/papermark/assets/150922932/79462bf6-0dcd-4669-b762-0d2e291c6ad5">

input: 'undefined/api/alternatives'

**Comment by mfts** [comment]
Thanks for opening the issue. This is related to the CMS. Not related to the application. I'll fix the onboarding for self-hosting this week.

**Comment by pravin-compatio** [comment]
@mfts any update here ?

**Comment by im-calvin** [comment]
Having the same problem too!

**Comment by 54NJ33V** [comment]
@mfts any update on this??

**Comment by mfts** [comment]
Thanks for your patience. We fixed the issue with the environment variable in a recent commit https://github.com/mfts/papermark/pull/386/commits/1510668bf0eb1a1f50a4281067bc89421e2481e8. This should not cause an issue anymore.
