### ISSUE TITLE
[info] vercel/storage blob private beta is adding folks from the waitlist

### ISSUE THREAD

**Issue by mfts** [mfts/papermark#42]
In case you are not on the beta waitlist for vercel/blob yet, make sure you get on it from your account: https://vercel.com/storage/blob

The team is reviewing the waitlist this week and letting more folks in. 

![image](https://github.com/mfts/papermark/assets/4049052/a19a4254-069f-48e9-b678-d8598e0db5b9)

---

If you don't have access after this week, please drop your vercel team ID in the message below or DM me.

**Comment by gijigae** [comment]
Hello @mfts , thank you so much for the great project. Regarding the Vercel Blob service, joined the waitlist last week but haven't got access yet. Here is our team ID, team_TMv4oz0UYxTlvAXvfA8kWel8.

**Comment by mfts** [comment]
@gijigae pinged the team :)

**Comment by Ale1x** [comment]
Hello @mfts, I joined the waitlist, our team ID is: team_QfsdpzCKTIRbjsIvXf9Os4cL

**Comment by mfts** [comment]
I think it shouldn't be an issue anymore, also we added AWS S3 support, there are more options.
