### ISSUE TITLE
bug: document upload window still says only supported file type is .pdf 

### ISSUE THREAD

**Issue by TyceHerrman** [mfts/papermark#467]
As shown in image. However spreadsheets are able to be uploaded without issue. Seems like the text just needs to be updated. 
<img width="600" alt="Screenshot 2024-06-19 at 3 47 07 PM" src="https://github.com/mfts/papermark/assets/22066434/e9c42792-9ae4-491c-bd84-8136e4e2be4f">

**Comment by mfts** [comment]
Great eye, @TyceHerrman.

Do you fancy opening a pull request to update the text? :) 

Otherwise, happy to do it myself in the next few days.
