### ISSUE TITLE
sortable index for data rooms 

### ISSUE THREAD

**Issue by mfts** [mfts/papermark#475]
let's use this amazing sortable component 

https://github.com/sadmann7/sortable/blob/main/src/components/ui/sortable.tsx
also used by openstatus: https://github.com/openstatusHQ/openstatus/pull/820/files

**Comment by MohdSaquib114** [comment]
Hello @mfts  I want to work on this issue. Could you please provide more details about the issue ?  Thank you!

**Comment by mfts** [comment]
Hi @MohdSaquib114 thanks for your interest. I'd love for you to help with this issue. 

Basically there's a data room with folders and documents inside. The idea is to rearrange the documents' order in the data room by dragging & dropping the documents to the position you want them. 

![CleanShot 2024-07-12 at 18 16 18@2x](https://github.com/user-attachments/assets/ad255643-e3e7-4099-abde-8d4ca7454b58)

We want to sort the documents similar to how the example here with the data table sorts the rows 
https://sortable.sadmn.com/data-table

**Comment by Ashmash100** [comment]
Hi @mfts 
Is this issue still open? I would like to work on this

**Comment by mfts** [comment]
I haven't heard back from @MohdSaquib114 anymore. 

Let's give it another day and then I'm happy to assign it to you @Ashmash100 :)

**Comment by mfts** [comment]
@Ashmash100 i assigned you to the issue. Let me know if you need any support :)

**Comment by Ashmash100** [comment]
> @Ashmash100 i assigned you to the issue. Let me know if you need any support :)

Sure, thanks

**Comment by mfts** [comment]
@Ashmash100 quick fix: update the `plan` field in your database table `team`

But i'll update the localhost experience so this doesn't occurr

**Comment by Ashmash100** [comment]
Hi @mfts 

I have created a PR for this feature - https://github.com/mfts/papermark/pull/539. But I need help with one thing. Once we have dragged the document card, it's index should be updated. But I was not able to find the reducer which updates the documents. Need help with this
