### ISSUE TITLE
Vercel deploy link error

### ISSUE THREAD

**Issue by kaerez** [mfts/papermark#48]
Clicking on the Vercel deploy badge (link) returns an error (404)

**Comment by mfts** [comment]
Hi @kaerez thanks for the feedback. The click behaviour of the Vercel deploy badge is strange. It used to work and I just followed the docs for creating it. 

If you copy the link it will work. Here's the proper link: 

https://vercel.com/new/clone?repository-url=https:/github.com/mfts/papermark&env=NEXTAUTH_SECRET,NEXTAUTH_URL,POSTGRES_PRISMA_URL,POSTGRES_PRISMA_URL_NON_POOLING,BLOB_READ_WRITE_TOKEN,GOOGLE_CLIENT_ID,GOOGLE_CLIENT_SECRET,NEXT_PUBLIC_BASE_URL&envDescription=Here%27s%20an%20example%20.env%20for%20all%20variables%20required&envLink=https:/github.com/mfts/papermark/blob/main/.env.example&project-name=my-awesome-papermark&repository-name=my-awesome-papermark&demo-title=Papermark&demo-description=Papermark%20is%20an%20open-source%20document%20sharing%20alternative%20to%20DocSend%20with%20built-in%20analytics.&demo-url=https:/www.papermark.io&demo-image=https:/www.papermark.io/_static/papermark.png
