### ISSUE TITLE
Self-hosting build error: "middleware references unsupported modules"

### ISSUE THREAD

**Issue by tedspare** [mfts/papermark#49]
Hey! Killer product. I'm in the process of self-hosting at **doc.rubric.sh**:
- [x] Forked the repo (**Deploy on Vercel** button link is malformed with spaces or something)
- [x] Connected Vercel Blob and Postgres (which auto-populated 3 env vars  — could save some time for those following README)
- [x] Set up a Google OAuth 2.0 client (steps would be nice in README)
- [x] Connected Resend

Only seeing one build error:

```
Error: The Edge Function "middleware" is referencing unsupported modules:
--
22:42:22.596 | - middleware.js: @/lib/middleware/app, @/lib/middleware/domain
22:42:22.596 | - next: stream, fs, url, path
```

Where did I go wrong? Any help is appreciated, and keep up the great work!

**Comment by tedspare** [comment]
[Dumb issue](https://github.com/vercel/next.js/discussions/45384) on my end: in the Vercel project settings, I had to set **Framework Preset** to Next.js.

This said, fixing the Vercel deploy button should help others avoid this!

**Comment by HarshSTb** [comment]
Hey @tedspare when you were self hosting it. Did you also try login with the email magic link option. If yes were you able to setup resend api.
