### ISSUE TITLE
Can control access by email domains

### ISSUE THREAD

**Issue by jooddang** [mfts/papermark#52]
**Papermark can control access by email domains**

1. Allowlist
  - User can add email addresses or domains to allow access to a document only to the users. e.g. `foo@bar.com`, `*@baz.com`
  - User has to authenticate the their email address by clicking a link sent to the email. The email address should be `foo@bar.com` or `*@baz.com`.
  - User can open the link in the email to access a document.
2. Denylist
  - User can add email addresses or domains to prevent access to a document only to the users.. e.g. `foo@bar.com`, `*@baz.com`
  - User has to authenticate the their email address by clicking a link sent to the email. The email that embedded the the link should not be sent to `foo@bar.com` or `*@baz.com`.
  - User who are not `foo@bar.com` or `*@baz.com` can open the link in the email to access a document.

**Comment by mfts** [comment]
Thanks @jooddang that's an excellent suggestion! 

Would you like to work on this feature? I'm adding it to the roadmap (to be published)

**Comment by mfts** [comment]
Prioritizing this issue for this week :)
