### ISSUE TITLE
Missing Prisma migrations

### ISSUE THREAD

**Issue by tedspare** [mfts/papermark#54]
### Issue
- Deploying on Vercel showed "no pending migrations" in build step
- Self-hosted instance hung at missing tables. Confirmed no tables in project > Storage > Postgres.
- Running `npx prisma migrate dev` ([baseline](https://www.prisma.io/docs/guides/migrate/developing-with-prisma-migrate/baselining) script) manually generated the tables, then the app worked as expected

### Solution
  - Run `npx prisma migrate dev` and commit the initial migration
  - Add `prisma migrate deploy` to `vercel-build` command in package.json, as per the [Prisma Next.js example project](https://github.com/prisma/deployment-example-vercel/blob/main/package.json#L13)

Will open a PR shortly!

**Comment by mfts** [comment]
Thanks @tedspare for the comment. Yes indeed the migrations were missing. I pushed to iterate quickly on the db, but you're 100% right, it's time to add them. 

If you want please feel free to add the PR, otherwise, I'm happy to do it by the end of the week :)

**Comment by tedspare** [comment]
Thanks for the quick response! PR is up, LFG
