### ISSUE TITLE
Migration from npm to pnpm 

### ISSUE THREAD

**Issue by ArpitBlagan** [mfts/papermark#554]
@mfts If you want this I am ready to work on this?

**Comment by mfts** [comment]
I prefer NPM to be honest. Any particular reason for pnpm?

**Comment by ArpitBlagan** [comment]
Just going through this: https://refine.dev/blog/pnpm-vs-npm-and-yarn/#introduction
so I think it is a good time to migrate to PNPM.

**Comment by mfts** [comment]
I don't see the need for it yet. We don't have multiple app / packages where pnpm would shine. So right now it would just replace npm for no real added benefit.

**Comment by ArpitBlagan** [comment]
cool
