### ISSUE TITLE
Button text color fix on settings/billing page

### ISSUE THREAD

**Issue by nidhish-srivastava** [mfts/papermark#572]
White color looks way better than than the black color on the Upgrade to Business button in both light and dark mode
![image](https://github.com/user-attachments/assets/4b2e0797-b6c4-456c-a440-fb3588577cac)
![image](https://github.com/user-attachments/assets/69dd027e-de30-47dd-9586-0005f3e08dd1)
White color inside maintains a consistent color sense on the page

**Comment by mfts** [comment]
Want to open a PR for it?

**Comment by nidhish-srivastava** [comment]
Yes i would love to
