### ISSUE TITLE
Fix :  Better handling of Error Pages in document/id page

### ISSUE THREAD

**Issue by nidhish-srivastava** [mfts/papermark#577]
If user enters a wrong path of a document which ain't created and not available in the db then we get error with status of 400 from the useDocument hook but this status code isn't handled. The page keeps on showing the loading component 
![image](https://github.com/user-attachments/assets/54f4f748-99c1-4589-aeb9-9d668041f0a4)
Here /4 doesnt exist in db but still showing loading

Solution -  To to use ErrorPage condition for status code 400 similar to 404 status code that is already being used

If you find this issue relevant, you can assign me

**Comment by mfts** [comment]
Hey @nidhish-srivastava thanks. Yes indeed that's an issue. 

Would love your help :)

**Comment by nidhish-srivastava** [comment]
I am closing this issue since pr merged #584
