### ISSUE TITLE
fix : Unproteced datarooms route 

### ISSUE THREAD

**Issue by nidhish-srivastava** [mfts/papermark#587]
User can access datarooms page without opting for any trial or plan

![image](https://github.com/user-attachments/assets/e02f5396-b571-431f-9ac2-07fadcae2557)

We get Upgrade PlanModal when we click on Dataroom route on sidebar but if user enters /datarooms route  from searchbar, he can open this page.

I can work on this issue

**Comment by mfts** [comment]
Thanks for spotting this. Yes, I was aware of this. It would be awesome if you could work on this :)
