### ISSUE TITLE
Improvements to document viewer

### ISSUE THREAD

**Issue by mfts** [mfts/papermark#59]
Main idea: split document by page into individual images

Currently the document viewer uses react-pdf to render the PDF as a canvas element. This has some performance impediments on very large files. 

The web is better adept at handling images than any other document type (except text). 
By splitting the document into pages and saving each page as an image, the performance will improve drastically.

- enables different viewing perspectives (full screen, vertical scrolling, horizontal scrolling, multi-page view)

**Comment by duelinggalois** [comment]
Seems like a good place to leave this, gave this a second spin, cant use due to delay in render


https://github.com/mfts/papermark/assets/26027325/8beda781-28c5-4a69-9b92-ec9d79f9fd0e

**Comment by mfts** [comment]
@duelinggalois thanks for the feedback @duelinggalois. I'll DM you to onboard you on our new preview version.

**Comment by mfts** [comment]
Major improvements are done by loading individual pages as images instead of using react-pdf with #146
