### ISSUE TITLE
Make link favicon customizable

### ISSUE THREAD

**Issue by mfts** [mfts/papermark#599]
There's already the option to customize the meta title, description and image. However, it would be cool to customize the favicon as well. 

![CleanShot 2024-09-16 at 19 06 50@2x](https://github.com/user-attachments/assets/229d9c42-0a86-4c55-b60f-b7620ce655a5)

One idea is to take the custom domain's root domain favicon. 
Another idea is to let the user upload a url to the favicon or a favicon image

**Comment by AshishViradiya153** [comment]
I'd be happy to contribute to this task. Could you please assign it to me?

**Comment by mfts** [comment]
@AshishViradiya153 Amazing. Let me know if you have any questions

**Comment by kk7188048** [comment]
is this issue yet open?

**Comment by mfts** [comment]
> is this issue yet open?

No. @AshishViradiya153 is already working on it
