### ISSUE TITLE
Vercel Blob alternative when developing locally?

### ISSUE THREAD

**Issue by ephraimduncan** [mfts/papermark#6]
Vercel Blob is in private beta and is not open to everyone.

It is a restriction when you want to contribute and you don't have access to it. 

Is there a way to store documents locally without the need for Vercel blob?

**Comment by mfts** [comment]
That’s a good point, @dephraiim. There are certainly alternatives but not yet compatible with the vercel blob API. 

Would need to build a separate exception for local dev. 

I can imagine adding minio for local development. https://github.com/minio/minio

**Comment by dephraiim** [comment]
Adding it together with postgres with docker will be an good approach for easier development

**Comment by mfts** [comment]
Totally agree. Do you want to give this a try or else I can see when I get to it.

**Comment by mfts** [comment]
@dephraiim @HunnySajid the vercel team is opening up the waitlist for vercel blob this week. Make sure you are on it: #42

**Comment by dephraiim** [comment]
I actually found https://github.com/minio/minio, if Vercel Blob has the same API as S3, MinIO will be compactible for development

**Comment by initeshjain** [comment]
Can we use something like https://github.com/initeshjain/golang-ftp-server here? 
We can toggle dev/prod from a .env file and use fetch calls to upload files.

**Comment by mfts** [comment]
Interesting proposal @initeshjain i don't know this tool. I'll have a look

**Comment by initeshjain** [comment]
> Interesting proposal @initeshjain i don't know this tool. I'll have a look

I have written this code 2 days back and open sourced it. It is simple ftp server written in golang.

**Comment by mfts** [comment]
We added S3 a while back, so we support anything that's s3-compatible :)
