### ISSUE TITLE
Summarize documents

### ISSUE THREAD

**Issue by mfts** [mfts/papermark#61]
In general, this enables the recipient to interact with the document in a way other than just viewing it. We intend to leverage LLMs to achieve this. 

- summarize document into a single page of text
- for pitchdecks, turn decks into an investment memo
- ask questions to a document

More suggestions welcome :)

**Comment by Aashish-Upadhyay-101** [comment]
@mfts I would like to try this, it seems fun 🚀

**Comment by digant2482** [comment]
Hey, @Aashish-Upadhyay-101, are you working on  this issue ?

**Comment by Aashish-Upadhyay-101** [comment]
Hey, @digant2482, I haven't actually started working on this issue, but I really want to take on this one. 
You could look for another one please, I would say go for #58 or anything else

**Comment by digant2482** [comment]
Sure @Aashish-Upadhyay-101. I have some ideas on that. Can we connect on your twitter ? Here's my twitter @DigantP39147939

**Comment by Aashish-Upadhyay-101** [comment]
yeah sure !
