### ISSUE TITLE
Unhandled error on /documents page when api call made and we get error

### ISSUE THREAD

**Issue by nidhish-srivastava** [mfts/papermark#614]
![image](https://github.com/user-attachments/assets/71546c4e-f7f9-4455-a648-cb5876422280)
The page keeps on showing the loading skeleton when error is coming from api call on /documents page

**Comment by mfts** [comment]
Does this issue still persist @nidhish-srivastava ?

**Comment by nidhish-srivastava** [comment]
Yes this issue is there,what we fixed earlier was the error on /documents/[id] page,this page is still not fixed. I would love to solve this issue

**Comment by mfts** [comment]
I'd love for you to fix it @nidhish-srivastava :)

**Comment by AshishViradiya153** [comment]
Any updates @nidhish-srivastava? May I look into this one?

**Comment by nidhish-srivastava** [comment]
I am already working on this,find another issue to solve @AshishViradiya153

**Comment by AshishViradiya153** [comment]
Alright, Thanks for your suggestion.
