### ISSUE TITLE
How to set up MinIO for Blob storage?

### ISSUE THREAD

**Issue by MuhammadNaeem42** [mfts/papermark#623]
Hi, I'm working on setting up MinIO for Blob storage in my environment and would like some guidance. Specifically, I have the following questions:

1. Does the application support using MinIO as a backend for Blob storage out of the box? If so, what configurations are required?
2. Are there any examples or documentation on how to integrate MinIO with this application (e.g., bucket configurations, environment variables, etc.)?
3. Can MinIO be used interchangeably with other S3-compatible storage solutions for this project?

Thanks all

**Comment by mfts** [comment]
Yes, MinIO can be used with Papermark. We support all S3-compatible storage providers. 

https://github.com/mfts/papermark/blob/main/third-party-s3-providers.md

**Comment by MuhammadNaeem42** [comment]
Thankyou
