### ISSUE TITLE
[🕹️] OG Image generator

### ISSUE THREAD

**Issue by shnai0** [mfts/papermark#629]
Currently the image when shared on a document looks like this 

![meta](https://www.papermark.io/_static/meta-image.png)

The og-image generator should generate a metatag image that contains the first slide of the document, the name of the document and Papermark somewhere 

Example but too minialistic
![CleanShot 2024-10-07 at 15 52 04@2x](https://github.com/user-attachments/assets/e6193fd0-d53a-4d88-aee3-3f40d364c8fc)
 
Bonus: 
it would be great if the og-image generator can be configured to enable and disable showing the preview of the document. Some documents are too sensitive to show the content

**Comment by zaCKoZAck0** [comment]
@shnai0 any updates?

**Comment by harshsbhat** [comment]
> @harshsbhat, Just a little reminder: Please open a draft PR linking this issue within 12 hours. If we can't detect a PR in 12h, you will be unassigned automatically.

/unassign

**Comment by Pratham271** [comment]
I can work on this

**Comment by zaCKoZAck0** [comment]
Hi @adityadeshlahre 😊 I'm working on the issue. thanks, I've some prototypes ready as well. just occupied with some office work. Will raise a pr this weekend.

**Comment by Khaan25** [comment]
Hey @zaCKoZAck0, any updates on this? I would like to work on this issue?

**Comment by Khaan25** [comment]
@mfts , I've generated OG images for many nextjs app, I can do it properly and nicely. Would you like me to give it a chance? Could you please assign me?

**Comment by Khaan25** [comment]
@mfts, shall I raise a PR and if you could assign me? :)

**Comment by Khaan25** [comment]
@mfts, any update?

**Comment by harshsbhat** [comment]
@Khaan25 even I wanted to work on this issue. But @zaCKoZAck0 is already working on it. He is done two iterations. Check the WIP PR. 

https://github.com/mfts/papermark/pull/778
