### ISSUE TITLE
[🕹️] Send group mails

### ISSUE THREAD

**Issue by ykburda** [mfts/papermark#644]
### What side quest or challenge are you solving?

Feature request

### Points

?

### Description

We can send mails within outlook to a group of members. But we defined already this group in dataroom. It will be nice to send mail directly within system to defined group. Of course we need to give a body and a title. Also it will be nice to see sended mail in somewhere at dataroom.

### Provide proof that you've completed the task

?

**Comment by mfts** [comment]
Getting this right is super difficult. We don't want to spam people. I'd love to table this and postpone it to a later date

**Comment by mfts** [comment]
I'd love to award you with points for the 6 opened issues, some of them were really good!
