### ISSUE TITLE
[🕹️] Replace a document with a new version

### ISSUE THREAD

**Issue by ykburda** [mfts/papermark#645]
### What side quest or challenge are you solving?

Feature request

### Points

?

### Description

There should be somehow update of specific doc with a new version. Eg: kind of replace document. Now it is only possible delete old one and add new one. If we delete we will lose statistics and all others.

### Provide proof that you've completed the task

?

**Comment by mfts** [comment]
Thanks for opening the issue. However, this already exists in Papermark.
