### ISSUE TITLE
[🕹️] Make an agreement's display name customizable

### ISSUE THREAD

**Issue by mfts** [mfts/papermark#651]
### What side quest or challenge are you solving?

We have Agreements, which can be NDAs or Privacy Policies or any other kind of document that you'd like to have your viewer see before checking a document. 

Currently, we hardcode the display name to "Non-Disclosure Agreement". 

![CleanShot 2024-10-04 at 14 46 42@2x](https://github.com/user-attachments/assets/a7607c60-f7bc-46f0-a3bd-6a00b81ea01a)

However, it would be great if we could customize the display name.

### Points

750 Points

### Description

Additional information: 

Here's the agreement configuration sheet, perhaps we can reuse the `name` field for the Display name or create a new table field for display name.
![CleanShot 2024-10-04 at 14 46 17@2x](https://github.com/user-attachments/assets/ebcd90e6-f7a6-47ea-9239-4910a4904775)

### Provide proof that you've completed the task

Open a PR with description of what you have done.

**Comment by DeepaPrasanna** [comment]
May I have a try?

**Comment by DeepaPrasanna** [comment]
is the NDA service available to customers in the data rooms plan?

**Comment by mfts** [comment]
@DeepaPrasanna yes, if you are working locally, you can just change the `plan` on your team table
