### ISSUE TITLE
[🕹️]  Prevent Data Room Duplication Beyond Limit & Display Subscription Popup

### ISSUE THREAD

**Issue by AshishViradiya153** [mfts/papermark#652]
### What side quest or challenge are you solving?

- Prevent users from clicking the "Duplicate Data Room" button if they’ve reached the limit.
- Update the button to be disabled when the limit is reached.
- Show a subscription popup prompting users to upgrade when they hit the data room limit.

![dataroom](https://github.com/user-attachments/assets/dba8c639-781f-4fac-bf4e-7a46ca33254d)

### Points

@mfts ?

### Provide proof that you've completed the task

Open a PR with description of what you have done.

**Comment by mfts** [comment]
closed with #659
