### ISSUE TITLE
[🕹️]Create a "new" logo for Papermark

### ISSUE THREAD

**Issue by adarsh79singh** [mfts/papermark#654]
### What side quest or challenge are you solving?

Valid logos would be

square icon
designed wordmark of Papermark
icon + wordmark

### Points

1. Open a PR with a logo design → Get 150 points
2. We review all submissions and our favorites will be part of public vote on Twitter, so submit your Twitter name if you want to be mentioned

3. Winner get additional → 750 points

### Description

 We need a logo designed for our website to enhance our brand identity and improve user recognition. The logo should reflect the core values of our brand and align with the overall theme of the website. We want the design to be modern, professional, and memorable.

### Provide proof that you've completed the task

![paper Mark logo white](https://github.com/user-attachments/assets/ed590419-64e5-4806-8343-24eda5af976c)
![paper Mark logo black](https://github.com/user-attachments/assets/6cdfaf88-56ca-4123-9a90-c88b449a1684)

**Comment by mfts** [comment]
Thanks for the contribution!
