### ISSUE TITLE
[🕹️] Solved three Side quests

### ISSUE THREAD

**Issue by harshsbhat** [mfts/papermark#660]
### What side quest or challenge are you solving?

Follow [Papermark X (Twitter)](https://x.com/papermarkio) Account (50 Points)

Follow [Papermark LinkedIn](https://linkedin.com/company/papermarkio) Page (50 Points)

Design our new Papermark logo (150 Points per logo, 750 for the winner)

### Points

25-

### Provide proof that you've completed the task

Created a new logo:

Link: https://dub.sh/GAsHMmo

Followed on X:

![image](https://github.com/user-attachments/assets/2fe7e846-3fe8-4e7f-b30c-c6ba7faacbfe)

Followed on LinkedIn:

![image](https://github.com/user-attachments/assets/e325972e-8f34-48c7-8876-f1d4e6334e15)

**Comment by mfts** [comment]
awarded via PR #657
