### ISSUE TITLE
[🕹️] Three oss.gg side quests

### ISSUE THREAD

**Issue by Ionfinisher** [mfts/papermark#662]
### What side quest or challenge are you solving?

Follow [Papermark X (Twitter)](https://x.com/papermarkio) Account (50 Points)

Follow [Papermark LinkedIn](https://linkedin.com/company/papermarkio) Page (50 Points)

Design our new Papermark logo (150 Points per logo, 750 for the winner)

### Points

250

### Provide proof that you've completed the task

<img width="693" alt="Screen Shot 2024-10-06 at 13 42 21" src="https://github.com/user-attachments/assets/f017c474-bda6-4856-90ab-8d2322d2a1cc">

<img width="893" alt="Screen Shot 2024-10-04 at 15 37 08" src="https://github.com/user-attachments/assets/f16d4554-9534-4103-8d28-11ee15f95e9b">

Logo link : https://drive.google.com/drive/folders/1-HI4AYMGrruscHXsDnlzmiTq-LtjS3eL?usp=drive_link

**Comment by mfts** [comment]
@Ionfinisher Please share the logo so it's publicly visible:)

**Comment by Ionfinisher** [comment]
![papermark-logo-1](https://github.com/user-attachments/assets/de019e8c-13d2-4c1b-a526-00b27d83b083)

![papaermark-logo-2](https://github.com/user-attachments/assets/17cfad71-25a5-48f6-b5be-e1a2f3b7bb70)

![papermar-logo-3](https://github.com/user-attachments/assets/20e5e2de-593a-4263-9228-a7c9fcb2f0f2)

Sorry for that @mfts

**Comment by mfts** [comment]
awarded via pull request #665
