### ISSUE TITLE
[🕹️] Create a "new" logo for Papermark

### ISSUE THREAD

**Issue by Jemeni11** [mfts/papermark#663]
### What side quest or challenge are you solving?

[🕹️] Create a "new" logo for Papermark

### Points

(150 Points per logo, 750 for the winner)

### Description

Papermark doesn't have a logo! So we are open-sourcing it!

Currently we only have a wordmark of the text "Papermark".

Valid logos would be

square icon
designed wordmark of Papermark
icon + wordmark
Please align with the color scheme of Papermark, which is primarily black and white but has an orange accent color

### Provide proof that you've completed the task

![Group 1](https://github.com/user-attachments/assets/c832946c-7a4e-486f-a806-d39e873f13e1)

**Comment by mfts** [comment]
Thanks for the contribution!
