### ISSUE TITLE
[🕹️] Three oss.gg side quests

### ISSUE THREAD

**Issue by shatanikmahanty** [mfts/papermark#666]
### What side quest or challenge are you solving?

Follow [Papermark X (Twitter)](https://x.com/papermarkio) Account (50 Points)

Follow [Papermark LinkedIn](https://linkedin.com/company/papermarkio) Page (50 Points)

Design our new Papermark logo (150 Points per logo, 750 for the winner)

### Points

250

### Provide proof that you've completed the task

<img width="1512" alt="Screenshot 2024-10-07 at 12 37 40 AM" src="https://github.com/user-attachments/assets/e02648b1-6dfb-4ee6-830b-b3a429e118ca">

<img width="1355" alt="Screenshot 2024-10-07 at 12 38 11 AM" src="https://github.com/user-attachments/assets/f68318cf-1313-4bef-bf49-44f3eaa71c8a">

![papermark](https://github.com/user-attachments/assets/0bade7bf-1bfe-4854-bab8-c0ca1f452f8c)

**Comment by sharsha315** [comment]
Hi, I would like to work on this issue.

**Comment by shatanikmahanty** [comment]
> Hi, I would like to work on this issue.

It is actually my entry for OSS.gg side quest.

You can do the same by following this

https://mfts.notion.site/Papermark-Hacktoberfest-Side-Quests-Challenges-111d3f870f008033935efe9f7702a3dc#111d3f870f0081efb82fd83277c61ede

**Comment by mfts** [comment]
Thank you for the contribution!
