### ISSUE TITLE
[🕹️] oss.gg Side Quests Submissions (Multiple)

### ISSUE THREAD

**Issue by thefool76** [mfts/papermark#671]
### What side quest or challenge are you solving?

1. Follow [Papermark X (Twitter)](https://x.com/papermarkio) Account (50 Points).
2. Follow [Papermark LinkedIn](https://linkedin.com/company/papermarkio) Page (50 Points)
3. Meme Magic (150 Points)
4. Gif Magic (150 Points)

### Points

400

### Description

1. Followed  [Papermark X (Twitter)](https://x.com/papermarkio) Account
2. Followed [Papermark LinkedIn](https://linkedin.com/company/papermarkio) Page 
3. Created Meme Magic 
4. Created Gif Magic 

### Provide proof that you've completed the task

1. Followed  [Papermark X (Twitter)](https://x.com/papermarkio) Account
![Screenshot 2024-10-07 at 11 16 32 AM](https://github.com/user-attachments/assets/a3de5878-7cef-4e43-b2d4-371420e4d2e6)

2. Followed [Papermark LinkedIn](https://linkedin.com/company/papermarkio) Page 
![Screenshot 2024-10-07 at 11 27 00 AM](https://github.com/user-attachments/assets/7991dda4-18f7-4c21-b8b7-16405f6e2edd)

3. Created Meme Magic 
[X meme Link](https://x.com/thefool1135/status/1843180633511928264)

4. Created Gif Magic 
[Papermark Gif](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExdjF5YTR4OTlzY3p1NHF1eHdqbzl3c3I4NWhwN3hwdTFqMG5tbDY5eSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/y72GrlfB4fIUAiwVH3/giphy.gif)

**Comment by mfts** [comment]
Thank you for the submissions! Could you please share you LinkedIn account and Twitter account as well :)

**Comment by thefool76** [comment]
> Thank you for the submissions! Could you please share you LinkedIn account and Twitter account as well :)

Hey Marc I know managing oss repos in October is hard. I apologise for the inconvenience 
Here is my link
[x profile](https://x.com/thefool1135?t=xqC0qjdOnCPHM4R5FA6n6A&s=09)

[LinkedIn](https://www.linkedin.com/in/avesh-mishra?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app)
