### ISSUE TITLE
[🕹️] Data Room Deletion: Title Mismatch Even with Same Title

### ISSUE THREAD

**Issue by AshishViradiya153** [mfts/papermark#672]
### What side quest or challenge are you solving?

![image](https://github.com/user-attachments/assets/ba268490-b3ba-4218-a5c2-05fe602b8dc9)

### Points

@mfts ?

### Provide proof that you've completed the task

Open a PR with description of what you have done

**Comment by mfts** [comment]
@AshishViradiya153 create catch! 

/award 50

**Comment by AshishViradiya153** [comment]
Fixed: https://github.com/mfts/papermark/pull/673
