### ISSUE TITLE
[🕹️] 2 Side Quests: Follow Papermark on Linkedin and X (Twitter)

### ISSUE THREAD

**Issue by yashsharma999** [mfts/papermark#676]
### What side quest or challenge are you solving?

1. Follow [Papermark X (Twitter)](https://x.com/papermarkio) Account (50 Points)
2. Follow [Papermark LinkedIn](https://linkedin.com/company/papermarkio) Page (50 Points)

### Points

100

### Provide proof that you've completed the task

<img width="955" alt="Screenshot 2024-10-07 at 8 46 30 PM" src="https://github.com/user-attachments/assets/a850a1c0-0dcf-4d6f-ba5f-f74c0a935c66">

<img width="1092" alt="Screenshot 2024-10-07 at 8 50 14 PM" src="https://github.com/user-attachments/assets/a8ca9080-cc50-4af2-b8f0-459178b46bcc">

**Comment by Abishkardhenga** [comment]
assign me this issue

**Comment by Abishkardhenga** [comment]
@yashsharma999  assign this issue to me

**Comment by yashsharma999** [comment]
Hey @Abishkardhenga, this is a side quest and doesn't require an assignee. For more info refer to: https://formbricks.notion.site/How-to-submit-a-non-code-contributions-via-GitHub-81166e8c948841d18209ac4c60280e60

**Comment by Rishi-0007** [comment]
## Proof

![image](https://github.com/user-attachments/assets/a1092398-27de-4cad-a4cb-02d027f0c5bc)
![Screenshot from 2024-10-08 17-57-52](https://github.com/user-attachments/assets/cc6471cd-57be-405c-9204-4e631c03cc7a)

**Comment by mfts** [comment]
@Rishi-0007 please open a separate issue and add your side quest proof there. this issue is for Yash

**Comment by mfts** [comment]
@yashsharma999 Thanks for the support :)
