### ISSUE TITLE
[🕹️] Improve Document "Action" Tab

### ISSUE THREAD

**Issue by AshishViradiya153** [mfts/papermark#677]
### What side quest or challenge are you solving?

- Add tab for create dataroom and if dont have a right plan than show update subscription,
- if dataroom are their than only show dataroom tab, otherwise upgrad to create dataroom... 

https://github.com/user-attachments/assets/b880b789-af8c-4e72-9160-72d0baae0779

### Points

@mfts ?

### Provide proof that you've completed the task

Open a PR with description of what you have done

**Comment by mfts** [comment]
great issue 

/award 50

**Comment by AshishViradiya153** [comment]
@ChaseNelson, no need to work on this. It's already solved and fixed by me. The PR is ready for review.

**Comment by AshishViradiya153** [comment]
It doesn't only contain what's described here; it includes more than the description.

**Comment by AshishViradiya153** [comment]
@hinakamal555 Please find another task. PR under review for this task.
