### ISSUE TITLE
[🕹️] Bug 🐞 : Dropzone UI Issue

### ISSUE THREAD

**Issue by yashsharma999** [mfts/papermark#679]
### What side quest or challenge are you solving?

Bug Hunter (50 - 150 Points for every bug)

### Points

50 - 150

### Description

- When dropping files on `/documents` page, dropzone is not able to catch files in the available free space. 
- Only when the user drags the files over some existing document the dropzone becomes active. 
- When there is no existing document, drag and drop doesn't work

### Provide proof that you've completed the task

<img width="1431" alt="Screenshot 2024-10-07 at 10 48 31 PM" src="https://github.com/user-attachments/assets/97ae2d09-2a7f-42f3-93be-7c774fe6c623">

<img width="1426" alt="Screenshot 2024-10-07 at 10 44 16 PM" src="https://github.com/user-attachments/assets/151b6870-24c6-4f47-b578-00cfb06848f5">

<img width="1430" alt="Screenshot 2024-10-07 at 10 44 08 PM" src="https://github.com/user-attachments/assets/1c75563e-a071-4fa6-8571-bcadebf4662e">

**Comment by mfts** [comment]
great catch @yashsharma999 

/award 150

**Comment by YashJsh** [comment]
Why yashsharma999 has awarded with the points, I have submitted the pull request, he has removed his assignment?
