### ISSUE TITLE
Team management

### ISSUE THREAD

**Issue by mfts** [mfts/papermark#68]
Obvious one! 

Manage your account and documents with your team <3

**Comment by Aashish-Upadhyay-101** [comment]
@mfts  can you explain this in detail, I would like to work on this feature.

**Comment by mfts** [comment]
@Aashish-Upadhyay-101 currently documents are connected to the user directly. 

we want to introduce a new model `Team` so that documents are owned by a team. the user can be part of multiple teams. This requires also UI changes. 

`User` will be connected to `Team` via `TeamMember` model

```
model User {
 ...
 teams    Team[]
}

model TeamMember {
 ...
 userId
 user User
 teamId
 team Team
}

model Team {
 users    TeamMember[]
```  

Documents, domains, plan will be connected to `Team` model

Let me know what your thoughts are :)

**Comment by Aashish-Upadhyay-101** [comment]
@mfts can you explain me a little bit about how ***Team***  and ***Domain*** are related, and how they work?

**Comment by mfts** [comment]
@Aashish-Upadhyay-101 `Team` has many `Domain` similar to how the relationship is currently on the `User`

**Comment by mfts** [comment]
completed with #105
