### ISSUE TITLE
[🕹️] Created a "new" logo for Papermark 

### ISSUE THREAD

**Issue by adityadeshlahre** [mfts/papermark#680]
### What side quest or challenge are you solving?

Creating a logo for papermark and other OS projects

### Points

150 - 750 for winner

### Provide proof that you've completed the task

![7](https://github.com/user-attachments/assets/a1d400d4-d9ac-472a-ae13-33f7bb5ce557)
![6](https://github.com/user-attachments/assets/94e05bab-095f-4801-aafe-fed41c78b605)
![5](https://github.com/user-attachments/assets/3c69740a-1673-46d3-817d-272e286b4a6d)
![4](https://github.com/user-attachments/assets/c60ffbca-efa4-46b9-b7e4-dfc466c0d181)
![3](https://github.com/user-attachments/assets/8b2e1a0a-1504-42be-9473-45abfaba70d8)
![2](https://github.com/user-attachments/assets/bf3a0eb1-08b4-4e13-935a-a86034bc7d2b)
![1](https://github.com/user-attachments/assets/2f2330e8-167c-40e7-865d-2852a493faa5)

**Comment by adityadeshlahre** [comment]
I know I won't be getting multiple for multiple logos but I had a fun creating these so made more then one :slightly_smiling_face:

**Comment by mfts** [comment]
Thanks @adityadeshlahre looks really cool!

I awarded the points in #681
