### ISSUE TITLE
Data room

### ISSUE THREAD

**Issue by mfts** [mfts/papermark#69]
Natural extension of one document, one link. 

For those who don't know what a data room is, think of it like a Linktree for documents: one link gives you access to many curated documents. 

This is the advanced version of #63

**Comment by Aashish-Upadhyay-101** [comment]
hey @mfts I would like to take this.

**Comment by mfts** [comment]
Yes absolutely! 

The goal is that we have one link and this links enables access to multiple documents. 
Each document should still track the engagement for each visitor. 

Let me know if you have any questions @Aashish-Upadhyay-101

**Comment by digant2482** [comment]
Hey @Aashish-Upadhyay-101  are you working on this issue ?

**Comment by Aashish-Upadhyay-101** [comment]
@digant2482 I am currently working on notification feature, you can take this if you want 🥇

**Comment by mfts** [comment]
Awesome @digant2482

**Comment by digant2482** [comment]
Hi @mfts. Just wanted to take your opinion on my design/functionality. Please check the video:
Features:
Data room section on sidebar.
Data room page.
Data room modal to add documents to modal
Add documents to data room modal.
Features to be done:
Prisma schema (add data room table)
Backend API's to fetch data rooms
Will complete everything by tomorrow. Please provide feedback (if any) on changes needed to be done
https://github.com/mfts/papermark/assets/73285842/00ef2040-2b89-49a1-be5d-8356fa24f5f4

**Comment by mfts** [comment]
@digant2482 it's similar to #63 

The goal is to have one link that gives access to many documents. As a recipient, I receive a link to a data room. I enter my email and then I see a folder structure to navigate the data room. When I visit each document within the dataroom, it will be tracked like a usual.. 

Video looks good but I don't think you built it with **one link** yet. Let me know if you have any question

**Comment by digant2482** [comment]
Thank you for the feedback, @mfts. This video is from the user's point of view (what documents a person wants to include inside the dataroom). 

The plan is to allow Papermark users to choose the documents to include in the dataroom (they can create more than one dataroom as well). There will be a unique link to that dataroom, which they can share with their customers.

I have one doubt, though. Do we want a folder structure, where there are folders inside folders, representing different pages? Or do we need a Linktree-like page, where people can access multiple documents on a single page?

**Comment by digant2482** [comment]
Hi, @mfts. I have create both versions (Linktree like datarooms and folder structure dataroom). Please check the videos for the same:
Folder structure dataroom
https://github.com/mfts/papermark/assets/73285842/1043d06b-a0c5-40fc-814b-e66f3f27cc5a

Linktree dataroom
https://github.com/mfts/papermark/assets/73285842/d6201efa-6028-408e-bcf9-8ff9463b7abf

Key points:
Hierarchical Datarooms
- Google Drive like folder structure
- Tracks links
- Edit/Delete file/folder names
- Navigation bar for easy navigation
- Only single backend call for whole 
  dataroom by maintaining state in frontend
  using useReducer hook
- Optimized re-renders using React memo
- Can edit dataroom name, description by
  clicking on it
- Tracks dataroom views in database
- Send emails to owner if dataroom is viewed
- Email protection, password protection
  for datarooms (Default email verification
  required)
- Plus more...

Linktree (Single-paged datarooms)
- Quick link-tree like datarooms
- Tracks links 
- Tracks dataroom views in database
- Send emails to owner if dataroom is viewed
- Email protection, password protection
  for datarooms (Default email verification
  required)
- Input validation on inputs

**Comment by mamscience** [comment]
Really looking forward to this feature. Any timeline when the review will start for this pull request?

https://github.com/mfts/papermark/pull/243

**Comment by mfts** [comment]
Added datarooms a while back.
