### ISSUE TITLE
[🕹️]Retweet and like side quest

### ISSUE THREAD

**Issue by YashJsh** [mfts/papermark#694]
### What side quest or challenge are you solving?

<img width="832" alt="Screenshot 2024-10-09 at 1 13 35 AM" src="https://github.com/user-attachments/assets/d9530dbd-0611-4f33-8609-4453ea76f8b2">
<img width="1331" alt="Screenshot 2024-10-09 at 1 09 55 AM" src="https://github.com/user-attachments/assets/4a188f93-0b79-4c32-ada7-7eea54fbaad4">

### Points

100

### Provide proof that you've completed the task

<img width="832" alt="Screenshot 2024-10-09 at 1 13 35 AM" src="https://github.com/user-attachments/assets/d9530dbd-0611-4f33-8609-4453ea76f8b2">
<img width="1331" alt="Screenshot 2024-10-09 at 1 09 55 AM" src="https://github.com/user-attachments/assets/4a188f93-0b79-4c32-ada7-7eea54fbaad4">

**Comment by mfts** [comment]
Thanks :)
/award 100
