### ISSUE TITLE
[🕹️] New Papermark logo

### ISSUE THREAD

**Issue by jonas-hoebenreich** [mfts/papermark#695]
### What side quest or challenge are you solving?

https://github.com/mfts/papermark/issues/630

This Papermark logo design features an origami-inspired "P" icon, crafted from folded black paper. This design represents the precision and simplicity associated with Papermark while paying homage to the paper medium that Papermark is digitizing. In the wordmark, the "P" seamlessly transitions as the first letter of the brand name, creating a cohesive and adaptable design that is both modern and versatile.

### Points

150

### Description

I designed a new logo for Papermark. The font used for the wordmark is Jockey One. This font can be easily replaced with anything else.

### Provide proof that you've completed the task

![papermark-icon](https://github.com/user-attachments/assets/37de9ce4-5985-4dd2-8f6a-d2a89967aec4)
![papermark-logo](https://github.com/user-attachments/assets/37889c6c-f939-4e82-bf4c-461fc6eb295c)

**Comment by mfts** [comment]
Wow @jonas-hoebenreich that looks incredible! The detail on that folded paper 🤯

/award 150
