### ISSUE TITLE
[🕹️] Add new doc from content inside dataroom

### ISSUE THREAD

**Issue by ykburda** [mfts/papermark#699]
### What side quest or challenge are you solving?

Feature Request

### Points

?

### Description

There is functionality “adding to dataroom” from documents content. But it is not possible “add from content” inside dataroom. There is “ add new doc” button but it is not allowing selection from document-content. It will be nice just select from inside dataroom

### Provide proof that you've completed the task

?

**Comment by ykburda** [comment]
Oss-gg is there anykind of assign trick? Interesting.

**Comment by AshishViradiya153** [comment]
@mfts, I created the PR because I don’t think anyone is working on this ticket.
