### ISSUE TITLE
Additional login method

### ISSUE THREAD

**Issue by mfts** [mfts/papermark#72]
- [ ] Login with email magic link
- [ ] Login with passkeys

**Comment by tedspare** [comment]
Some resources:
- Passkeys: not supported by NextAuth yet. [Hanko](https://www.hanko.io/) is an option.
- Magic link: add the [NextAuth EmailProvider](https://authjs.dev/guides/providers/email-http#setup) to [providers](https://github.com/mfts/papermark/blob/main/pages/api/auth/%5B...nextauth%5D.ts#L9C3-L13C6). Send the magic link with Resend in the `sendVerificationRequest()` callback:

**/api/[...nextauth.ts]**
```typescript
...
providers: [
   ...
    {
      id: 'resend',
      type: 'email',
      async sendVerificationRequest({ identifier: email, url }) {
         const emailTemplate = MagicLinkTemplate({ url });
         await sendEmail({
             to: email as string,
             subject: "Sign in with magic link!",
             react: emailTemplate,
        });
      }
    }
  ],
...
```

New users will be signed up. Existing users will be logged in.

**Comment by yashsharma999** [comment]
For login with passkeys, can also consider [Passage](https://docs.passage.id/hosted-login/guides/auth.js-next.js) as an option? @tedspare 


```js
import Passage from 'next-auth/providers/passage';

...
providers: [
    GoogleProvider({
      clientId: process.env.GOOGLE_CLIENT_ID as string,
      clientSecret: process.env.GOOGLE_CLIENT_SECRET as string,
    }),
    Passage({
      clientId: process.env.PASSAGE_ID as string,
      clientSecret: process.env.PASSAGE_SECRET as string,
      issuer: process.env.PASSAGE_ISSUER,
    }),
  ],
...
```

**Comment by mfts** [comment]
> New users will be signed up. Existing users will be logged in.

@tedspare definitely going with `next-auth` for magic link. i haven't looked into how it behaves with merging accounts that are already signed up with google or another provider. 

I saw that dub.co did the reverse from magic link to google provider and had to write extra function to merge the accounts.
