### ISSUE TITLE
[🕹️]Follow Papermark X (Twitter) Account (50 Points):

### ISSUE THREAD

**Issue by Sam-at-code** [mfts/papermark#720]
### What side quest or challenge are you solving?

Follow [Papermark X (Twitter)](https://x.com/papermarkio) Account (50 Points):

### Points

50 points are assigned to this contribution 

### Description

Followed Papermark's X (Twitter) account. Liked and retweeted the launch post

### Provide proof that you've completed the task

![Screenshot 2024-10-11 092733](https://github.com/user-attachments/assets/832e014f-7a4f-4dfd-8db6-e9226ef73fbd)
![Screenshot 2024-10-11 092841](https://github.com/user-attachments/assets/adfce503-09d6-49da-b252-a4292402a305)

**Comment by PranjalGupta280** [comment]
![Screenshot 2024-10-11 095317](https://github.com/user-attachments/assets/1fece14d-8fe1-4986-838e-a27ab5a9cf80)

**Comment by mfts** [comment]
@PranjalGupta280 please open your own issue
