### ISSUE TITLE
[🕹️]Follow Papermark X (Twitter) Account

### ISSUE THREAD

**Issue by Sulochan-khadka** [mfts/papermark#725]
### What side quest or challenge are you solving?

Follow [Papermark X (Twitter)](https://x.com/papermarkio) Account

### Points

50

### Description

Followed

### Provide proof that you've completed the task

<img width="1435" alt="Screenshot 2024-10-11 at 1 03 30 PM" src="https://github.com/user-attachments/assets/e4ecb751-a273-46c9-ae89-ce341033a1a3">

**Comment by rahulkr-dev** [comment]
I have followed the Papermark X Twitter account as requested. Here is the screenshot:

![twitter-following-proof](https://github.com/user-attachments/assets/6ffde6a0-843a-43dc-9242-26ea195da8b5)

**Comment by manishkumar123456** [comment]
followed
![Screenshot (101)](https://github.com/user-attachments/assets/a2c1da54-0098-48c4-a407-5ce6f5d79f76)
