### ISSUE TITLE
[🕹️]Follow Papermark Linkedin Page

### ISSUE THREAD

**Issue by milanp19** [mfts/papermark#733]
### What side quest or challenge are you solving?

Follow Papermark Linkedin Page

### Points

50

### Description

Followed Papermark Linkedin Page

### Provide proof that you've completed the task

![Screenshot 2024-10-11 134120](https://github.com/user-attachments/assets/c3d7e203-2247-410a-b155-326da94d14e7)

**Comment by Zahhiiir** [comment]
Followed Papermark Linkedin Page
Proof of task provided as well.
![Papermark_linkedin](https://github.com/user-attachments/assets/e41a586e-d68f-4145-9bcd-3dfa2f1528a3)

**Comment by GuraaseesSingh** [comment]
@milanp19  I have already done the PR, please consider

**Comment by Vaibhav-nk-git** [comment]
Followed Papermark Linkedin Page
Proof...


![Screenshot 2024-10-11 142349](https://github.com/user-attachments/assets/f754284c-d2cb-4308-9ed1-8d308628668d)

**Comment by mfts** [comment]
@Vaibhav-nk-git @GuraaseesSingh @Zahhiiir please open your own issues
