### ISSUE TITLE
[🕹️]Follow Papermark Twitter Account 

### ISSUE THREAD

**Issue by hiralvavadiya** [mfts/papermark#742]
### What side quest or challenge are you solving?

- Follow Papermark Twitter Account

### Points

50 points

### Provide proof that you've completed the task

<img width="672" alt="Screenshot 2024-10-11 at 3 11 56 PM" src="https://github.com/user-attachments/assets/47d81caf-b003-4226-8f21-2a4fa8018b08">

<img width="601" alt="Screenshot 2024-10-10 at 6 56 32 PM" src="https://github.com/user-attachments/assets/340aecf8-fc78-4b20-8eec-a00e09cc579f">

**Comment by mfts** [comment]
@rxhul18 please open your own issue
