### ISSUE TITLE
[🕹️]Follow Papermark X (Twitter) Account

### ISSUE THREAD

**Issue by ishwarthecodddr** [mfts/papermark#745]
### What side quest or challenge are you solving?

Follow Papermark X (Twitter) Account

### Points

50

### Description

Followed Papermark on twitter(X)

### Provide proof that you've completed the task

Proof:
![image](https://github.com/user-attachments/assets/819da788-97de-4f9b-b1bd-1add981a695e)

**Comment by krishna-cyber** [comment]
Followed Papermark X (Twitter) Account



Description
Followed Papermark on twitter(X)

Provide proof that you've completed the task
Proof:
![image](https://github.com/user-attachments/assets/1f79edc0-1bf7-46b1-a59f-b6e529895835)

**Comment by mfts** [comment]
@krishna-cyber please open your own issue
