### ISSUE TITLE
[🕹️]Follow Papermark LinkedIn Page 

### ISSUE THREAD

**Issue by hiralvavadiya** [mfts/papermark#748]
### What side quest or challenge are you solving?

- Followed Papermark LinkedIn Page

### Points

50 points

### Provide proof that you've completed the task

<img width="472" alt="Screenshot 2024-10-11 at 3 18 10 PM" src="https://github.com/user-attachments/assets/978c3f8d-7a09-430a-9bab-b79f1f51a342">
<img width="533" alt="Screenshot 2024-10-11 at 3 21 35 PM" src="https://github.com/user-attachments/assets/e492aea6-3d84-465a-a8b3-23a3cb682615">

**Comment by Nisarg-Sha** [comment]
![Screenshot 2024-10-11 at 3 32 46 PM](https://github.com/user-attachments/assets/cfe4f5b9-7cf0-4563-ba0a-66245159994e)
follow papermark linkedin page
