### ISSUE TITLE
REST API

### ISSUE THREAD

**Issue by mfts** [mfts/papermark#75]
- [ ] Upload documents (and delete)
- [ ] Create link (and delete)
- [ ] Send link
- [ ] Retrieve views

Suggestions for additional functionality that an API should perform are welcomed

**Comment by Aashish-Upadhyay-101** [comment]
I would like to work on this issue 🚀

**Comment by mfts** [comment]
Awesome @Aashish-Upadhyay-101 looking forward to it. Feel free to break this into multiple tasks and share what you are building :)
