### ISSUE TITLE
[🕹️]  New Logo for Papermark

### ISSUE THREAD

**Issue by ameghcoder** [mfts/papermark#755]
### What side quest or challenge are you solving?

#630

### Points

150

### Description

Hello @mfts, This logo is simple, and minimalist and contains only two colors first is orange (that is your accent color) and second is black which is the base color, this logo is not only unique but also more attractive than the previous one.

### Provide proof that you've completed the task

![PaperMark - Logo](https://github.com/user-attachments/assets/74560204-dc3a-4352-b90f-0f88aa9fa6a2)
![PaperMark - Logo with text](https://github.com/user-attachments/assets/74f05960-412e-4257-8255-ed843639574a)
![PaperMark - Logo with text in square](https://github.com/user-attachments/assets/23e96894-1908-4380-ab2a-5da2d96cc0f3)

**Comment by mfts** [comment]
@Hitarthsheth07 you can open your own issue with your own logo idea to get points
