### ISSUE TITLE
[🕹️]Follow Papermark LinkedIn Page

### ISSUE THREAD

**Issue by Nisarg-Sha** [mfts/papermark#757]
### What side quest or challenge are you solving?

Followed Papermark LinkedIn Page

### Points

50

### Provide proof that you've completed the task

![Uploading Screenshot 2024-10-11 at 3.32.46 PM.png…]()

**Comment by mfts** [comment]
/award 50 thanks! Happy to have you participate :) 

@shindebhavika 
to everyone else commenting: if you not already, pls open your own issue with proof of completing the quest :
I can only award the author of an issue with points!

more Papermark side quests here 👇
https://mfts.notion.site/Papermark-Hacktoberfest-Side-Quests-Challenges-111d3f870f008033935efe9f7702a3dc
