### ISSUE TITLE
[🕹️]Follow Papermark X (Twitter) Account

### ISSUE THREAD

**Issue by Nisarg-Sha** [mfts/papermark#758]
### What side quest or challenge are you solving?

Follow Papermark X (Twitter) Account

### Points

50

### Provide proof that you've completed the task

<img width="1512" alt="Screenshot 2024-10-11 at 7 12 48 PM" src="https://github.com/user-attachments/assets/196764bb-2830-4e00-a72f-e8c31a74c5ea">

**Comment by mfts** [comment]
/award 50 thanks! Happy to have you participate :) 

@shindebhavika 
to everyone else commenting: if you not already, pls open your own issue with proof of completing the quest :
I can only award the author of an issue with points!

more Papermark side quests here 👇
https://mfts.notion.site/Papermark-Hacktoberfest-Side-Quests-Challenges-111d3f870f008033935efe9f7702a3dc
