### ISSUE TITLE
[🕹️]Follow Papermark X (Twitter) Account

### ISSUE THREAD

**Issue by milanp19** [mfts/papermark#760]
### What side quest or challenge are you solving?

Follow Papermark X (Twitter) Account

### Points

50

### Description

Followed Papermark X (Twitter) Account

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/82cd1007-2f69-4c81-b594-a7b3ad4c16e2)

**Comment by AVtheking** [comment]
![image](https://github.com/user-attachments/assets/c498c665-fb64-4a42-8315-7fef9f99c2d3)

**Comment by SrinivasReddy78** [comment]
![image](https://github.com/user-attachments/assets/9b02183f-9312-4695-8687-96609bf402aa)

**Comment by mfts** [comment]
/award 50 thanks! Happy to have you participate :) 

@AmanSagar0607 @SrinivasReddy78  @AVtheking 
to everyone else commenting: if you not already, pls open your own issue with proof of completing the quest :
I can only award the author of an issue with points!

more Papermark side quests here 👇
https://mfts.notion.site/Papermark-Hacktoberfest-Side-Quests-Challenges-111d3f870f008033935efe9f7702a3dc
