### ISSUE TITLE
[🕹️]Follow Papermark Twitter Account

### ISSUE THREAD

**Issue by Shlok2302** [mfts/papermark#762]
### What side quest or challenge are you solving?

Solving a Papermark side quest :  Follow Papermark X(Twitter) Account

### Points

50

### Description

Followed the Twitter(X) page of Papermark

### Provide proof that you've completed the task

![Follow](https://github.com/user-attachments/assets/cf315d6b-a58e-420a-ac91-49ceeb3d2318)

**Comment by mfts** [comment]
/award 50 thanks! Happy to have you participate :) 

@mitgajera @GaneshB2334 @SoftwareDeveloperYadavJi 
to everyone else commenting: if you not already, pls open your own issue with proof of completing the quest :
I can only award the author of an issue with points!

more Papermark side quests here 👇
https://mfts.notion.site/Papermark-Hacktoberfest-Side-Quests-Challenges-111d3f870f008033935efe9f7702a3dc
