### ISSUE TITLE
[🕹️] oss.gg Multiple Quests Submission (400 Point) 

### ISSUE THREAD

**Issue by Sahil-Gupta584** [mfts/papermark#767]
### What side quest or challenge are you solving?

1. Follow [Papermark LinkedIn](https://linkedin.com/company/papermarkio) Page (50 Points):
2. Follow Papermark X (Twitter) Account (50 Points)
3. Gif Magic (150 Points)
4. Meme Magic (150 Points)

### Points

Total :400

### Provide proof that you've completed the task

1.Meme Magic ( 150 points)
[X meme link](https://x.com/guptas3067/status/1844770050277785670)

Side Quest: Gif Magic ( 150 points)
[Giphy Link](https://giphy.com/gifs/paperwork-ossgg-hactoberfest-PyGwXgOOzVd2xDiH2C)
 

Side Quest: Follow Hanko LinkedIn Page ( 50 points)
![Screenshot_20241011_211854](https://github.com/user-attachments/assets/474d45a5-1157-4e57-b999-343f48a28c71)

Side Quest: Follow Hanko on X ( 50 points)
![Screenshot_20241011_211812](https://github.com/user-attachments/assets/b13e0351-76d8-43a2-b7db-8d38ba2802e0)

Total points - 400 points

**Comment by abdulrehmanwaseem** [comment]
![{2CD4089F-B194-4243-87F4-10BEE299C304}](https://github.com/user-attachments/assets/99246fa7-63ae-461c-99c2-3632ae75342d)

**Comment by abdulrehmanwaseem** [comment]
![WhatsApp Image 2024-10-11 at 21 26 00_e95c6350](https://github.com/user-attachments/assets/daa31595-29d7-4e2f-a171-dbaa29d48a2b)

**Comment by abdulrehmanwaseem** [comment]
<iframe src="https://giphy.com/embed/3orifaQEOagjYJ1EXe" width="480" height="362" style="" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/season-16-the-simpsons-16x7-3orifaQEOagjYJ1EXe">via GIPHY</a></p>

**Comment by abdulrehmanwaseem** [comment]
![gif-for-papermark](https://github.com/user-attachments/assets/94c8d221-16d0-49d3-bc2b-6c5682046713)

**Comment by abdulrehmanwaseem** [comment]
https://x.com/AbdulRehmanw_/status/1844782105823199349

**Comment by abdulrehmanwaseem** [comment]
![gif-for-papermark](https://github.com/user-attachments/assets/465523ce-9052-4417-9085-772c698fc4a8)

**Comment by abdulrehmanwaseem** [comment]
![giphy_2](https://github.com/user-attachments/assets/126e6593-aca6-482d-8661-0001ff4cc34e)

**Comment by mfts** [comment]
@Sahil-Gupta584 meme link does not lead anywhere.  Please submit it and i can award

@Ritesh2351235  @jitendrakumar025  @abdulrehmanwaseem   please open separate issues with all you completed, I can not reward you in the same issue.

**Comment by Sahil-Gupta584** [comment]
> @Sahil-Gupta584 meme link does not lead anywhere. Please submit it and i can award
> 
> @Ritesh2351235 @jitendrakumar025 @abdulrehmanwaseem please open separate issues with all you completed, I can not reward you in the same issue.

I have update X meme link now you can access it. And award points soon.

**Comment by abdulrehmanwaseem** [comment]
I have completed all the tasks this is the issue link: https://github.com/mfts/papermark/issues/790

**Comment by abdulrehmanwaseem** [comment]
> @Sahil-Gupta584 meme link does not lead anywhere. Please submit it and i can award
> 
> @Ritesh2351235 @jitendrakumar025 @abdulrehmanwaseem please open separate issues with all you completed, I can not reward you in the same issue.

:: I have completed all the tasks this is the issue link: https://github.com/mfts/papermark/issues/790 :: but still i haven't recieved points (if i did something wrong please tell me i am new to contributions i don't know how they acctually work)

**Comment by mfts** [comment]
/award 400 Thanks for participating!

more Papermark side quests here 👇
https://mfts.notion.site/Papermark-Hacktoberfest-Side-Quests-Challenges-111d3f870f008033935efe9f7702a3dc

everyone else pls open your own issue with proof of completing the quest : I can only award the author of an issue with points! You can combine number of no-code quests in one.
