### ISSUE TITLE
[🕹️]Follow Papermark Linkedin Account 

### ISSUE THREAD

**Issue by mitgajera** [mfts/papermark#769]
### What side quest or challenge are you solving?

Follow Papermark Linkedin Account

### Points

50

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/8a1dca4c-1202-45ec-9218-6af8dc4da8db)

**Comment by mfts** [comment]
/award 50 thanks! Happy to have you participate :)

more Papermark side quests here 👇
https://mfts.notion.site/Papermark-Hacktoberfest-Side-Quests-Challenges-111d3f870f008033935efe9f7702a3dc
