### ISSUE TITLE
[🕹️] New Papermark Logo

### ISSUE THREAD

**Issue by webdev-mohdamir** [mfts/papermark#770]
### What side quest or challenge are you solving?

#630

### Points

150

### Description

Hello @mfts, I have created this simple logo with a slightly rounded square and a stylized "P" inside it. The wordmark "Papermark" is placed below the logo.

Used font is Inter, colors are #242424 and #131313 for the logo and #000000 for the text.

### Provide proof that you've completed the task

![papermark_logo](https://github.com/user-attachments/assets/b5b6571d-fe07-48c0-a63b-115fdf718ac1)

![papermark_logo_black](https://github.com/user-attachments/assets/abe3a25c-ad87-42a3-81b4-351a398625b5)

**Comment by mfts** [comment]
@webdev-mohdamir  there is error in the logo. the correct name of company is Papermark 

@harshavardhan1726 to create alos logo just open new issue and submit proof that. you made logo

**Comment by webdev-mohdamir** [comment]
Sorry I didn't see that.

here are the corrected versions @mfts :

![papermark_logo_black](https://github.com/user-attachments/assets/532fd10d-751f-46ca-9d4f-b63e131ae8c7)
![papermark_logo](https://github.com/user-attachments/assets/2a9c7792-594a-4e7a-8360-bc108600ead3)

**Comment by mfts** [comment]
/award 150 

Thanks for the logo :)
