### ISSUE TITLE
[🕹️]Follow Papermark LinkedIn Page (50 Points):

### ISSUE THREAD

**Issue by Sam-at-code** [mfts/papermark#773]
### What side quest or challenge are you solving?

Follow [Papermark LinkedIn](https://linkedin.com/company/papermarkio) Page (50 Points):

### Points

50 points are assigned to this task

### Description

Followed Papermark's LinkdeIn Page and liked the launch post

### Provide proof that you've completed the task

![Screenshot 2024-10-12 001020](https://github.com/user-attachments/assets/32846786-82f7-4fc6-8456-4f040f898db6)
![Screenshot 2024-10-12 001052](https://github.com/user-attachments/assets/8dd17504-a735-43c8-b281-262daad22948)

**Comment by AndrewHamal** [comment]
<img width="1470" alt="Screenshot 2024-10-12 at 12 39 30 AM" src="https://github.com/user-attachments/assets/21d72181-577e-442f-9e59-f1bf9c420a07">
<img width="1470" alt="Screenshot 2024-10-12 at 12 40 35 AM" src="https://github.com/user-attachments/assets/02f13e9c-45c7-4c2f-9f46-74e6ff5176fb">

**Comment by mfts** [comment]
### to the author of the issue:

/award 50 thanks! Happy to have you participate :)

### to every one else commenting: pls open your own issue with proof of completing the quest @AndrewHamal @jitendrakumar025 

please open your own issues with your submissions. I can only award the author of an issue with points!

### more Papermark side quests here 👇
https://mfts.notion.site/Papermark-Hacktoberfest-Side-Quests-Challenges-111d3f870f008033935efe9f7702a3dc
