### ISSUE TITLE
[🕹️]Retweet and like side questFollow Papermark X (Twitter) Account (50 Points):

### ISSUE THREAD

**Issue by HimanshuGaur14** [mfts/papermark#774]
### What side quest or challenge are you solving?

I liked the official oss.gg launch [post](https://x.com/ossgoodgame/status/1841019549183066552) on X and retweeted it.

### Points

50

### Description

 I liked and retweet on the launch post that I'm competing.

### Provide proof that you've completed the task

<img width="356" alt="oss2" src="https://github.com/user-attachments/assets/1e892eaa-8eff-4243-a06c-03d1357b0858">

**Comment by draunger** [comment]
@mfts what I have to do?

**Comment by mfts** [comment]
### to the author of the issue:

/award 50 thanks! Happy to have you participate :)

### to every one else commenting: pls open your own issue with proof of completing the quest :

please open your own issues with your submissions. I can only award the author of an issue with points!

### more Papermark side quests here 👇
https://mfts.notion.site/Papermark-Hacktoberfest-Side-Quests-Challenges-111d3f870f008033935efe9f7702a3dc
