### ISSUE TITLE
[🕹️] Spread the word (50 per influencer, max. 3 influencers)

### ISSUE THREAD

**Issue by antilpiyush89** [mfts/papermark#776]
### What side quest or challenge are you solving?

Spread the word (50 per influencer, max. 3 influencers)

### Points

150 points, 50 per influencer

### Description

Commented on 3 influencer channels about oss.gg hackathon that they should cover this topic in their upcoming videos

### Provide proof that you've completed the task

![Screenshot 2024-10-12 030610](https://github.com/user-attachments/assets/ecb5f300-48eb-4b37-8ba0-d1059edc6346)
![Screenshot 2024-10-12 030729](https://github.com/user-attachments/assets/396968d1-1fe4-4a35-81a5-1f9994a02ba2)
![Screenshot 2024-10-12 030816](https://github.com/user-attachments/assets/a462ea4c-0287-4e3b-b3ff-92122fc87c75)

**Comment by ishsarin** [comment]
![image](https://github.com/user-attachments/assets/f83f5d01-1772-4605-99bb-254269312f2e)
![image](https://github.com/user-attachments/assets/859d7914-7910-4f3d-bbba-0db19068eed5)
![image](https://github.com/user-attachments/assets/8a97c3da-3325-4292-ace8-9fb7a449b8e1)

**Comment by mfts** [comment]
@ishsarin  @antilpiyush89  please the issues related to oss.gg submit to Formbricks repo https://github.com/formbricks/formbricks/issues
