### ISSUE TITLE
[🕹️]Design our new Papermark logo (150 Points per logo, 750 for the winner): 

### ISSUE THREAD

**Issue by Sam-at-code** [mfts/papermark#781]
### What side quest or challenge are you solving?

Designing a new logo for Papermark

### Points

150 points assigned for submission
750 points assigned for winning

### Description

I have created a logo for Papermark ensuring simplicity and the metioned colour pallete

### Provide proof that you've completed the task

![Dark Theme](https://github.com/user-attachments/assets/0388e1a6-6d69-4c09-a7f5-28e6b73136a3)
![Light Theme](https://github.com/user-attachments/assets/1d6c1aaf-b304-47fe-a6b9-c1a92b6da9b3)

**Comment by mfts** [comment]
Thanks for completing it. Your logo will take part in the public voting for best logo

**Comment by Anky9972** [comment]
![logo2](https://github.com/user-attachments/assets/4cbd9caf-fa5c-4702-9d77-6ff81a208d06)

**Comment by mfts** [comment]
@Anky9972 please open separate issue and sibmit logo there that i can award you there.

**Comment by Sam-at-code** [comment]
> Thanks for completing it. Your logo will take part in the public voting for best logo

Thanks for the opportunity. Glad to participate
