### ISSUE TITLE
[🕹️]Design new Papermark logo (150 Points per logo, 750 for the winner)

### ISSUE THREAD

**Issue by Anky9972** [mfts/papermark#782]
### What side quest or challenge are you solving?

Designing a new logo for Papermark.

### Points

150 points assigned for submission.
750 points assigned for winning.

### Description

I have create a logo for Papermark.

### Provide proof that you've completed the task

![logo2](https://github.com/user-attachments/assets/16ebcca3-421e-4c4d-8a10-86c9f10dcf52)
![logo3](https://github.com/user-attachments/assets/32a13495-d72b-430c-8d7f-29de5cbefe80)

**Comment by Anky9972** [comment]
@mfts  will i get the points for this side quest challenge?

**Comment by mfts** [comment]
/award 150 Thanks for creating a logo!

more Papermark side quests here 👇
https://mfts.notion.site/Papermark-Hacktoberfest-Side-Quests-Challenges-111d3f870f008033935efe9f7702a3dc

@suraj-xd  @heygogu   pls open your own issue with proof of completing the quest : I can only award the author of an issue with points! You can combine number of no-code quests in one.
