### ISSUE TITLE
[🕹️]Design new Papermark logo  #782 (submission)

### ISSUE THREAD

**Issue by heygogu** [mfts/papermark#784]
### What side quest or challenge are you solving?

Designing a new logo for papermark

### Points

150 assigned for submission
750 assigned for winning

### Description

I have created a logo for papermark

### Provide proof that you've completed the task

![papermark](https://github.com/user-attachments/assets/16fd84e7-3367-43f5-8e6b-2e12b1e95438)

**Comment by mfts** [comment]
/award 150 Thanks for deisgning logo! Looks cool! It will take part in public voting

more Papermark side quests here 👇
https://mfts.notion.site/Papermark-Hacktoberfest-Side-Quests-Challenges-111d3f870f008033935efe9f7702a3dc

@ambesh333  @TechWithAkash @Shanu-Sharma22   pls open your own issue with proof of completing the quest : I can only award the author of an issue with points! You can combine number of no-code quests in one.
