### ISSUE TITLE
[🕹️] Export document views to CSV

### ISSUE THREAD

**Issue by mfts** [mfts/papermark#786]
### What side quest or challenge are you solving?

Add an export function to download the document views to CSV by expanding the "..." button on the document detail page and select "Export visits".

It should trigger a direct download of a CSV file with the following content related to the visitor and visit:

- Viewed at
- Name (if available)
- Email (if available)
- Link Name
- Total Visit Duration
- % (Visit) Completion
- Document version
- Downloaded at
- Verified (if available)

The download file should be named after the document name and current timestamp e.g. `presentation-pdf_visits_2024-10-12_14-30.csv` or whatever makes more sense :)

### Points

750 Points

### Provide proof that you've completed the task

Open a PR with working code and explanation what you did. As well as a quick video showing the solution

**Comment by Pa04rth** [comment]
Hey @mfts ,did you want Export visits under this Action drop down list ?
![image](https://github.com/user-attachments/assets/8cede765-c3fd-4b1a-9e3e-fe3343d0484d)
I can do it ,if you reassign it to me

**Comment by mfts** [comment]
No, the export visits action should be under the document detail page.

**Comment by Pa04rth** [comment]
Ok

**Comment by Pa04rth** [comment]
Hey @mfts ,I need to ask a simple question ,when we setup papermark locally ,how we will get the .env credentials as even .envexample is empty

**Comment by mfts** [comment]
@Pa04rth You need to set up a postgres instance. Either hosted or local or via docker. That'll give you the connection string. 

You can either set up a blob storage on aws s3, vercel or minio (via docker) to get the file storage env variables. 

For emails you can use resend to set up an account there but it also works without emails

**Comment by aryany9** [comment]
Hey @mfts, Have completed the given assignment. Let me know if incase I missed anything. Thankyou for providing me the opportunity to contribute.
