### ISSUE TITLE
[🕹️] Submission For oss.gg Multiple Quests Submission (400 Point) #767

### ISSUE THREAD

**Issue by abdulrehmanwaseem** [mfts/papermark#790]
### Side quest and challenge i am solving!

1. Follow [Papermark LinkedIn](https://linkedin.com/company/papermarkio) Page (50 Points):
2. Follow Papermark X (Twitter) Account (50 Points)
3. Gif Magic (150 Points)
4. Meme Magic (150 Points)

### Points

400

### Provide proof that you've completed the task

1. Follow [Papermark LinkedIn](https://linkedin.com/company/papermarkio) Page (50 Points):
![Screenshot 2024-10-11 212343](https://github.com/user-attachments/assets/811399fa-876b-49ff-8ccd-6cc46d1b5e8d)

2. Follow Papermark X (Twitter) Account (50 Points):
![WhatsApp Image 2024-10-11 at 21 25 59_62464843](https://github.com/user-attachments/assets/2f94a4df-ba2a-470c-a74e-ec514acfc26f)

3. Gif Magic (150 Points):
https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExZnptdDVhcnZ1ZWJtd2ttMHd3ZXVibmp0bmV6azdwMWR2cTA3cXpodiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/IxgXIhNXsakFpr3Qxz/giphy.gif

4. Meme Magic (150 Points):
https://x.com/AbdulRehmanw_/status/1844782105823199349

**Comment by vishaljoshi789** [comment]
How can i show the proof of the task should I upload it here?

**Comment by vishaljoshi789** [comment]
The meme magic point is not visible 
<img width="1680" alt="image" src="https://github.com/user-attachments/assets/5ed7fa32-0d3a-4406-88e4-051be982d990">

**Comment by mfts** [comment]
/award 400 Thanks for participating! Awesome GIF! 

more Papermark side quests here 👇
https://mfts.notion.site/Papermark-Hacktoberfest-Side-Quests-Challenges-111d3f870f008033935efe9f7702a3dc

@TechWithAkash  @Shanu-Sharma22  pls open your own issue with proof of completing the quest : I can only award the author of an issue with points! You can combine number of no-code quests in one.
