### ISSUE TITLE
[🕹️] Support dark mode in Notion page view

### ISSUE THREAD

**Issue by mfts** [mfts/papermark#791]
### What side quest or challenge are you solving?

Papermark supports sharing Notion pages. 

Sometimes, Notion pages are default dark mode and the users who shares a Notion page via Papermark wants to keep that color scheme. 

We are using `react-notion-x` to parse and visualize Notion pages. Currently we hard-coded the color-scheme to light mode. 
https://github.com/mfts/papermark/blob/80299d2906ff6421d59292c4f95c7a24f0ab27a8/components/NotionPage.tsx#L315

However, I believe there should be a setting to make this whatever the original Notion page is. 

### Points

150 Points

### Provide proof that you've completed the task

Open a PR with the working code and a short video showing the original notion page and the notion page on Papermark that shows that it persists the color-scheme (light or dark) based on the Notion page's original setting

**Comment by DeepaPrasanna** [comment]
Hello @mfts , It seems the ability to change color schemes is available for paid notion users. It might be difficult to change color schemes of the notion page and test out

**Comment by DeepaPrasanna** [comment]
Hello @mfts , It seems the ability to change the color scheme of the public notion doc is for paid users. It might be hard to test that locally.

**Comment by mfts** [comment]
@DeepaPrasanna you are right. Also there's currently no way to retrieve that from `react-notion-x`. However, it would be cool to perhaps add a `?mode=dark|light` at the end of the notion page link and then once we parse it we can assign the `darkMode = true|false` in the NotionPage.tsx

What do you think?

**Comment by DeepaPrasanna** [comment]
> @DeepaPrasanna you are right. Also there's currently no way to retrieve that from `react-notion-x`.
> 
> However, it would be cool to perhaps add a `?mode=dark|light` at the end of the notion page link and then once we parse it we can assign the `darkMode = true|false` in the NotionPage.tsx
> 
> What do you think?

That seems like a cool idea. Do you want the users to specify that while adding the link, or should we try to read it from the Notion page itself? I'm not sure if the latter is possible.

**Comment by DeepaPrasanna** [comment]
hello @mfts , this is unrelated and I have no way of contacting u, I am informing you here in order to avoid any attention drawn towards me. There is an issue created by a spam user with a spam content. Pls block that user. you can find the issue created by this user [nandibholeseo](https://github.com/nandibholeseo)

**Comment by mfts** [comment]
@DeepaPrasanna I'd keep the navbar in the color as is. The user can change it in branding anyways. 

Let's just apply the dark mode

**Comment by mfts** [comment]
@DeepaPrasanna are you still working on this issue?

**Comment by DeepaPrasanna** [comment]
Yes! I had some appointments to do, so that's why I was unable to work on this. I will create a PR latest by tomorrow.
