### ISSUE TITLE
[🕹️] oss.gg hack submission 🕹️

### ISSUE THREAD

**Issue by abdulrehmanwaseem** [mfts/papermark#793]
### What side quest or challenge are you solving?

Followed Papermark LinkedIn

### Points

50

### Provide proof that you've completed the task

![Screenshot 2024-10-11 212343](https://github.com/user-attachments/assets/ea6f57db-38fb-4e49-9035-3fa9c4efd8a7)

**Comment by mfts** [comment]
@abdulrehmanwaseem I already awarded in 795

**Comment by triggeredcode** [comment]
@mfts should i remove myself then ?

**Comment by mfts** [comment]
/award 50 

Thanks for the support and participation! 

---

Everyone else please open your own issue if you followed Papermark (@triggeredcode)
