### ISSUE TITLE
Meme Magic Submission 🕹️

### ISSUE THREAD

**Issue by abdulrehmanwaseem** [mfts/papermark#794]
### What side quest or challenge are you solving?

Meme Magic (150 points)

### Points

150

### Description

I created a meme comparing old-school paper use to the new digital solution, Papermark.

### Provide proof that you've completed the task

https://x.com/AbdulRehmanw_/status/1844782105823199349

**Comment by mfts** [comment]
@abdulrehmanwaseem the link is not visible

**Comment by mfts** [comment]
@abdulrehmanwaseem just a reminder that the link is not working. please share a working link to get a reward

**Comment by abdulrehmanwaseem** [comment]
> @abdulrehmanwaseem just a reminder that the link is not working. please share a working link to get a reward

It's Working For Me Fine? Try again: https://x.com/AbdulRehmanw_/status/1844782105823199349?s=19

**Comment by JeevaRamanathan** [comment]
Hi @abdulrehmanwaseem, it seems to be you have limited your post only to your followers (https://x.com/settings/audience_and_tagging). So it's not seeable.

**Comment by mfts** [comment]
![CleanShot 2024-10-19 at 17 29 38@2x](https://github.com/user-attachments/assets/161a2791-dcb9-426a-977b-e01ca95c3fe2)
@abdulrehmanwaseem doesn't work.
