### ISSUE TITLE
[🕹️] Follow Papermark X (Twitter) Account

### ISSUE THREAD

**Issue by abdulrehmanwaseem** [mfts/papermark#795]
### What side quest or challenge are you solving?

Followed Papermark X (Twitter) Account (50 Points)

### Points

50

### Provide proof that you've completed the task

![WhatsApp Image 2024-10-11 at 21 26 00_4c321818](https://github.com/user-attachments/assets/9bcf38ec-3526-4b74-ba12-848aea6a0085)

**Comment by mfts** [comment]
/award 50 Thanks for participating!

more Papermark side quests here 👇
https://mfts.notion.site/Papermark-Hacktoberfest-Side-Quests-Challenges-111d3f870f008033935efe9f7702a3dc

@hirendhola @TechWithAkash  pls open your own issue with proof of completing the quest : I can only award the author of an issue with points! You can combine number of no-code quests in one.
