### ISSUE TITLE
[🕹️] Gif Magic (150 Points)

### ISSUE THREAD

**Issue by abdulrehmanwaseem** [mfts/papermark#796]
### What side quest or challenge are you solving?

Gif Magic (150 Points)

### Points

150

### Provide proof that you've completed the task

https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExZnptdDVhcnZ1ZWJtd2ttMHd3ZXVibmp0bmV6azdwMWR2cTA3cXpodiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/IxgXIhNXsakFpr3Qxz/giphy.gif

**Comment by mfts** [comment]
Awarded in 795 issue already. @abdulrehmanwaseem
