### ISSUE TITLE
[🕹️]Starry-eyed Supporter

### ISSUE THREAD

**Issue by Ionfinisher** [mfts/papermark#797]
### What side quest or challenge are you solving?

Asked for 5 friends to star the papermark repo

### Points

150

### Description

Ask them to star and provide screenshots with their usernames

### Provide proof that you've completed the task

1. Username: https://github.com/gh05t-me 
<img width="836" alt="Screen Shot 2024-10-12 at 07 00 56" src="https://github.com/user-attachments/assets/a27a2cf4-e49d-4b2f-bf8b-7251ab612e29">

![WhatsApp Image 2024-10-10 at 22 58 16](https://github.com/user-attachments/assets/d42e0065-8b68-436f-b509-d5426bd5c9fb)

2. Username: https://github.com/nongande
<img width="836" alt="Screen Shot 2024-10-12 at 07 06 49" src="https://github.com/user-attachments/assets/c3594f90-c160-4c0d-b1a8-dc2a6fd619c6">

![WhatsApp Image 2024-10-10 at 22 29 02](https://github.com/user-attachments/assets/96f335b3-4c3c-46c7-82f0-c709db8a577c)

3. Username: https://github.com/OziasKOUYA
<img width="836" alt="Screen Shot 2024-10-12 at 07 09 07" src="https://github.com/user-attachments/assets/b5f871f5-fc91-4f35-8eba-e38f5902ebac">

![WhatsApp Image 2024-10-11 at 09 28 45](https://github.com/user-attachments/assets/e5679616-c59b-45a2-a291-28bc5bce5b24)

4. Username: https://github.com/agodaMarina
<img width="836" alt="Screen Shot 2024-10-12 at 07 10 37" src="https://github.com/user-attachments/assets/dea25b1c-2ee3-47c6-be43-82d5f5f2a5aa">

![WhatsApp Image 2024-10-11 at 13 48 24](https://github.com/user-attachments/assets/ea72f5ea-9311-4b50-a0d2-b39ea4000d3f)

5. Username: https://github.com/Le64
<img width="836" alt="Screen Shot 2024-10-12 at 07 15 58" src="https://github.com/user-attachments/assets/c87d0b43-64cf-4ec1-90ab-3511a815236c">

![WhatsApp Image 2024-10-10 at 23 28 31](https://github.com/user-attachments/assets/f05d3a37-6679-4b0b-abff-0a4057a8e8aa)

### PLEASE NO NEED TO ASSIGN YOURSELF THIS ISSUE. THIS IS MY PLAYER SUBMISSION. THANKS

**Comment by mfts** [comment]
/award 150 

Thanks for reaching out to your friends :)
