### ISSUE TITLE
[🕹️] Followed Papermark on YouTube (50 Points) 

### ISSUE THREAD

**Issue by dexterousdhruv** [mfts/papermark#799]
### What side quest or challenge are you solving?

Papermark now has a Youtube channel.  See #792

### Points

50

### Description

Subscribed the papermark channel on  youtube.

### Provide proof that you've completed the task

![Screenshot 2024-10-12 131417](https://github.com/user-attachments/assets/c3242e2f-3c97-4ef8-aae5-384874bb24d5)

**Comment by mfts** [comment]
/award 50 

Thanks for the support and participation!
