### ISSUE TITLE
[🕹️] Follow Papermark X (Twitter) Account

### ISSUE THREAD

**Issue by mohdjami** [mfts/papermark#800]
### What side quest or challenge are you solving?

Solving a Papermark side quest : Follow Papermark X(Twitter) Account

### Points

50

### Description

Followed the Twitter(X) page of Papermark

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/94dfa32d-72bf-44c5-b655-27b8b9d61710)

**Comment by mfts** [comment]
/award 50 Thanks for participating!

more Papermark side quests here 👇
https://mfts.notion.site/Papermark-Hacktoberfest-Side-Quests-Challenges-111d3f870f008033935efe9f7702a3dc

@Pranavx1   pls open your own issue with proof of completing the quest : I can only award the author of an issue with points! You can combine number of no-code quests in one.
