### ISSUE TITLE
[🕹️] Follow Papermark on YouTube (50 points)

### ISSUE THREAD

**Issue by vamsi4845** [mfts/papermark#801]
### What side quest or challenge are you solving?

What side quest or challenge are you solving?
Papermark now has a Youtube channel. See https://github.com/mfts/papermark/issues/792

### Points

50

### Description

Subscribed to the Papermark channel on YouTube.
to 

### Provide proof that you've completed the task

https://www.youtube.com/@papermarkio/videos
![image](https://github.com/user-attachments/assets/0ad2bbe1-a65d-47fb-ba8d-cbb61cc7eb34)

**Comment by Omvpatil** [comment]
![Screenshot 2024-10-12 141021](https://github.com/user-attachments/assets/307bd46b-5082-4154-a748-ca1e42c51dd4)

**Comment by muhammadhaad** [comment]
![Screenshot 2024-10-12 at 1 48 12 PM](https://github.com/user-attachments/assets/55480f9c-64d0-43ce-869f-b5cd35d5632d)
Done

**Comment by VivekSite** [comment]
<img width="1380" alt="Screenshot 2024-10-12 at 2 56 09 PM" src="https://github.com/user-attachments/assets/74d70d0c-0909-4906-9e7e-7e4993fb436b">

**Comment by shnai0** [comment]
### Please create separate issue, one issue one person can be awarded. Don't assign it in here. 

@VivekSite  @muhammadhaad @Omvpatil

**Comment by VivekSite** [comment]
Ok, so I have to create a new issue for this same task.
And, do I have to create a PR to complete this task?

**Comment by Harsh9485** [comment]
hello @shnai() 
ok I understand this side quest create new issue but where is side quest 
plz give me a link for this quests

**Comment by vamsi4845** [comment]
> Ok, so I have to create a new issue for this same task.
> And, do I have to create a PR to complete this task?
> 
> @shnai0 

I think its issue only as this is a no code contribution

**Comment by mfts** [comment]
/award 50 Thanks for participating!

more Papermark side quests here 👇
https://mfts.notion.site/Papermark-Hacktoberfest-Side-Quests-Challenges-111d3f870f008033935efe9f7702a3dc

@Nithin-532 @VivekSite @Omvpatil   pls open your own issue with proof of completing the quest , if not yet: I can only award the author of an issue with points! You can combine number of no-code quests in one.
