### ISSUE TITLE
[🕹️]Follow Papermark on YouTube (50 points)

### ISSUE THREAD

**Issue by muhammadhaad** [mfts/papermark#803]
### What side quest or challenge are you solving?

What side quest or challenge are you solving?
Papermark now has a Youtube channel. See https://github.com/mfts/papermark/issues/792

### Points

50

### Description

Subscribed to the Papermark channel on YouTube.
to
https://www.youtube.com/@papermarkio/videos

### Provide proof that you've completed the task

![Screenshot 2024-10-12 at 1 48 12 PM](https://github.com/user-attachments/assets/65995bd7-8c88-4495-b4ee-c3b8551b2370)

**Comment by shnai0** [comment]
@tushar-agarwal7 Please create separate issue, one issue one person can be awarded. Don't assign it in here.

**Comment by mfts** [comment]
/award 50 Thanks for participating!

more Papermark side quests here 👇
https://mfts.notion.site/Papermark-Hacktoberfest-Side-Quests-Challenges-111d3f870f008033935efe9f7702a3dc

@tushar-agarwal7   pls open your own issue with proof of completing the quest : I can only award the author of an issue with points! You can combine number of no-code quests in one.
