### ISSUE TITLE
[🕹️]Follow Papermark on YouTube (50 points) 

### ISSUE THREAD

**Issue by milanp19** [mfts/papermark#804]
### What side quest or challenge are you solving?

Papermark now has a Youtube channel. See https://github.com/mfts/papermark/issues/792

### Points

50

### Description

Subscribed to papermark youtube account

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/bfb7baef-8adb-46dd-a315-0c446aaca8d0)

**Comment by mfts** [comment]
/award 50 Thanks for participating!

more Papermark side quests here 👇
https://mfts.notion.site/Papermark-Hacktoberfest-Side-Quests-Challenges-111d3f870f008033935efe9f7702a3dc

@manishkumar123456 @Luna7282   pls open your own issue with proof of completing the quest : I can only award the author of an issue with points! You can combine number of no-code quests in one.
