### ISSUE TITLE
[🕹️]Design new Papermark logo 

### ISSUE THREAD

**Issue by FelixFelicis99** [mfts/papermark#805]
### What side quest or challenge are you solving?

designed a new papermark logo 

### Points

150 Points per logo, 750 for the winner

### Description

looks like this:
![image](https://github.com/user-attachments/assets/a3fa7438-4122-490f-bb80-3b2d03209bed)
![image](https://github.com/user-attachments/assets/d94d901b-330b-4539-bbf6-c66c0a8a3f9c)

### Provide proof that you've completed the task

logo design:
![logofinal](https://github.com/user-attachments/assets/d5da9818-bf50-44c4-b4a2-37454d83cd04)

**Comment by mfts** [comment]
/award 150 Thanks for participating!

more Papermark side quests here 👇
https://mfts.notion.site/Papermark-Hacktoberfest-Side-Quests-Challenges-111d3f870f008033935efe9f7702a3dc

@Mohit081 1  pls open your own issue with proof of completing the quest : I can only award the author of an issue with points! You can combine number of no-code quests in one.
