### ISSUE TITLE
[🕹️]Design new Papermark logo

### ISSUE THREAD

**Issue by milanp19** [mfts/papermark#807]
### What side quest or challenge are you solving?

Design new Papermark logo

### Points

150 Points per logo, 750 for the winner

### Description

Designed papermark logo

### Provide proof that you've completed the task

![logo](https://github.com/user-attachments/assets/0d8baf99-9eb5-4f9c-a04e-21288166d67b)

**Comment by mfts** [comment]
/award 150 Thanks for participating!

more Papermark side quests here 👇
https://mfts.notion.site/Papermark-Hacktoberfest-Side-Quests-Challenges-111d3f870f008033935efe9f7702a3dc
