### ISSUE TITLE
[🕹️] Follow Papermark on Twitter(X)

### ISSUE THREAD

**Issue by Suryadev78** [mfts/papermark#808]
### What side quest or challenge are you solving?

Follow Papermark on Twitter

### Points

50

### Description

Followed papermark on twitter

### Provide proof that you've completed the task

Here's the proof - 
![image](https://github.com/user-attachments/assets/730aec11-212f-493a-a006-a2af1b3417db)

**Comment by mfts** [comment]
/award 50 Thanks for participating!

more Papermark side quests here 👇
https://mfts.notion.site/Papermark-Hacktoberfest-Side-Quests-Challenges-111d3f870f008033935efe9f7702a3dc

@tosif121  pls open your own issue with proof of completing the quest : I can only award the author of an issue with points! You can combine number of no-code quests in one.
