### ISSUE TITLE
[🕹️]Follow Papermark on LinkedIn

### ISSUE THREAD

**Issue by Suryadev78** [mfts/papermark#809]
### What side quest or challenge are you solving?

Follow papermark on linkedin

### Points

50

### Description

Followed papermark on linkdein

### Provide proof that you've completed the task

Here's the proof - 
![image](https://github.com/user-attachments/assets/b7019bb6-0e8b-4049-b35e-223f01dc9a18)

**Comment by mfts** [comment]
/award 50 Thanks for participating!

more Papermark side quests here 👇
https://mfts.notion.site/Papermark-Hacktoberfest-Side-Quests-Challenges-111d3f870f008033935efe9f7702a3dc

@Fz-Faiz  @Karankhatik  @tosif121  pls open your own issue with proof of completing the quest : I can only award the author of an issue with points! You can combine number of no-code quests in one.
