### ISSUE TITLE
[🕹️] New logo for PaperMark

### ISSUE THREAD

**Issue by Suryadev78** [mfts/papermark#811]
### What side quest or challenge are you solving?

Design a new logo for papermark

### Points

150 per logo ,750 for winner

### Description

Created a simple, square and ideally black and white logo for Papermark

### Provide proof that you've completed the task

Here's the proof - 

![Papermark-logo](https://github.com/user-attachments/assets/7cb7aa61-364a-4a1c-a9ea-68b50f81795c)

**Comment by mfts** [comment]
/award 150 Cool logo!

more Papermark side quests here 👇
https://mfts.notion.site/Papermark-Hacktoberfest-Side-Quests-Challenges-111d3f870f008033935efe9f7702a3dc

@Hasnain-Memon   pls open your own issue with proof of completing the quest : I can only award the author of an issue with points! You can combine number of no-code quests in one.
