### ISSUE TITLE
[🕹️] Add "report" button to document viewer to report abuse

### ISSUE THREAD

**Issue by mfts** [mfts/papermark#812]
### What side quest or challenge are you solving?

Add a button to the viewer navbar that let's visitors report abuse on any document or dataroom. 

Once the button is pressed, it should send the documentId, viewId, and linkId to a redis bucket. 
Therefore, we can count the amount of reports on a given document/link, only allow a viewId to report once. 

There should be a small action panel to select what type of abuse it is 

```
What kind of issue is it?
- Spam, Fraud, or Scam
- Malware or virus
- Copyright violation
- Harmful content
- Content is not working properly
- Other
```

![CleanShot 2024-10-12 at 19 28 08@2x](https://github.com/user-attachments/assets/01342315-c5a8-45e8-802f-4e68f82c8c98)

### Points

750 Points

### Provide proof that you've completed the task

Open a PR with the working code and a short video showing the solution

**Comment by Khaan25** [comment]
@mfts, If for whatever reason RajuGangitla isn't able todo it, please assign it to me.

**Comment by RajuGangitla** [comment]
@mfts is there any dicord channel to discuss this issue

**Comment by mfts** [comment]
@RajuGangitla what would you like to discuss? please use this thread here :)

**Comment by RajuGangitla** [comment]
@mfts

**Comment by mfts** [comment]
@RajuGangitla You don't need Stripe or S3 for it. Redis yes, but upstash let's you create a free account, alternatively you can also connect to a redis instance locally in docker. 

You can test the viewer with a public notion link like this: https://mfts.notion.site/Papermark-Hacktoberfest-Side-Quests-Challenges-111d3f870f008033935efe9f7702a3dc

**Comment by RajuGangitla** [comment]
@mfts how can I get the viewers 
I need to invite someone to my team for that it's asking plan

**Comment by mfts** [comment]
@RajuGangitla But why do you need to invite someone to the team for solving this issue? 

Also locally you can just change your account to any plan.

**Comment by RajuGangitla** [comment]
![image](https://github.com/user-attachments/assets/8e4da989-bd30-416b-ab9f-1faac5dc9e31)

**Comment by RajuGangitla** [comment]
@mfts

**Comment by mfts** [comment]
@RajuGangitla just update the team plan in your local database. Or delete the account and create a fresh account locally. you don't need stripe for this task

**Comment by RajuGangitla** [comment]
@mfts even though i added the usptash credentials still its throwing this error any idea how to solve this one 

![image](https://github.com/user-attachments/assets/df55d3ae-f676-4426-86dd-5607904b9339)

**Comment by RajuGangitla** [comment]
@mfts  i implemented the functionality on the notion docs can you confirm me if i am going in right direction i will raise pr 

[screen-capture (19).webm](https://github.com/user-attachments/assets/3cdd48a4-a3fd-4d44-8347-6c971a3b0c75)

**Comment by mfts** [comment]
@RajuGangitla wow that looks perfect! 

> do i need to store the reason for reporting also

yes, but let's give it a enum or number so that storing it is simpler 

> While creating link, do we give option to toggle report button

no


please open a PR so I can review the implementation :)
