### ISSUE TITLE
[Help] Unable to Initialize the database locally

### ISSUE THREAD

**Issue by JeevaRamanathan** [mfts/papermark#817]
A postgres database has been created in Vercel storage in a new project. 
`POSTGRES_PRISMA_URL` and `POSTGRES_PRISMA_URL_NON_POOLING` env is set based on the generated values in vercel by replacing `verceldb` to created database name.
![image](https://github.com/user-attachments/assets/5a3722f0-dc37-47aa-bfd7-d589fd4f73cd)

The status is available in database.

on running `npm run dev:prisma`  the following error is received. 
```
Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma
Datasource "db": PostgreSQL database "github-ai-pr-tracker-postgres", schema "public" at "ep-tight-mountain-a4labwa2.us-east-1.aws.neon.tech:5432"

Error: P1001: Can't reach database server at `ep-tight-mountain-a4labwa2.us-east-1.aws.neon.tech:5432`

Please make sure your database server is running at `ep-tight-mountain-a4labwa2.us-east-1.aws.neon.tech:5432`.
```

Attempted multiple ways but didn't help. Any help on this is appreciated.

**Comment by PaulDesigne** [comment]
have same problem

**Comment by JeevaRamanathan** [comment]
@PaulDesigne  This worked for me.  i) I was replacing the `verceldb` with the database name, but the URL has to be used as it is without changing from Vercel.
ii) Sometimes my Wi-Fi was causing connectivity issues, so I had to change my network.

**Comment by PaulDesigne** [comment]
@JeevaRamanathan Thanks for the reply. I've figured out my problem. My company's firewall was blocking it.
