### ISSUE TITLE
[🕹️] Followed papermark on twitter

### ISSUE THREAD

**Issue by dhanyamd** [mfts/papermark#818]
### What side quest or challenge are you solving?

followed papermark on 'X' platform

### Points

50

### Description

followed the official papermark page on X 

### Provide proof that you've completed the task

![pp](https://github.com/user-attachments/assets/3d4a7241-63d7-41f5-b5ed-063326291519)

**Comment by mfts** [comment]
/award 50 Thanks for participating!

more Papermark side quests here 👇
https://mfts.notion.site/Papermark-Hacktoberfest-Side-Quests-Challenges-111d3f870f008033935efe9f7702a3dc
