### ISSUE TITLE
[🕹️] Followed papermark on LinkedIn

### ISSUE THREAD

**Issue by dhanyamd** [mfts/papermark#819]
### What side quest or challenge are you solving?

followed papermark today on LinkedIn

### Points

50

### Description

following the official papermark page on LinkedIn

### Provide proof that you've completed the task

![pp2](https://github.com/user-attachments/assets/92c31ca5-a99d-4293-b7f1-f8c456cbec6d)

**Comment by durgeshbg** [comment]
Draft PR: #838

**Comment by mfts** [comment]
/award 50 Thanks for participating!

more Papermark side quests here 👇
https://mfts.notion.site/Papermark-Hacktoberfest-Side-Quests-Challenges-111d3f870f008033935efe9f7702a3dc

@durgeshbg  pls open your own issue with proof of completing the quest : I can only award the author of an issue with points!
