### ISSUE TITLE
[🕹️]Starry-eyed supporter

### ISSUE THREAD

**Issue by krbappy00** [mfts/papermark#821]
### What side quest or challenge are you solving?

1050 Points 🔥 Get 5 friends to star our repos, one of my friend give star to this repo

### Points

150

### Provide proof that you've completed the task

![9cd85112-94d4-463d-bf28-c744f277c968](https://github.com/user-attachments/assets/85dc85c9-709f-4988-8bf4-99c7b28baeab)

**Comment by mfts** [comment]
@krbappy00 i can see only one screenshot. please add 5 supporters :)

**Comment by mfts** [comment]
sorry cannot award you because missing information.
