### ISSUE TITLE
[🕹️]Design new Papermark logo #807

### ISSUE THREAD

**Issue by FaheemOnHub** [mfts/papermark#822]
### What side quest or challenge are you solving?

Design new Papermark logo

### Points

150 Points per logo, 750 for the winner

### Description

designed two logos for papermark

1. 
![Untitled1 design](https://github.com/user-attachments/assets/30481c30-8138-4e27-88e3-760acd3acd35)
The first one signifies that you can check analytics of your shared docs

2. 
![Untitled design](https://github.com/user-attachments/assets/6e3e2796-dff9-4574-be1a-30609314e6d3)
The second one signifies that you can easily share docs on the go

### Provide proof that you've completed the task

<img width="1440" alt="Screenshot 2024-10-12 at 5 53 13 PM" src="https://github.com/user-attachments/assets/510cdcbd-7212-418e-8082-aeb43134b39c">
<img width="1440" alt="Screenshot 2024-10-12 at 5 50 17 PM" src="https://github.com/user-attachments/assets/a1eb1cb6-5f1e-4001-a854-4ffd7eb92e04">

**Comment by mfts** [comment]
/award 150 Thanks for participating!

more Papermark side quests here 👇
https://mfts.notion.site/Papermark-Hacktoberfest-Side-Quests-Challenges-111d3f870f008033935efe9f7702a3dc

@Axdityxa  @tosif121 pls open your own issue with proof of completing the quest : I can only award the author of an issue with points!
