### ISSUE TITLE
[🕹️]Follow Papermark X (Twitter) Account

### ISSUE THREAD

**Issue by AnshMehta24** [mfts/papermark#828]
### What side quest or challenge are you solving?

![Screenshot 2024-10-12 191844](https://github.com/user-attachments/assets/c6c044f7-242b-439d-b56a-a859109a0319)

### Points

# 50

### Provide proof that you've completed the task

![Screenshot 2024-10-12 191844](https://github.com/user-attachments/assets/3053c038-b914-4a5d-a728-ea57a1d8fcee)

**Comment by mfts** [comment]
/award 50 Thanks for participating!

more Papermark side quests here 👇
https://mfts.notion.site/Papermark-Hacktoberfest-Side-Quests-Challenges-111d3f870f008033935efe9f7702a3dc

@Junaid-Shaukat  @yashksaini-coder @eyeaadil   if you not already, pls open your own issue with proof of completing the quest : I can only award the author of an issue with points!

**Comment by Junaid-Shaukat** [comment]
I have completed the task
