### ISSUE TITLE
[🕹️]Follow Papermark LinkedIn Page

### ISSUE THREAD

**Issue by AnshMehta24** [mfts/papermark#829]
### What side quest or challenge are you solving?

Follow [Papermark LinkedIn](https://linkedin.com/company/papermarkio) Page

### Points

# 50

### Description

Follow Papermark LinkedIn Page

### Provide proof that you've completed the task

![Screenshot 2024-10-12 192142](https://github.com/user-attachments/assets/0dc9f7ec-0588-4f80-92c7-0172f9f46683)

**Comment by mfts** [comment]
/award 50 Thanks for participating!

more Papermark side quests here 👇
https://mfts.notion.site/Papermark-Hacktoberfest-Side-Quests-Challenges-111d3f870f008033935efe9f7702a3dc

@eyeaadil @satyajitX001   if you not already, pls open your own issue with proof of completing the quest : I can only award the author of an issue with points!
