### ISSUE TITLE
[🕹️]Follow papermark LinkedIn Page

### ISSUE THREAD

**Issue by eyeaadil** [mfts/papermark#830]
### What side quest or challenge are you solving?

Follow LinkedIn page of papermark

### Points

50

### Description

Follow LinkedIn page of papermark

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/69a6b9be-19a0-4c77-a24d-6b7dac4501a1)

**Comment by mfts** [comment]
/award 50 Thanks for participating!

more Papermark side quests here 👇
https://mfts.notion.site/Papermark-Hacktoberfest-Side-Quests-Challenges-111d3f870f008033935efe9f7702a3dc

@manishkumar123456 @yashksaini-coder  if you not already, pls open your own issue with proof of completing the quest : I can only award the author of an issue with points!
