### ISSUE TITLE
[🕹️]Follow Papermark on Twitter(X)

### ISSUE THREAD

**Issue by sahiladit** [mfts/papermark#833]
### What side quest or challenge are you solving?

Followed Papermark on Twitter(X)

### Points

50

### Provide proof that you've completed the task

<img width="1440" alt="Screenshot 2024-10-12 at 8 25 21 PM" src="https://github.com/user-attachments/assets/602ba1bf-491b-4f6e-b096-dfb7fa9aaf5e">

**Comment by DorcasOpatola** [comment]
Hi @sahiladit , can you assign this task to me?

**Comment by sahiladit** [comment]
> Hi @sahiladit , can you assign this task to me?

its not an issue

**Comment by mfts** [comment]
/award 50 thanks! Thanks for participating.

more Papermark side quests here 👇
https://mfts.notion.site/Papermark-Hacktoberfest-Side-Quests-Challenges-111d3f870f008033935efe9f7702a3dc

@DorcasOpatola  @Sarthak32  if you not already, pls open your own issue with proof of completing the quest :
I can only award the author of an issue with points!
