### ISSUE TITLE
[🕹️]Follow papermark LinkedIn Page

### ISSUE THREAD

**Issue by sahiladit** [mfts/papermark#835]
### What side quest or challenge are you solving?

Followed papermark LinkedIn Page

### Points

50

### Provide proof that you've completed the task

<img width="1440" alt="Screenshot 2024-10-12 at 8 29 10 PM" src="https://github.com/user-attachments/assets/e90b8c76-833f-4493-b9c7-3ac5cb060c3f">

**Comment by Sarthak32** [comment]
![image](https://github.com/user-attachments/assets/c5800a8d-902b-4f4a-8f4c-0acca722f5ad)
done!

**Comment by mfts** [comment]
/award 50 thanks! Thanks for participating.

more Papermark side quests here 👇
https://mfts.notion.site/Papermark-Hacktoberfest-Side-Quests-Challenges-111d3f870f008033935efe9f7702a3dc

@Saurabh2312 @Sarthak32  if you not already, pls open your own issue with proof of completing the quest :
I can only award the author of an issue with points!
