### ISSUE TITLE
[🕹️]Bug:The tick marks should be at the centre of the box

### ISSUE THREAD

**Issue by sahiladit** [mfts/papermark#836]
### What side quest or challenge are you solving?

Accessibility Advocate

### Points

50

### Description

Open the Home page, scroll own a bit, you will see this table. The tick marks should be at the centre of the box.

### Provide proof that you've completed the task

<img width="1440" alt="Screenshot 2024-10-12 at 8 35 53 PM" src="https://github.com/user-attachments/assets/d7323ccd-32c6-48a6-b639-6e9ce9be3b31">

**Comment by ShreyasLakhani** [comment]
@sahiladit can you send the URL of the table.

**Comment by sahiladit** [comment]
> @sahiladit can you send the URL of the table.

Go to the Data Room page

**Comment by ShreyasLakhani** [comment]
@sahiladit do you know, where is located in file?

**Comment by career-yashaswee** [comment]
help me with navigating to the exact folder, where the papermark.io home-page is being hosted in the directory. As of now, i have got the application running on local-host with complete set-up. Not able to find, where the exact files to the home-page and it's sub-pages

**Comment by career-yashaswee** [comment]
I am unassigning myself from this issue, as I haven't received any clarifications the repo to the landing page  for papermark.io. I would love to work on some other issues.

**Comment by pnk-ltoc-892** [comment]
faced difficulty in locating the component in the CodeBase

**Comment by pnk-ltoc-892** [comment]
very unstructured and unclear routing

**Comment by sweets-11** [comment]
not able to navigate to this page
