### ISSUE TITLE
[🕹️]Bug: Last Login Indicator should display only after successful login or return to login screen

### ISSUE THREAD

**Issue by JeevaRamanathan** [mfts/papermark#841]
### What side quest or challenge are you solving?

Bug

### Points

W.r.t. Bug Hunter

### Description

Related to #718 / #707 
Currently last login indicator is displayed the moment it's clicked.

### Current Behaviour
https://github.com/user-attachments/assets/041cbdb5-dcde-4a4e-902e-68f2ab581d09

### Expected Behaviour
Last login indicator should be displayed on only when coming back to login screen after successful login or as in https://lex.page/

**Comment by sahiladit** [comment]
@mfts review the pull request.

**Comment by sahiladit** [comment]
@Sundaram-rathor one pr is already there for this issue.
