### ISSUE TITLE
[🕹️]Follow LinkedIn page of papermark

### ISSUE THREAD

**Issue by jitendrakumar025** [mfts/papermark#842]
### What side quest or challenge are you solving?

Follow papermark on linkedin

### Points

50

### Description

Follow papermark on linkedin 

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/59f9d2de-f236-4eab-871b-6afe8e9a19aa)

**Comment by mfts** [comment]
/award 50 thanks! Thanks for participating.

more Papermark side quests here 👇
https://mfts.notion.site/Papermark-Hacktoberfest-Side-Quests-Challenges-111d3f870f008033935efe9f7702a3dc

@abdulrehmanwaseem  if you not already, pls open your own issue with proof of completing the quest :
I can only award the author of an issue with points!
