### ISSUE TITLE
[🕹️]Follow Papermark on X (Twitter)

### ISSUE THREAD

**Issue by tushar110302** [mfts/papermark#844]
### What side quest or challenge are you solving?

Follow Papermark on Twitter(X)

### Points

50

### Description

Followed the Twitter(X) page of Papermark

### Provide proof that you've completed the task

<img width="1336" alt="Screenshot 2024-10-12 at 10 24 22 PM" src="https://github.com/user-attachments/assets/b529d023-9691-4b78-b4bf-b6521daa9fe7">

**Comment by Sakethpavan** [comment]
![image](https://github.com/user-attachments/assets/e792a997-967a-45e2-8465-57ec6427e0f7)

**Comment by mfts** [comment]
/award 50 thanks! Thanks for participating.

more Papermark side quests here 👇
https://mfts.notion.site/Papermark-Hacktoberfest-Side-Quests-Challenges-111d3f870f008033935efe9f7702a3dc

@Sakethpavan  if you not already, pls open your own issue with proof of completing the quest :
I can only award the author of an issue with points!
