### ISSUE TITLE
[🕹️]  Onboarding feedback video, YT side quest, Meme

### ISSUE THREAD

**Issue by harshsbhat** [mfts/papermark#847]
### What side quest or challenge are you solving?

1. Onboarding feedback video 300
2. YouTube Follow and LIke 50
3. Meme 150

### Points

500

### Description

Btw I was the first one to like and comment on the video.

### Provide proof that you've completed the task

Video:

https://www.loom.com/share/da406c46982e4332a45969de7c9d4120?sid=23e76a28-0cc3-48a7-8e39-ddba5e18a271

YouTube Follow:

![image](https://github.com/user-attachments/assets/94bb023a-0d30-4c7f-a8b0-678e573cc6a5)

Meme:

https://x.com/HarshBhatX/status/1844771307851751706

**Comment by harshsbhat** [comment]
why would you assign this? @Nithin-532 this is a submission for my sidequest

**Comment by Nithin-532** [comment]
Sorry man.

**Comment by mfts** [comment]
/award 500 

Thanks for the feedback and video!
