### ISSUE TITLE
[🕹️] Follow Papermark X (Twitter) 

### ISSUE THREAD

**Issue by heygogu** [mfts/papermark#852]
### What side quest or challenge are you solving?

Follow Papermark on X (Twitter) 

### Points

50

### Description

followed papermark on twitter and also liked and retweeted launch post

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/82f90587-05d7-43fd-b185-667cf0c49593)
![image](https://github.com/user-attachments/assets/efc402ec-85dd-48d2-8299-58ba7d505b49)

**Comment by heygogu** [comment]
This is my individual contribution . Do not comment / assign here as it wont benefit you either way

**Comment by mfts** [comment]
/award 50 thanks! Happy to have you participate :)

more Papermark side quests here 👇
https://mfts.notion.site/Papermark-Hacktoberfest-Side-Quests-Challenges-111d3f870f008033935efe9f7702a3dc
