### ISSUE TITLE
[🕹️] Follow Papermark LinkedIn

### ISSUE THREAD

**Issue by heygogu** [mfts/papermark#853]
### What side quest or challenge are you solving?

Follow Papermark on LinkedIn

### Points

50

### Description

Followed papermark on linkedin

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/cf4316c4-7f4b-452a-8e53-eba90eafaab1)

**Comment by Sumit1911** [comment]
![image](https://github.com/user-attachments/assets/4757e3d9-c210-40c2-8311-1721530b8d41)

**Comment by mfts** [comment]
/award 50 thanks! Happy to have you participate :)

more Papermark side quests here 👇
https://mfts.notion.site/Papermark-Hacktoberfest-Side-Quests-Challenges-111d3f870f008033935efe9f7702a3dc

@Sumit1911  please open seaparte issue to get rewarded
