### ISSUE TITLE
[🕹️] Design our new Papermark logo (150 Points per logo, 750 for the winner):

### ISSUE THREAD

**Issue by antilpiyush89** [mfts/papermark#856]
### What side quest or challenge are you solving?

Designing a new logo for Papermark

### Points

150 points assigned for submission
750 points assigned for winning

### Description

Created a logo for Papermark, following the provided color pallete

### Provide proof that you've completed the task

![image_2024-10-13_044041499](https://github.com/user-attachments/assets/a8dcad54-0a22-4748-a28e-458f78862d67)

![Untitled design (2)](https://github.com/user-attachments/assets/4ed8b289-ad63-4e54-a7e2-e68d5ab89e31)

**Comment by mfts** [comment]
/award 150 thanks! Happy to have you participate :)

more Papermark side quests here 👇
https://mfts.notion.site/Papermark-Hacktoberfest-Side-Quests-Challenges-111d3f870f008033935efe9f7702a3dc

@Sumit1911  please open separate issue to get rewarded
