### ISSUE TITLE
[🕹️]Follow Papermark X (Twitter)

### ISSUE THREAD

**Issue by mdaatifayman786** [mfts/papermark#858]
### What side quest or challenge are you solving?

Follow Papermark on X (Twitter)

### Points

50 points

### Description

followed papermark on twitter and also liked and retweeted launch post

### Provide proof that you've completed the task

![Screenshot 2024-10-12 233930](https://github.com/user-attachments/assets/e2c1f006-d473-4dd7-9915-c4534f8aab0e)
![Screenshot 2024-10-13 082820](https://github.com/user-attachments/assets/f981653c-8cb9-4ee4-973d-1cf6702e6719)

**Comment by mfts** [comment]
/award 50 thanks! Happy to have you participate :)

more Papermark side quests here 👇
https://mfts.notion.site/Papermark-Hacktoberfest-Side-Quests-Challenges-111d3f870f008033935efe9f7702a3dc

@amitkumarashutosh  please open separate issue to get rewarded
