### ISSUE TITLE
[🕹️] Follow Papermark LinkedIn

### ISSUE THREAD

**Issue by mdaatifayman786** [mfts/papermark#859]
### What side quest or challenge are you solving?

 Follow Papermark LinkedIn

### Points

50 points

### Description

Followed papermark on linkedin

### Provide proof that you've completed the task

![Screenshot 2024-10-13 083321](https://github.com/user-attachments/assets/dfb08469-73ab-4e9c-9678-3642b53c732a)

**Comment by mfts** [comment]
/award 50 thanks! Happy to have you participate :)

more Papermark side quests here 👇
https://mfts.notion.site/Papermark-Hacktoberfest-Side-Quests-Challenges-111d3f870f008033935efe9f7702a3dc
