### ISSUE TITLE
[🕹️] Follow Papermark LinkedIn

### ISSUE THREAD

**Issue by sanjaraiy** [mfts/papermark#860]
### What side quest or challenge are you solving?

Follow Papermark LinkedIn

### Points

50 points

### Description

Followed papermark on linkedin

### Provide proof that you've completed the task

![Screenshot 2024-10-13 091718](https://github.com/user-attachments/assets/368c125a-bc09-47cc-8e4f-df8134edf2cb)

**Comment by mfts** [comment]
/award 50 thanks! Happy to have you participate :)


more Papermark side quests here 👇
https://mfts.notion.site/Papermark-Hacktoberfest-Side-Quests-Challenges-111d3f870f008033935efe9f7702a3dc

@hirendhola  please open separate issue to get rewarded
