### ISSUE TITLE
[🕹️] Follow Papermark X / Twitter

### ISSUE THREAD

**Issue by sanjaraiy** [mfts/papermark#861]
### What side quest or challenge are you solving?

Follow Papermark on X or Twitter

### Points

50 points

### Description

followed papermark on twitter and also liked and retweeted launch post

### Provide proof that you've completed the task

![Screenshot 2024-10-13 092227](https://github.com/user-attachments/assets/d72cf2a6-0c3c-458e-a722-ccf807e1727f)

**Comment by mfts** [comment]
/award 50 thanks! Happy to have you participate :) 

more Papermark side quests here 👇
https://mfts.notion.site/Papermark-Hacktoberfest-Side-Quests-Challenges-111d3f870f008033935efe9f7702a3dc
