### ISSUE TITLE
[🕹️]Design our new Papermark logo

### ISSUE THREAD

**Issue by pragatiSrivastav** [mfts/papermark#862]
### What side quest or challenge are you solving?

Designing a new logo for Papermark

### Points

150 points assigned for submission
750 points assigned for winning

### Description

Created a logo for Papermark, following the provided color pallete

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/d840c1f9-725a-4f19-b1fb-b1a872b69669)

**Comment by mfts** [comment]
/award 150 thanks! Happy to have you participate :) 

more Papermark side quests here 👇
https://mfts.notion.site/Papermark-Hacktoberfest-Side-Quests-Challenges-111d3f870f008033935efe9f7702a3dc
