### ISSUE TITLE
[🕹️] Follow Papermark X (Twitter) Account

### ISSUE THREAD

**Issue by DChitale** [mfts/papermark#867]
### What side quest or challenge are you solving?

Follow [Papermark X (Twitter)](https://x.com/papermarkio) Account

### Points

50

### Description

Followed Papermark X (Twitter) Account

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/b5da4a31-5a54-4c49-a99f-e6f5e0c3a278)

**Comment by prathmesh-jagtap** [comment]
What side quest or challenge are you solving?
Follow [Papermark X (Twitter)](https://x.com/papermarkio) Account

Points
50

Description
Followed Papermark X (Twitter) Account

Provide proof that you've completed the task

![papermark](https://github.com/user-attachments/assets/f7138a4b-cf83-4aa2-9301-bcb748ebd5a5)

**Comment by MilanGohel** [comment]
#867

**Comment by mfts** [comment]
/award 50 thanks for participation!

@MilanGohel @AlfrinP @prathmesh-jagtap 
to everyone else commenting: if you not already, pls open your own issue with proof of completing the quest :
I can only award the author of an issue with points! Please ask in it others not assign to it.
