### ISSUE TITLE
[🕹️]Follow Papermark LinkedIn Page (50 Points):

### ISSUE THREAD

**Issue by DChitale** [mfts/papermark#868]
### What side quest or challenge are you solving?

Follow Papermark LinkedIn Page

### Points

50

### Description

Followed Papermark LinkedIn Page

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/90eeab9f-1075-475b-8c72-d9571ae84dd7)

**Comment by mfts** [comment]
/award 50 thanks for participation!

@Pranavx1 
if you not already, pls open your own issue with proof of completing the quest :
I can only award the author of an issue with points!

more Papermark side quests here 👇
https://mfts.notion.site/Papermark-Hacktoberfest-Side-Quests-Challenges-111d3f870f008033935efe9f7702a3dc
