### ISSUE TITLE
[🕹️]Meme Magic

### ISSUE THREAD

**Issue by DChitale** [mfts/papermark#869]
### What side quest or challenge are you solving?

Meme Magic

### Points

150

### Description

Made a fun meme :)

### Provide proof that you've completed the task

![meme](https://github.com/user-attachments/assets/9986c8ba-8d84-49aa-bfa2-639cdd859439)

**Comment by initeshjain** [comment]
![meme2](https://github.com/user-attachments/assets/593c5b50-254f-429f-afd9-1a7cb3bbc8cc)
![meme1](https://github.com/user-attachments/assets/6508890a-ef02-4ae7-b722-932924649794)

**Comment by initeshjain** [comment]
![meme3](https://github.com/user-attachments/assets/b513108c-346f-4641-8b6b-efdae3619c2d)

**Comment by mfts** [comment]
/award 150 love it!

@initeshjain @SanidhyaMadheshia 
to everyone else commenting: if you not already, pls open your own issue with proof of completing the quest :
I can only award the author of an issue with points!

more Papermark side quests here 👇
https://mfts.notion.site/Papermark-Hacktoberfest-Side-Quests-Challenges-111d3f870f008033935efe9f7702a3dc
