### ISSUE TITLE
[🕹️]Follow Papermark LinkedIn 

### ISSUE THREAD

**Issue by tushar110302** [mfts/papermark#871]
### What side quest or challenge are you solving?

Follow Papermark on LinkedIn

### Points

50

### Description

Followed papermark on linkedin

### Provide proof that you've completed the task

<img width="1200" alt="image" src="https://github.com/user-attachments/assets/aec051c1-4741-4202-b79b-c053ed8c5dae">

**Comment by AlfrinP** [comment]
![Screenshot 2024-10-13 121414](https://github.com/user-attachments/assets/113e9800-f10e-4e1e-a1c8-c8d1e501c32a)

**Comment by mfts** [comment]
/award 50 thanks for participation!

@AlfrinP  pls open your own issue with proof of completing the quest :
I can only award the author of an issue with points!

more Papermark side quests here 👇
https://mfts.notion.site/Papermark-Hacktoberfest-Side-Quests-Challenges-111d3f870f008033935efe9f7702a3dc
