### ISSUE TITLE
[🕹️]Follow Papermark on YouTube

### ISSUE THREAD

**Issue by tushar110302** [mfts/papermark#872]
### What side quest or challenge are you solving?

Papermark now has a Youtube channel. See https://github.com/mfts/papermark/issues/792.
Subscribe Papermark on youtube.

### Points

50

### Description

Subscribed to papermark youtube account

### Provide proof that you've completed the task

<img width="1468" alt="Screenshot 2024-10-13 at 11 49 01 AM" src="https://github.com/user-attachments/assets/b073535a-a45e-474d-8a02-0317b11da455">

**Comment by mfts** [comment]
/award 50 thanks for participation!

@tosif121  pls open your own issue with proof of completing the quest :
I can only award the author of an issue with points!

more Papermark side quests here 👇
https://mfts.notion.site/Papermark-Hacktoberfest-Side-Quests-Challenges-111d3f870f008033935efe9f7702a3dc
