### ISSUE TITLE
[🕹️] Follow on Twitter

### ISSUE THREAD

**Issue by MilanGohel** [mfts/papermark#874]
### What side quest or challenge are you solving?

Followed "[Papermark](https://x.com/papermarkio)" on X

### Points

50

### Description

Followed Papermark X (Twitter) Account

### Provide proof that you've completed the task

![paermark_x_account](https://github.com/user-attachments/assets/007047f0-9fe3-41f5-875e-aac508d23eb9)

**Comment by initeshjain** [comment]
Followed Papermark on X (Twitter)

![image](https://github.com/user-attachments/assets/9dbde055-accc-45a9-9215-2c88af5b7aea)

**Comment by mfts** [comment]
/award 50 

Thank you for the support and participating 

---
Everyone else, please open your own issue (@initeshjain )
