### ISSUE TITLE
[🕹️] Bug Hunter : Email Input Black Background After Choosing Dark Mode.

### ISSUE THREAD

**Issue by aritradevelops** [mfts/papermark#875]
### What side quest or challenge are you solving?

Bug Hunter

### Points

50 - 150

### Description

# Bug Description
The input email which was originally having white background, after sigining in and choosing dark mode and then signing out. The input button color has changed to black although the page have no theme switching context.

# Steps to reproduce
1. Sign In
2. Choose Dark Theme
3. Sign out

### Provide proof that you've completed the task

<img width="1439" alt="image" src="https://github.com/user-attachments/assets/1f414fa3-03da-4527-a83f-8c09501ccbf2">

**Comment by aritradevelops** [comment]
@mfts See I can fix this thing with one extra css class, but what do you want there eventually is my real concern, do you want to keep the theming over here, then I guess adding a theme switching button and implementing proper theming of every component will help. Or if you want to just keep this page in light theme then my fix will work. Let me know what do you want!  And I will request you to assign this to me, Thanks!

After My Fix : 
<img width="1092" alt="image" src="https://github.com/user-attachments/assets/d483f0cb-ee63-4603-8af0-601d86636ea2">
<img width="1043" alt="image" src="https://github.com/user-attachments/assets/133c8b6b-ce29-4e25-96d7-b5941eee160d">

**Comment by mfts** [comment]
@aritradevelops great find and good solution. yes this should always be a white background therefore overriding the `dark:` className makes sense. 

/award 100
