### ISSUE TITLE
[🕹️] Bug Hunter : Register a new passkey does not work.

### ISSUE THREAD

**Issue by aritradevelops** [mfts/papermark#876]
### What side quest or challenge are you solving?

Bug Hunter

### Points

50 - 150 

### Description

While trying to register a new passkey the api is failing (Bad Request Error) and it does not give any feedback on why that is happening

### Provide proof that you've completed the task

video link : https://streamable.com/8ml1o9
<img width="1429" alt="image" src="https://github.com/user-attachments/assets/803391e5-bbd6-4366-91d7-388f019a3618">

**Comment by aritradevelops** [comment]
I would like to get some more info on it, to fix it

**Comment by mfts** [comment]
/award 100 thanks for the bug report

**Comment by aritradevelops** [comment]
Hii @mfts I have checked this today, Now it is working, I'm assuming it was some plan-permission related issue. So this issue can be closed now! Thanks

**Comment by mfts** [comment]
@aritradevelops It was related to a callback url. We fixed that after the issue was raised :)
