### ISSUE TITLE
[🕹️] Linkedin follow Side Quest

### ISSUE THREAD

**Issue by initeshjain** [mfts/papermark#881]
### What side quest or challenge are you solving?

![image](https://github.com/user-attachments/assets/bdeaaac7-ebab-4177-a383-2cd3d3989a17)

### Points

50

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/d44ac9a1-5203-4217-967e-1a8199f11edf)

**Comment by mfts** [comment]
/award 50 thanks for participation!

@Fz-Faiz  pls open your own issue with proof of completing the quest :
I can only award the author of an issue with points!

more Papermark side quests here 👇
https://mfts.notion.site/Papermark-Hacktoberfest-Side-Quests-Challenges-111d3f870f008033935efe9f7702a3dc
