### ISSUE TITLE
[🕹️] YouTube Subscribe Side Quest

### ISSUE THREAD

**Issue by initeshjain** [mfts/papermark#882]
### What side quest or challenge are you solving?

![image](https://github.com/user-attachments/assets/a2f8db7f-fdda-40cb-8dfe-f7cecc236134)

### Points

50

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/a2f8db7f-fdda-40cb-8dfe-f7cecc236134)

**Comment by prwt888** [comment]
![ytsub](https://github.com/user-attachments/assets/a105247d-eef4-4915-9654-8d8480583264)

**Comment by mfts** [comment]
/award 50 thanks for participation!

@prwt888 pls open your own issue with proof of completing the quest :
I can only award the author of an issue with points!

more Papermark side quests here 👇
https://mfts.notion.site/Papermark-Hacktoberfest-Side-Quests-Challenges-111d3f870f008033935efe9f7702a3dc
