### ISSUE TITLE
[🕹️]Meme Magic Side Quest

### ISSUE THREAD

**Issue by initeshjain** [mfts/papermark#883]
### What side quest or challenge are you solving?

![image](https://github.com/user-attachments/assets/a33988fb-8d06-47de-a39b-7a3fcf8e9b8f)

![image](https://github.com/user-attachments/assets/c74f8ad2-a16f-4ed1-a58e-77672b6f641d)

### Points

150

### Provide proof that you've completed the task

https://x.com/initeshjain/status/1845369682473386378

https://x.com/initeshjain/status/1845369595466744188

**Comment by mfts** [comment]
/award 150 Thanks for fun memes!
more Papermark side quests here 👇
https://mfts.notion.site/Papermark-Hacktoberfest-Side-Quests-Challenges-111d3f870f008033935efe9f7702a3dc
