### ISSUE TITLE
[🕹️] Follow on X

### ISSUE THREAD

**Issue by Sakethpavan** [mfts/papermark#888]
### What side quest or challenge are you solving?

Follow Papermark on X

### Points

50

### Description

Followed Papermark on X

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/d004af94-347f-47be-82d9-fe445683d5fe)

**Comment by prwt888** [comment]
![Screenshot from 2024-10-13 14-23-27](https://github.com/user-attachments/assets/99d9fe0d-21dc-4e16-bbec-ff71a12abb33)

**Comment by mfts** [comment]
/award 50 thanks for participation!

@prwt888 pls open your own issue with proof of completing the quest :
I can only award the author of an issue with points!

more Papermark side quests here 👇
https://mfts.notion.site/Papermark-Hacktoberfest-Side-Quests-Challenges-111d3f870f008033935efe9f7702a3dc
