### ISSUE TITLE
[🕹️] Follow Papermark X (Twitter) Account

### ISSUE THREAD

**Issue by Kritikaadhikarii** [mfts/papermark#889]
### What side quest or challenge are you solving?

[🕹️] Follow Papermark X (Twitter) Account

### Points

50

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/1bce1078-eb65-40ff-8c92-92c4c9306165)

**Comment by mfts** [comment]
/award 50 Thanks for participating!

more Papermark side quests here 👇
https://mfts.notion.site/Papermark-Hacktoberfest-Side-Quests-Challenges-111d3f870f008033935efe9f7702a3dc
