### ISSUE TITLE
[🕹️] Follow Papermark LinkedIn Page

### ISSUE THREAD

**Issue by Kritikaadhikarii** [mfts/papermark#890]
### What side quest or challenge are you solving?

[🕹️] Follow Papermark LinkedIn Page

### Points

50

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/19ff6751-0156-4775-b752-ac2cf4a5d071)

**Comment by mfts** [comment]
/award 50 Thanks for participating!

more Papermark side quests here 👇
https://mfts.notion.site/Papermark-Hacktoberfest-Side-Quests-Challenges-111d3f870f008033935efe9f7702a3dc
