### ISSUE TITLE
[🕹️] Follow Papermark Youtube Page

### ISSUE THREAD

**Issue by Kritikaadhikarii** [mfts/papermark#891]
### What side quest or challenge are you solving?

[🕹️] Follow Papermark Youtube Page

### Points

50

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/7b32933e-5636-4f65-91fb-77ad5f7f6432)

**Comment by mfts** [comment]
/award 50 Thanks for participating!

more Papermark side quests here 👇
https://mfts.notion.site/Papermark-Hacktoberfest-Side-Quests-Challenges-111d3f870f008033935efe9f7702a3dc
