### ISSUE TITLE
[🕹️] Follow Papermark LinkedIn Page

### ISSUE THREAD

**Issue by utsavdotdev** [mfts/papermark#893]
### What side quest or challenge are you solving?

Follow [Papermark LinkedIn](https://linkedin.com/company/papermarkio) Page

### Points

50

### Description

Went to linkedin profile of Papermark and follow it

### Provide proof that you've completed the task

<img width="1415" alt="Screenshot 2024-10-13 at 4 27 57 PM" src="https://github.com/user-attachments/assets/9e91de7b-3fc4-4425-9918-3509bf47bfa1">

**Comment by mfts** [comment]
/award 50 Thanks for participating!

more Papermark side quests here 👇
https://mfts.notion.site/Papermark-Hacktoberfest-Side-Quests-Challenges-111d3f870f008033935efe9f7702a3dc
