### ISSUE TITLE
[🕹️] Follow Papermark Youtube Page

### ISSUE THREAD

**Issue by utsavdotdev** [mfts/papermark#894]
### What side quest or challenge are you solving?

Follow [Papermark Youtube](https://www.youtube.com/@papermarkio) Page

### Points

50

### Description

Went to Youtube channel of Papermark and subscribe it

### Provide proof that you've completed the task

<img width="1414" alt="Screenshot 2024-10-13 at 4 28 10 PM" src="https://github.com/user-attachments/assets/439daf49-7124-4487-9e86-0cf7311424f6">

**Comment by mfts** [comment]
/award 50 Thanks for participating!

more Papermark side quests here 👇
https://mfts.notion.site/Papermark-Hacktoberfest-Side-Quests-Challenges-111d3f870f008033935efe9f7702a3dc
