### ISSUE TITLE
[🕹️] Follow Papermark X (Twitter)

### ISSUE THREAD

**Issue by utsavdotdev** [mfts/papermark#895]
### What side quest or challenge are you solving?

Follow [Papermark X (Twitter)](https://x.com/papermarkio)

### Points

50

### Description

Went to X(twitter) profile of Papermark and followed it

### Provide proof that you've completed the task

<img width="1403" alt="Screenshot 2024-10-13 at 4 28 22 PM" src="https://github.com/user-attachments/assets/f74913c7-793d-44d8-8c8b-dbbc74fca30c">

**Comment by mfts** [comment]
/award 50 thanks for participation!

@Tejas-Dherange  pls open your own issue with proof of completing the quest :
I can only award the author of an issue with points!

more Papermark side quests here 👇
https://mfts.notion.site/Papermark-Hacktoberfest-Side-Quests-Challenges-111d3f870f008033935efe9f7702a3dc
