### ISSUE TITLE
[🕹️] Follow Papermark LinkedIn

### ISSUE THREAD

**Issue by DevGajjar28** [mfts/papermark#896]
### What side quest or challenge are you solving?

Follow [Papermark LinkedIn](https://www.linkedin.com/company/papermarkio/) page

My Linkedin: [Dev Gajjar](https://www.linkedin.com/in/dev-gajjar-318493309/)

### Points

50

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/cc316c61-a82b-4013-93dd-26735f3ef1ad)

**Comment by mfts** [comment]
/award 50 Thanks for participating!

more Papermark side quests here 👇
https://mfts.notion.site/Papermark-Hacktoberfest-Side-Quests-Challenges-111d3f870f008033935efe9f7702a3dc
