### ISSUE TITLE
[🕹️] Follow Papermark Youtube Page

### ISSUE THREAD

**Issue by DevGajjar28** [mfts/papermark#897]
### What side quest or challenge are you solving?

Follow [Papermark YouTube](https://www.youtube.com/@papermarkio)

### Points

50

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/f41309c3-f46f-4ea3-bbe7-19a442856985)

**Comment by mfts** [comment]
/award 50 Thanks for participating!

more Papermark side quests here 👇
https://mfts.notion.site/Papermark-Hacktoberfest-Side-Quests-Challenges-111d3f870f008033935efe9f7702a3dc
