### ISSUE TITLE
[🕹️] Follow Papermark on X(Twitter)

### ISSUE THREAD

**Issue by DevGajjar28** [mfts/papermark#898]
### What side quest or challenge are you solving?

 Follow [Papermakr X](https://x.com/papermarkio)

### Points

50

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/e8affe10-2ca2-4edc-b40b-700a9a069f87)

**Comment by mfts** [comment]
/award 50 Thanks for participating!

more Papermark side quests here 👇
https://mfts.notion.site/Papermark-Hacktoberfest-Side-Quests-Challenges-111d3f870f008033935efe9f7702a3dc
