### ISSUE TITLE
[🕹️] Side quest: Follow Papermark on X (Twitter)

### ISSUE THREAD

**Issue by Atharva-3000** [mfts/papermark#899]
### What side quest or challenge are you solving?

The side quest of Following Papermark on Twitter/X

### Points

50

### Description

Followed Papermark on Twitter/X

### Provide proof that you've completed the task

![Proof of Follow](https://github.com/user-attachments/assets/c1c4845e-111a-4372-83d8-014e41f6fa76)

**Comment by mfts** [comment]
/award 50 Thanks for participating!

more Papermark side quests here 👇
https://mfts.notion.site/Papermark-Hacktoberfest-Side-Quests-Challenges-111d3f870f008033935efe9f7702a3dc
