### ISSUE TITLE
[🕹️] Follow Papermark on LinkedIn

### ISSUE THREAD

**Issue by Atharva-3000** [mfts/papermark#900]
### What side quest or challenge are you solving?

The quest to follow Papermark on LinkedIn

### Points

50

### Description

Followed Papermark on LinkedIn

### Provide proof that you've completed the task

![Proof of Follow](https://github.com/user-attachments/assets/45a65fc3-752a-47d8-9a63-e27404de6e27)

**Comment by mfts** [comment]
/award 50 Thanks for participating!

more Papermark side quests here 👇
https://mfts.notion.site/Papermark-Hacktoberfest-Side-Quests-Challenges-111d3f870f008033935efe9f7702a3dc

**Comment by VinayB2** [comment]
Followed Papermark on LinkedIn
![Screenshot 2024-10-13 165917](https://github.com/user-attachments/assets/b3d2218c-d77f-4c0e-bf49-705da265f5cf)
