### ISSUE TITLE
[🕹️]Subscribe/Follow Papermark on Youtube

### ISSUE THREAD

**Issue by Atharva-3000** [mfts/papermark#901]
### What side quest or challenge are you solving?

The side quest to follow Papermark on YouTube

### Points

50

### Description

Followed/Subscribed to Papermark on YouTube

### Provide proof that you've completed the task

![Proof of Subscribe](https://github.com/user-attachments/assets/5f83caf5-fe34-4cd2-a208-7580ccfab8b4)

**Comment by mfts** [comment]
/award 50 Thanks for participating!

more Papermark side quests here 👇
https://mfts.notion.site/Papermark-Hacktoberfest-Side-Quests-Challenges-111d3f870f008033935efe9f7702a3dc
