### ISSUE TITLE
[🕹️] Follow on Linkedin

### ISSUE THREAD

**Issue by AlfrinP** [mfts/papermark#906]
### What side quest or challenge are you solving?

Follow Papermark on LinkedIn

### Points

50

### Description

Followed papermark on linkedin

### Provide proof that you've completed the task

![Screenshot 2024-10-13 121414](https://github.com/user-attachments/assets/84f65d5b-c52d-4d51-8633-aaba2f3b9d57)

**Comment by mfts** [comment]
/award 50 

Thank you for the support and participating
