### ISSUE TITLE
Login/Sign up (alternative to google)

### ISSUE THREAD

**Issue by shnai0** [mfts/papermark#91]
I think it would be valuable to have Google sign up  as not everyone wouls like to sign up with google.

**Comment by manpoffc** [comment]
What other alternatives would you like to have?

**Comment by mfts** [comment]
@manpoffc we'd love to add an email magic link. I haven't gotten to it yet. if you want to tackle it, that would be awesome

**Comment by manpoffc** [comment]
Hey @mfts ,
Are you willing to do an in house magic link implementation or you prefer using 3rd party API for that?

**Comment by mfts** [comment]
@manpoffc Should be done with next-auth's built-in magic link

**Comment by manpoffc** [comment]
Alright, thank you for the info. I’ll give it a go.

**Comment by SammitBadodekar** [comment]
@manpoffc  are you still working on it ?

**Comment by manpoffc** [comment]
@SammitBadodekar didnt start yet but you could take this up 👍🏻

**Comment by jflattery** [comment]
If I can piggyback on this, I would love to see support for other Identity Providers namely [Authentik](https://github.com/goauthentik/authentik).

**Comment by uncleSlayer** [comment]
hi, can I be assigned this? I'd love to work on it.

**Comment by Prakhar-FF13** [comment]
@mfts hey is there a discord group for this project? I worked on this and got It running on dev environment using dev credentials provided by resend.
However if I try to use existing paperwork.io I get a 403 error saying it is not added in domain.
Screenshot below shows it works if using resend dev credentials:
<img width="978" alt="Screenshot 2023-11-18 at 10 00 39 PM" src="https://github.com/mfts/papermark/assets/23739449/93ecb0da-b0ce-4c12-9fc4-401de3444775">
Below screenshot shows doesn't work using existing email.
<img width="978" alt="Screenshot 2023-11-18 at 10 00 57 PM" src="https://github.com/mfts/papermark/assets/23739449/42bd77a9-72d8-418f-aa23-62f04d7ae822">

Results of both:
<img width="978" alt="Screenshot 2023-11-18 at 10 00 22 PM" src="https://github.com/mfts/papermark/assets/23739449/02fbe67e-f21f-4697-9947-423e81dbc1f3">

**Comment by mfts** [comment]
Closing this issue as we have other login / signup options
