### ISSUE TITLE
[🕹️]Design a new Papermark logo

### ISSUE THREAD

**Issue by AnshMehta24** [mfts/papermark#912]
### What side quest or challenge are you solving?

# Design a new Papermark logo

### Points

# 150

### Provide proof that you've completed the task

# Logo 1:
![PaperMark_Logo1](https://github.com/user-attachments/assets/9dc417dd-f095-45b9-a831-cfa97030aa33)

# Logo 2:
![PaperMark_Logo2](https://github.com/user-attachments/assets/dd179947-85d6-423a-b0c0-0685cc7997b9)

**Comment by mfts** [comment]
/award 150 

Thank you for the logo!
