### ISSUE TITLE
[🕹️]Follow papermark on Twitter

### ISSUE THREAD

**Issue by sohelhussain** [mfts/papermark#913]
### What side quest or challenge are you solving?

Follow papermark on Twitter

### Points

50 points

### Description

By retweeting and liking my post, you're not only supporting me but also helping spread the word about the importance of open-source contributions! Together, we can inspire more people to join this incredible movement!

### Provide proof that you've completed the task

<img width="1141" alt="Screenshot 2024-10-13 at 7 44 17 PM" src="https://github.com/user-attachments/assets/3aa64d90-9b15-42e0-bd2d-2f1ad4a6cf5c">

**Comment by Sukhpreet7137** [comment]
![image](https://github.com/user-attachments/assets/3854f869-3208-4f8b-a43a-af9d9aa3e09c)

**Comment by mfts** [comment]
/award 50 

Thank you for the support and participating 

---
Everyone else, please open your own issue (@Sukhpreet7137 )
