### ISSUE TITLE
[🕹️] side quest: Follow Papermark LinkedIn Page

### ISSUE THREAD

**Issue by Sa1-Codes** [mfts/papermark#916]
### What side quest or challenge are you solving?

Follow [Papermark LinkedIn](https://linkedin.com/company/papermarkio) Page

### Points

50

### Description

followed papermark's linkedin page.

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/b4796eb4-cab9-452b-a0ed-501bb7738912)

**Comment by Tanmayshi** [comment]
![Screenshot (74)](https://github.com/user-attachments/assets/d48cc95f-9301-43b6-80ec-5bc17a38a23d)

**Comment by Tanmayshi** [comment]
I have followed the page.

**Comment by mfts** [comment]
/award 50 

Thank you for the support and participating 

---
Everyone else, please open your own issue (@Tanmayshi)
