### ISSUE TITLE
[🕹️] side quest: Follow Papermark X (Twitter) Account

### ISSUE THREAD

**Issue by Sa1-Codes** [mfts/papermark#917]
### What side quest or challenge are you solving?

Follow [Papermark X (Twitter)](https://x.com/papermarkio) Account

### Points

50

### Description

followed papermark's official twitter(X) handle.

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/f402ed9e-8909-41db-8e82-40afc996ce0a)

**Comment by mfts** [comment]
/award 50 

Thank you for the support and participating
