### ISSUE TITLE
[🕹️] Followed Papermark on YouTube (50 Points)

### ISSUE THREAD

**Issue by abdulrehmanwaseem** [mfts/papermark#920]
### What side quest or challenge are you solving?

Papermark now has a Youtube channel. See https://github.com/mfts/papermark/issues/792

### Points

50

### Description

Subscribed the papermark channel on youtube.

### Provide proof that you've completed the task

![{87598D4B-8867-4AA3-B8AD-647FE4293116}](https://github.com/user-attachments/assets/69f72617-751e-41a9-b90b-f8580112ce3c)

**Comment by mfts** [comment]
/award 50 

Thank you for the support and participating
