### ISSUE TITLE
[🕹️ ] Follow Papermark on YouTube (50 points)

### ISSUE THREAD

**Issue by pnk-ltoc-892** [mfts/papermark#922]
### What side quest or challenge are you solving?

 Papermark now has a Youtube channel. See #792 

Subscribed To Papermark on Youtube

### Points

50

### Provide proof that you've completed the task

![Screenshot 2024-10-14 004814](https://github.com/user-attachments/assets/e5b592ad-f76a-4d2e-a498-585e11f33629)

**Comment by mfts** [comment]
/award 50 

Thank you for the support and participating 

---
Everyone else, please open your own issue (@infovishal01)
