### ISSUE TITLE
[🕹️] Follow Papermark on YouTube (50 points)

### ISSUE THREAD

**Issue by trinetra110** [mfts/papermark#923]
### What side quest or challenge are you solving?

Papermark now has a Youtube channel. See #792 

### Points

50

### Provide proof that you've completed the task

![Screenshot 2024-10-14 011416](https://github.com/user-attachments/assets/988e3046-a09d-446a-89c1-757e6d09c2f8)

**Comment by mfts** [comment]
/award 50 thanks for the support and follow
