### ISSUE TITLE
[🕹️]Create a "new" logo for Papermark

### ISSUE THREAD

**Issue by onchky** [mfts/papermark#924]
### What side quest or challenge are you solving?

[🕹️] Create a "new" logo for Papermark

### Points

150

### Description

A logo which can be used in any size and any medium filled with any color. An isometric view of two sheets of paper with shadow forming an abstract “P”.

### Provide proof that you've completed the task

<img width="640" alt="Papermark" src="https://github.com/user-attachments/assets/1ad5e319-f921-48e8-b468-d9a7ddd6f14a">

![Papermark Grid](https://github.com/user-attachments/assets/c0ab5611-d631-4ce3-bdcb-c9111c9556db)

**Comment by mfts** [comment]
/award 150 

such a lovely logo! Thanks @onchky

**Comment by mfts** [comment]
@onchky your logo was the voted the highest. 

I will prepare a quick handover of creative assets, so we can then eventually use the logo. 
Could you please share your email address and full name with me here or by dm on twitter: x.com/mfts0 so i can share it with you.

Thanks, 
Marc
