### ISSUE TITLE
[🕹️] Follow Papermark on YouTube (50 points)

### ISSUE THREAD

**Issue by DanishAliUmar** [mfts/papermark#925]
### What side quest or challenge are you solving?

Papermark now has a Youtube channel. See https://github.com/mfts/papermark/issues/792

### Points

50

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/4171317d-92cc-427a-b7e1-c422f36da939)

**Comment by mfts** [comment]
/award 50 thanks for the support and follow
