### ISSUE TITLE
[🕹️] Improve document 📄 "Action" tab (Points)

### ISSUE THREAD

**Issue by AshishViradiya153** [mfts/papermark#927]
### What side quest or challenge are you solving?

Fixes https://github.com/mfts/papermark/pull/678

Its contain two fixes

- The user can create a data room using the "Action" tabs if they have the correct subscription; otherwise, an "Upgrade Plan" tab will be shown.
- Display a tooltip for "Upload a new version." (The problem is that if we wrap the button with a tooltip, the button event doesn't work : Fixed)

@mfts can award points here.

### Points

?

### Provide proof that you've completed the task

PR

**Comment by mfts** [comment]
Great! 

/award 150

**Comment by AshishViradiya153** [comment]
Thanks @mfts
