### ISSUE TITLE
[🕹️]Follow Papermark on Youtube

### ISSUE THREAD

**Issue by Naprila** [mfts/papermark#929]
### What side quest or challenge are you solving?

Papermark now has a Youtube channel. See https://github.com/mfts/papermark/issues/792

### Points

50

### Description

Subscribed to papermark channel on youtube

### Provide proof that you've completed the task

<img width="1424" alt="Screenshot 2024-10-14 at 10 38 54 AM" src="https://github.com/user-attachments/assets/fb50bf48-791f-498d-beda-bd1d59a8ed50">

**Comment by Sans25VS** [comment]
![Screenshot (116)](https://github.com/user-attachments/assets/ec50eb1e-0107-4853-b80d-db8421838f97)
@Naprila Subscribed :)

**Comment by mfts** [comment]
/award 50 

thanks for the follow 

----
everyone else please open your own issue to get awarded (@Sans25VS)
