### ISSUE TITLE
[🕹️]Made Logo of papermark

### ISSUE THREAD

**Issue by Meetpidev** [mfts/papermark#934]
### What side quest or challenge are you solving?

Created Logo for papermark in canva.

### Points

150

### Description

Created Logo for papermark in canva.

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/067d179d-23f3-4a79-9fad-709257230dc3)

**Comment by Meetpidev** [comment]
@mfts please review it

**Comment by Meetpidev** [comment]
@mfts please review it

**Comment by mfts** [comment]
/award 150 

thanks for the logo

**Comment by mfts** [comment]
@Meetpidev would you mind uploading a higher quality version here please

**Comment by Meetpidev** [comment]
@mfts  higher quality version of Logo..
![image](https://github.com/user-attachments/assets/bc34ace5-8a09-460c-9c5a-4c6f6355eeac)

**Comment by Meetpidev** [comment]
@mfts  i've made new changes in logo.. that are given below.. you can select based on your choice.. 
1) 
![Screenshot 2024-10-15 195426](https://github.com/user-attachments/assets/84de9ca3-f52d-47df-aced-20e675456897)

2) 
![Screenshot 2024-10-15 194529](https://github.com/user-attachments/assets/f794deef-92ad-411e-a326-eed5bd9738d1)

3) 
![image](https://github.com/user-attachments/assets/f05100f0-291f-4690-9cc9-266bca78212f)

**Comment by Meetpidev** [comment]
@mfts  requested to review it
