### ISSUE TITLE
[🕹️][BUG]:"Upgrade" Button Padding and Responsiveness Issue on md Screens

### ISSUE THREAD

**Issue by rishipatel9** [mfts/papermark#939]
### What side quest or challenge are you solving?

<img width="343" alt="to fix" src="https://github.com/user-attachments/assets/1d55d05b-0323-4c10-a6c3-77a4a8c1c732">

### Points

200

### Description

The "Upgrade" buttons used for inviting members are not properly responsive on medium (md) screens. The button does not resize appropriately, and the padding is excessive, making the layout appear misaligned and oversized on md screens.

### Provide proof that you've completed the task

/assign

**Comment by rishipatel9** [comment]
oh yes my bad

**Comment by JeevaRamanathan** [comment]
No problem
