### ISSUE TITLE
[🕹️] Dataroom view ui : hotFix

### ISSUE THREAD

**Issue by AshishViradiya153** [mfts/papermark#951]
### What side quest or challenge are you solving?

Always show scroll and on bottom bg-color

![image](https://github.com/user-attachments/assets/a657c629-7e97-4b09-8e91-e8b332efefe3)

if List is big!!!

![image](https://github.com/user-attachments/assets/b16691ad-9cf7-472a-ba74-8bbeedc47089)

### Points

@mfts ?

### Provide proof that you've completed the task

PR

**Comment by AshishViradiya153** [comment]
@Tejas-Dherange Plases dont work on it, PR in review

**Comment by AshishViradiya153** [comment]
@mfts Please check this one. I think it should be live as soon as possible...
Thank you.

**Comment by mfts** [comment]
@AshishViradiya153 Checking them in a bit. Thanks for the PR

**Comment by AshishViradiya153** [comment]
@mfts, I’d like to remind you to add the points for issue creation as well.
