### ISSUE TITLE
[🕹️] Follow Twitter Page of Papermark

### ISSUE THREAD

**Issue by AliYar-Khan** [mfts/papermark#963]
### What side quest or challenge are you solving?

Following the paper mark account on X

### Points

50

### Description

I have followed the Papermark account on X

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/951386de-995b-4911-8c62-c3c8428a8445)

**Comment by mfts** [comment]
/award 50

thanks for the follow
