### ISSUE TITLE
[🕹️] Subscribe to Youtube Channel

### ISSUE THREAD

**Issue by AliYar-Khan** [mfts/papermark#964]
### What side quest or challenge are you solving?

Subscribing to YouTube channel

### Points

50

### Description

Subscribed to Youtube Channel

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/2e35da55-829e-4c0a-83a1-ef9cff80c2f8)

**Comment by spawade99** [comment]
I have subscribed to a Papermark Youtube channel, here is the proof.
![image](https://github.com/user-attachments/assets/b35e28b1-a6b7-4527-87b7-233c61797290)

**Comment by mfts** [comment]
/award 50

thanks for the follow
