### ISSUE TITLE
[🕹️] Follow the Linkedin Page

### ISSUE THREAD

**Issue by AliYar-Khan** [mfts/papermark#965]
### What side quest or challenge are you solving?

Follow the Papermark Linkedin Page

### Points

50

### Description

I have followed the Papermark Linkedin Page

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/09b6c26e-abc3-4aa3-b1f9-909e7fd89e36)

**Comment by mfts** [comment]
/award 50

thanks for the follow on Linkedin
