### ISSUE TITLE
Replace Loading text with Loading Icon

### ISSUE THREAD

**Issue by vndpal** [mfts/papermark#97]
In the application there are 3 places where text "Loading..." is rendered however we already have a loading Icon in the application in the form of "LoadingSpinner". 

While viewing a document

![image](https://github.com/mfts/papermark/assets/39481600/92d17df8-3b39-4b8b-8abd-3b983176186a)

After clicking on a document in documents page:

![image](https://github.com/mfts/papermark/assets/39481600/8ce8dae6-e004-4e07-a7d9-dd7516b6cdc9)
 
These Loading text should be replaced with the loading icon.

**Comment by mfts** [comment]
Nice! Yes I saw your PR with the LoadingSpinner. Will get it merged asap
