### ISSUE TITLE
[🕹️] Subscribe to Youtube Channel 

### ISSUE THREAD

**Issue by spawade99** [mfts/papermark#971]
### What side quest or challenge are you solving?

Subscribing to YouTube channel

### Points

50

### Description

I have followed Papermark Youtube channel.

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/61ca878d-e4bc-4b09-9f6c-346191b3d6bc)

**Comment by mfts** [comment]
/award 50 

thanks for the follow
