### ISSUE TITLE
[🕹️]Follow Papermark on YouTube (50 points)

### ISSUE THREAD

**Issue by Naprila** [mfts/papermark#972]
### What side quest or challenge are you solving?

Papermark now has a Youtube channel. See https://github.com/mfts/papermark/issues/792

### Points

50

### Description

Subscribed to papermark youtube channel.

### Provide proof that you've completed the task

<img width="1424" alt="Screenshot 2024-10-14 at 10 38 54 AM" src="https://github.com/user-attachments/assets/bbd371dc-e928-4ab2-901c-2dd73b8ab0ab">

**Comment by mfts** [comment]
/award 50

thanks for the follow
