### ISSUE TITLE
[🕹️]side quest: Follow Papermark X (Twitter) Account 

### ISSUE THREAD

**Issue by Naprila** [mfts/papermark#973]
### What side quest or challenge are you solving?

Follow [Papermark X (Twitter)](https://x.com/papermarkio) Account

### Points

50

### Description

followed papermark's official twitter(X) handle.

### Provide proof that you've completed the task

<img width="1320" alt="Screenshot 2024-10-14 at 10 38 17 PM" src="https://github.com/user-attachments/assets/aa232782-8c5a-47b3-9512-cfebae2476f3">

**Comment by mfts** [comment]
/award 50

thanks for the follow
