### ISSUE TITLE
[🕹️]side quest: Follow Papermark LinkedIn Page

### ISSUE THREAD

**Issue by Naprila** [mfts/papermark#974]
### What side quest or challenge are you solving?

Follow [Papermark LinkedIn](https://linkedin.com/company/papermarkio) Page

### Points

50

### Description

followed papermark's linkedin page.

### Provide proof that you've completed the task

<img width="1320" alt="Screenshot 2024-10-14 at 10 40 17 PM" src="https://github.com/user-attachments/assets/c37cc949-bcfd-41af-85ce-794bfc934c9c">

**Comment by shuvishma** [comment]
![Screenshot 2024-10-14 233749](https://github.com/user-attachments/assets/6e436a03-d8d5-4ddf-bb41-3d4a11e9668a)

**Comment by mfts** [comment]
/award 50

thanks for the follow
