### ISSUE TITLE
[🕹️] Starry-eyed Supporter

### ISSUE THREAD

**Issue by DevGajjar28** [mfts/papermark#975]
### What side quest or challenge are you solving?

Starred a Repo from 5 friend.

### Points

150

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/03d3378a-4236-41ec-a9af-439881503f09)   
![image](https://github.com/user-attachments/assets/ea51de23-cd8a-45dc-b7fc-2aeb5a7335b6)
![image](https://github.com/user-attachments/assets/2bc7fd41-f61e-4ee8-bdb9-303d29316de7)
![image](https://github.com/user-attachments/assets/2976ad74-f17f-4dc2-8b98-73f5f426beb6)
![image](https://github.com/user-attachments/assets/43d8f2ab-bcdc-43db-b8be-77c29d4db8ec)

Usernames with proof direct starred page :

[heerchokshi](https://github.com/heerchokshi?tab=stars)
[mihirsolanki3](https://github.com/mihirsolanki3?tab=stars)
[kalp1801](https://github.com/kalp1801?tab=stars)
[Monkey-D-Luffy-1](https://github.com/Monkey-D-Luffy-1?tab=stars)
[nimish salecha](https://github.com/nimish-salecha?tab=stars)

**Comment by mfts** [comment]
/award 150

thanks so much for spreading the word! that really helps us 🫶
