### ISSUE TITLE
[🕹️]Side Quest:Follow Papermark X (Twitter) Account (50 Points)

### ISSUE THREAD

**Issue by A10-g** [mfts/papermark#977]
### What side quest or challenge are you solving?

Follow [Papermark X (Twitter)](https://x.com/papermarkio) Account (50 Points)

### Points

50

### Description

Followed [Papermark X (Twitter)](https://x.com/papermarkio) Account (50 Points)

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/90935a9c-7018-4ade-8173-5bd5de43ac07)

**Comment by mfts** [comment]
/award 50

thanks for the follow and participating
