### ISSUE TITLE
[🕹️] Gif Magic

### ISSUE THREAD

**Issue by DevGajjar28** [mfts/papermark#978]
### What side quest or challenge are you solving?

made Gif on Giphy

### Points

150

### Provide proof that you've completed the task

https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExZGI2dGljZjhlNjhrem4yd2kzbzg1anEyZHd2Y2dnOGh0NGJ6bW5vbyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/1oZkXXLHBMs0t8gwbO/giphy.gif

![image](https://github.com/user-attachments/assets/03ed8977-aac6-408c-82ba-db76b0d9dbd7)

**Comment by mfts** [comment]
/award 150

amazing meme / gif
