### ISSUE TITLE
[🕹️] Follow Papermark X (Twitter) Account 

### ISSUE THREAD

**Issue by tanishq-singh-2407** [mfts/papermark#979]
### What side quest or challenge are you solving?

Follow Papermark X (Twitter) Account 

### Points

50

### Provide proof that you've completed the task

<img width="1567" alt="Screenshot 2024-10-14 at 23 23 29" src="https://github.com/user-attachments/assets/1bccccb2-e7e8-45a6-8e6b-7cb907e6ce6b">

**Comment by mfts** [comment]
/award 50 

thanks for the follow
