### ISSUE TITLE
[🕹️]Designed new logo for Papermark

### ISSUE THREAD

**Issue by Naprila** [mfts/papermark#989]
### What side quest or challenge are you solving?

Design our new Papermark logo 

### Points

150 Points per logo

### Description

Created three diff logo for Papermark

### Provide proof that you've completed the task

logo 1:
![cover](https://github.com/user-attachments/assets/2ffe5870-8013-4bd4-8c70-807c85eb789d)

logo 2:
![cover](https://github.com/user-attachments/assets/14e4511e-6e5a-479c-bfc5-e24118ed093e)

logo 3:
![cover](https://github.com/user-attachments/assets/bb1588da-b767-43e0-a786-8afc223238ff)

**Comment by mfts** [comment]
/award 150

thanks for the logo submission
