### ISSUE TITLE
[🕹️]Designed new logo for Papermark

### ISSUE THREAD

**Issue by DanishAliUmar** [mfts/papermark#990]
### What side quest or challenge are you solving?

Design our new Papermark logo

### Points

150 Points per logo

### Description

Created three diff logo for Papermark

### Provide proof that you've completed the task

logo 1:
![paperMark](https://github.com/user-attachments/assets/04da4b32-5d34-42c1-ae8c-d6d55fc12ad9)

logo 2:
![paperMark (1)](https://github.com/user-attachments/assets/719866c6-89a8-4dd3-85b9-5f16610d4d4d)

logo 3:
![paperMark (2)](https://github.com/user-attachments/assets/859f83e0-bedd-4ba9-94e6-4a35961b6334)

**Comment by mfts** [comment]
/award 150 

thanks for the logo submission
