### ISSUE TITLE
[🕹️] Side Quest : Follow Papermark on X (Twitter) Account

### ISSUE THREAD

**Issue by AmanPathan** [mfts/papermark#992]
### What side quest or challenge are you solving?

Follow [Papermark X (Twitter)](https://x.com/papermarkio) Account (50 Points)

### Points

50

### Description

I followed Papermark on X (Twitter) and I have attached the proof of the same.

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/4b7b88b3-efbf-4e92-a59d-5c1e2833e93e)

**Comment by mfts** [comment]
/award 50

thanks for the follow
