### ISSUE TITLE
[🕹️] Side Quest : Follow Papermark on LinkedIn Page (50 Points)

### ISSUE THREAD

**Issue by AmanPathan** [mfts/papermark#993]
### What side quest or challenge are you solving?

Follow [Papermark LinkedIn](https://linkedin.com/company/papermarkio) Page (50 Points)

### Points

50 Points

### Description

I followed Papermark on LinkedIn and I have attached the screenshot as the proof.

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/3605df66-c5a9-4f69-ba12-23d12922f18f)

**Comment by MunishMummadi** [comment]
I followed Papermark on LinkedIn and I have attached the screenshot as the proof.

![Screenshot 2024-10-14 at 19 03 27](https://github.com/user-attachments/assets/db0d912b-9193-4d1b-ab94-2c601edae87c)

**Comment by shuvishma** [comment]
Follow Papermark

![Screenshot 2024-10-14 233749](https://github.com/user-attachments/assets/ef4e4875-9484-46ce-b158-5db49e604613)

**Comment by Git-Suraj-hub** [comment]
I followed Papermark on LinkedIn and I have attached the screenshot as the proof.

**Provide proof that you've completed the task**
![Screenshot 2024-10-15 161149](https://github.com/user-attachments/assets/0d300f67-90e3-499f-86ce-427e24da3669)

**Comment by mfts** [comment]
/award 50

thanks for the follow 

---
everyone else please open your own issue (@Git-Suraj-hub)
