### ISSUE TITLE
[🕹️] Side Quest: Follow Papermark Youtube Page (50 Points)

### ISSUE THREAD

**Issue by AmanPathan** [mfts/papermark#994]
### What side quest or challenge are you solving?

Follow [Papermark Youtube](https://www.youtube.com/@papermarkio) Page (50 Points)

### Points

50 Points

### Description

I followed Papermark on YouTube and I have attached the screenshot as proof.

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/1b294e9b-61e5-4082-9bf4-9652bb9324f9)

**Comment by MunishMummadi** [comment]
here you go ![Screenshot 2024-10-14 at 19 01 51](https://github.com/user-attachments/assets/2e61f8fc-8679-4b29-a160-8d26af712115)

**Comment by hanzlah101** [comment]
What side quest or challenge are you solving?
Follow [Papermark Youtube](https://www.youtube.com/@papermarkio) Page (50 Points)

Points
50 Points

Description
I followed Papermark on YouTube and I have attached the screenshot as proof.

Provide proof that you've completed the task
![Screenshot 2024-10-15 at 6 50 25 AM](https://github.com/user-attachments/assets/2a1fe55e-691f-42a6-b42a-9062c3ea7a90)

**Comment by Gdhoundiyal** [comment]
What side quest or challenge are you solving?
Follow [Papermark Youtube](https://www.youtube.com/@papermarkio) Page (50 Points)

Points
50 Points

Description
I followed Papermark on YouTube and I have attached the screenshot as proof.

Provide proof that you've completed the task
![image](https://github.com/user-attachments/assets/ebe45e66-a976-46af-be7c-52f1cf89d66d)

**Comment by mfts** [comment]
/award 50

thanks for the follow 

---
everyone else please open your own issue (@Gdhoundiyal , @hanzlah101)
