### ISSUE TITLE
[🕹️]Youtube Subscribed

### ISSUE THREAD

**Issue by darknight26** [mfts/papermark#995]
### What side quest or challenge are you solving?

Subscribe to youtube channel.
![image](https://github.com/user-attachments/assets/ad57534c-cf9b-4dab-bb0f-5da8c62784e4)

### Points

50

### Provide proof that you've completed the task

![image](https://github.com/user-attachments/assets/767024f3-3af4-4ee2-aef2-78f38e8071eb)

**Comment by shuvishma** [comment]
Subscribe your youtube channel
![papermark-ytd](https://github.com/user-attachments/assets/228abd9a-6f5b-4e69-a1d7-4c4cf8b4dd70)

**Comment by Ajeya2691** [comment]
Subscribed !

![Screenshot 2024-10-15 131743](https://github.com/user-attachments/assets/0a21c6ce-264c-4428-b86c-662d44d2a956)

**Comment by mfts** [comment]
/award 50 

--

everyone else please open your own issues, if you haven't yet
