### ISSUE TITLE
[🕹️] Starry-eyed Supporter

### ISSUE THREAD

**Issue by Atharva-3000** [mfts/papermark#996]
### What side quest or challenge are you solving?

Asking out 5 friends to star the repo!

### Points

150

### Description

Successfully made them star the repo 😋 and lectured them about how awesome oss.gg is!!

### First:
![WhatsApp Image 2024-10-14 at 14 15 07_ac2212ed](https://github.com/user-attachments/assets/9aac083b-245a-4ec7-bdf4-54d24250c145)

### Second
![WhatsApp Image 2024-10-14 at 17 17 27_df9eff52](https://github.com/user-attachments/assets/8b4f000c-f320-484c-af99-0f0c34ab007b)

### Third:
![WhatsApp Image 2024-10-14 at 18 22 27_fabcefda](https://github.com/user-attachments/assets/a8988c5a-b24e-463f-b825-9fd5b0c92c86)

### Fourth:
![WhatsApp Image 2024-10-14 at 22 29 20_2e9ec035](https://github.com/user-attachments/assets/d9acdda1-e5a9-41e5-bf4d-a69fdc027de1)

### Fifth:
<img width="1440" alt="Screenshot 2024-10-15 at 9 39 09 AM" src="https://github.com/user-attachments/assets/9c45b9d5-0365-48af-b563-bc3b4c5e29fd">

**Comment by mfts** [comment]
/award 150 

thanks for sharing papermark with your friends
